Repository DataDog/terraform-provider-datadog, pull requests merged in 2018-08, with the labels that each got.

#83 Fix typo in timeboard documentation
  website/docs/r/timeboard.html.markdown
Labels: documentation

#81 docs: monitor type
  website/docs/r/monitor.html.markdown
Labels: documentation

#84 Update client to v2.11.0 Release
  datadog/config.go
  datadog/resource_datadog_downtime.go
  datadog/resource_datadog_downtime_test.go
  datadog/resource_datadog_metric_metadata.go
  datadog/resource_datadog_metric_metadata_test.go
  datadog/resource_datadog_monitor.go
  datadog/resource_datadog_monitor_test.go
  datadog/resource_datadog_timeboard.go
  datadog/resource_datadog_timeboard_test.go
  datadog/resource_datadog_user.go
  datadog/resource_datadog_user_test.go
  vendor/github.com/zorkian/go-datadog-api/LICENSE
  vendor/github.com/zorkian/go-datadog-api/Makefile
  vendor/github.com/zorkian/go-datadog-api/README.md
  vendor/github.com/zorkian/go-datadog-api/alerts.go
  vendor/github.com/zorkian/go-datadog-api/checks.go
  vendor/github.com/zorkian/go-datadog-api/client.go
  vendor/github.com/zorkian/go-datadog-api/comments.go
  vendor/github.com/zorkian/go-datadog-api/dashboard_lists.go
  vendor/github.com/zorkian/go-datadog-api/dashboards.go
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/downtimes.go
  vendor/github.com/zorkian/go-datadog-api/events.go
  vendor/github.com/zorkian/go-datadog-api/generate.go
  vendor/github.com/zorkian/go-datadog-api/helpers.go
  vendor/github.com/zorkian/go-datadog-api/hosts.go
  vendor/github.com/zorkian/go-datadog-api/integrations.go
  vendor/github.com/zorkian/go-datadog-api/metric_metadata.go
  vendor/github.com/zorkian/go-datadog-api/monitors.go
  vendor/github.com/zorkian/go-datadog-api/request.go
  vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
  vendor/github.com/zorkian/go-datadog-api/screenboards.go
  vendor/github.com/zorkian/go-datadog-api/search.go
  vendor/github.com/zorkian/go-datadog-api/series.go
  vendor/github.com/zorkian/go-datadog-api/snapshot.go
  vendor/github.com/zorkian/go-datadog-api/tags.go
  vendor/github.com/zorkian/go-datadog-api/users.go
  vendor/vendor.json
Labels: size/L

#85 Deprecate is_admin for resource "datadog_user"
  datadog/resource_datadog_user.go
Labels: size/XS

#86 Prepare 1.1.1
  CHANGELOG.md
Labels: size/S
