Repository DataDog/terraform-provider-datadog, pull requests merged in 2018-11, with the labels that each got.

#106 Add new hostmap widget options (node type, fill_min and fill_max).
  datadog/resource_datadog_timeboard.go
  website/docs/r/timeboard.html.markdown
Labels: size/S

#114 Prepare for 1.5.0
  CHANGELOG.md
Labels: size/XS

#123 Added install and uninstall make targets
  GNUmakefile
Labels: size/XS

#125 Explicitly silent a monitor when needed
  datadog/resource_datadog_monitor.go
Labels: size/XS

#126 Fix diff for `palette_flip`
  datadog/resource_datadog_timeboard.go
  datadog/resource_datadog_timeboard_test.go
Labels: size/M

#121 Bump datadog api to v2.18.0 and add support for include units and zero
  CHANGELOG.md
  datadog/resource_datadog_screenboard.go
  datadog/resource_datadog_timeboard.go
  datadog/resource_datadog_timeboard_test.go
  vendor/github.com/zorkian/go-datadog-api/dashboards.go
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/monitors.go
  vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
  vendor/github.com/zorkian/go-datadog-api/screenboards.go
  vendor/vendor.json
Labels: size/L

#127 bump client to latest, fix precision and yaxis.include_* fields
  datadog/resource_datadog_timeboard.go
  datadog/resource_datadog_timeboard_test.go
  vendor/github.com/zorkian/go-datadog-api/dashboards.go
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/helpers.go
  vendor/github.com/zorkian/go-datadog-api/monitors.go
  vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
  vendor/vendor.json
Labels: size/L

#124 Fixes crash on import when separator is missing
  datadog/resource_datadog_integration_aws.go
  datadog/resource_datadog_integration_aws_test.go
Labels: size/S

#128 Make screenboard's width and height accept strings and numbers
  datadog/resource_datadog_screenboard.go
  datadog/resource_datadog_screenboard_test.go
Labels: size/XL

#130 Prepare 1.6.0
  CHANGELOG.md
Labels: size/XS
