Repository DataDog/terraform-provider-datadog, pull requests merged in 2018-09, with the labels that each got.

#91 Add datadog_screenboard resource
  datadog/provider.go
  datadog/resource_datadog_screenboard.go
  datadog/resource_datadog_screenboard_test.go
  vendor/github.com/zorkian/go-datadog-api/dashboards.go
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/monitors.go
  vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
  vendor/github.com/zorkian/go-datadog-api/screenboards.go
  vendor/vendor.json
  website/datadog.erb
  website/docs/r/screenboard.html.markdown
Labels: size/XXL

#88 new_host_delay should not be computed
  datadog/resource_datadog_monitor.go
Labels: size/XS

#93 Fix issues with the uptime widget
  datadog/resource_datadog_screenboard.go
  datadog/resource_datadog_screenboard_test.go
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
  vendor/vendor.json
  website/docs/r/screenboard.html.markdown
Labels: size/L

#96 Mention is_admin is deprecated in the docs
  website/docs/r/user.html.markdown
Labels: size/XS

#97 Prepare 1.3.0
  CHANGELOG.md
Labels: size/XS
