Repository DataDog/terraform-provider-datadog, pull requests merged in 2019-05, with the labels that each got.

#187 Fix various acceptance tests failures
  datadog/import_datadog_downtime_test.go
  datadog/resource_datadog_downtime_test.go
  datadog/resource_datadog_monitor.go
  datadog/resource_datadog_monitor_test.go
  datadog/resource_datadog_user.go
  datadog/resource_datadog_user_test.go
  go.mod
  go.sum
  vendor/github.com/zorkian/go-datadog-api/Makefile
  vendor/github.com/zorkian/go-datadog-api/monitors.go
  vendor/modules.txt
Labels: dependencies, size/M

#131 Adds ThresholdWindows
  datadog/resource_datadog_monitor.go
Labels: size/S

#191 Add tests for datadog_monitor resource threshold_windows attribute
  datadog/resource_datadog_monitor_test.go
Labels: size/M

#193 Add documentation for datadog_monitor's threshold_windows
  website/docs/r/monitor.html.markdown
Labels: documentation, size/XS

#202 Fix and provide better docs for (un)muting monitors. Fixes #181
  datadog/resource_datadog_monitor.go
  datadog/resource_datadog_monitor_test.go
  go.mod
  go.sum
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/monitors.go
  vendor/modules.txt
  website/docs/r/downtime.html.markdown
  website/docs/r/monitor.html.markdown
Labels: dependencies, documentation, size/L

#154 Change monitor element schema to TypeString
  datadog/resource_datadog_screenboard.go
Labels: size/XS

#199 #148 Fix log monitor UI issue: generate queryConfig.queryString from query
  datadog/resource_datadog_monitor.go
Labels: size/S

#207 Clarify the format of api_url provider argument
  website/docs/index.html.markdown
Labels: documentation, size/XS

#209 Make sure the computed value for monitor's query_config gets stored on creation
  datadog/resource_datadog_monitor.go
Labels: size/XS

#210 Fix monitor acceptance tests after API change that makes '*_recovery' thresho…
  datadog/resource_datadog_monitor_test.go
Labels: size/XS

#201 docs(monitor): finish sentence for include_tags
  website/docs/r/monitor.html.markdown
Labels: documentation, size/XS

#189 Add custum_bg_color to screenboard
  datadog/resource_datadog_screenboard.go
  datadog/resource_datadog_screenboard_test.go
  go.mod
  go.sum
  vendor/github.com/zorkian/go-datadog-api/dashboards.go
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/downtimes.go
  vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
  vendor/modules.txt
Labels: dependencies, size/XS

#213 Add link to documentation about monitor types
  website/docs/r/monitor.html.markdown
Labels: documentation, size/XS

#214 Fixes #182 - Monitor Tags are not sorted
  datadog/resource_datadog_monitor.go
  datadog/resource_datadog_monitor_test.go
Labels: size/XS

#212 Add default of 10m for monitor no data timeframe
  datadog/resource_datadog_monitor.go
  website/docs/r/monitor.html.markdown
Labels: documentation, size/XS

#215 Allow adding metadata aliases for widgets in screenboards and timeboards
  datadog/resource_datadog_screenboard.go
  datadog/resource_datadog_screenboard_test.go
  datadog/resource_datadog_timeboard.go
  datadog/resource_datadog_timeboard_test.go
  website/docs/r/screenboard.html.markdown
  website/docs/r/timeboard.html.markdown
Labels: documentation, size/M
