Repository DataDog/terraform-provider-datadog, pull requests merged in 2019-06, with the labels that each got.

#204 Downtime improvements
  datadog/resource_datadog_downtime.go
  website/docs/r/downtime.html.markdown
Labels: documentation, size/M

#220 Add examples section to docs
  website/datadog.erb
  website/docs/r/examples/monitors.html.markdown
Labels: documentation, size/S

#226 Revert "#148 Fix log monitor UI issue: generate queryConfig.queryStri…
  datadog/resource_datadog_monitor.go
Labels: size/S

#222 Support Synthetics tests in composite monitors
  datadog/resource_datadog_monitor_test.go
  datadog/resource_datadog_synthetics_test_.go
  datadog/resource_datadog_synthetics_test_test.go
  go.mod
  go.sum
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/synthetics.go
  vendor/modules.txt
  website/docs/r/monitor.html.markdown
Labels: dependencies, documentation, size/M

#227 go mod tidy
  go.sum
Labels: dependencies, size/XS

#228 Suppress diff on default precision
  datadog/resource_datadog_timeboard.go
Labels: size/XS

#230 Update to go-datadog-api v2.21.0, run "go mod tidy"
  go.mod
  go.sum
  vendor/github.com/zorkian/go-datadog-api/downtimes.go
  vendor/modules.txt
Labels: dependencies, size/XS

#232 Add example on constructing dynamic timeboards. Fixes #47, #64.
  website/docs/r/timeboard.html.markdown
Labels: documentation, size/S

#231 Timeboard extra_col fix
  datadog/resource_datadog_timeboard.go
  website/docs/r/timeboard.html.markdown
Labels: documentation, size/S

#221 Deprecate Silence attribute and Fix multiple terraform runs
  datadog/resource_datadog_monitor.go
  datadog/resource_datadog_monitor_test.go
  website/docs/r/monitor.html.markdown
Labels: documentation, enhancement, size/L

#234 Fix several integration tests and related code
  datadog/import_datadog_downtime_test.go
  datadog/resource_datadog_downtime.go
  datadog/resource_datadog_monitor.go
  datadog/resource_datadog_monitor_test.go
Labels: size/M

#233 Mention units explicitly
  website/docs/r/synthetics.html.markdown
Labels: documentation, size/XS

#236 Mark datadog_monitor.type as ForceNew, since changing type is not actually possible
  datadog/resource_datadog_monitor.go
Labels: size/XS

#239 Add an examply of an anomaly monitor
  website/docs/r/examples/monitors.html.markdown
Labels: documentation, size/XS

#238 Fix up the GCP and User tests
  datadog/resource_datadog_integration_gcp_test.go
  datadog/resource_datadog_user_test.go
Labels: size/XS

#240 Update changelog
  CHANGELOG.md
Labels: size/XS

#242 `datadog_monitor` ignore `query alert` vs `metric alert` diff
  datadog/resource_datadog_monitor.go
Labels: size/XS

#244 Clarify the logic around monitors changing types by adding parentheses
  datadog/resource_datadog_monitor.go
Labels: size/XS

#243 Update changelog
  CHANGELOG.md
Labels: size/XS

#247 Use suppressdiff on monitor type
  datadog/resource_datadog_monitor.go
Labels: size/XS

#248 Prep 2.0.2 release
  CHANGELOG.md
Labels: size/XS

#251 Make is_admin computed
  datadog/resource_datadog_user.go
Labels: size/XS

#237 Make it possible to configure individual PD service objects independently
  datadog/provider.go
  datadog/resource_datadog_integration_pagerduty.go
  datadog/resource_datadog_integration_pagerduty_service_object.go
  datadog/resource_datadog_integration_pagerduty_service_object_test.go
  datadog/resource_datadog_integration_pagerduty_test.go
  go.mod
  go.sum
  vendor/github.com/cenkalti/backoff/.travis.yml
  vendor/github.com/cenkalti/backoff/README.md
  vendor/github.com/cenkalti/backoff/backoff.go
  vendor/github.com/cenkalti/backoff/context.go
  vendor/github.com/cenkalti/backoff/exponential.go
  vendor/github.com/cenkalti/backoff/retry.go
  vendor/github.com/cenkalti/backoff/ticker.go
  vendor/github.com/cenkalti/backoff/tries.go
  vendor/github.com/zorkian/go-datadog-api/integrations.go
  vendor/modules.txt
  website/datadog.erb
  website/docs/r/integration_pagerduty.html.markdown
  website/docs/r/integration_pagerduty_service_object.html.markdown
Labels: dependencies, documentation, size/XL

#252 Clarify threshold windows are required for anomaly monitors
  website/docs/r/monitor.html.markdown
Labels: documentation, size/XS

#254 Add a mutex to all AWS integration operations that change data to prevent race conditions
  datadog/resource_datadog_integration_aws.go
Labels: size/XS

#253 Update error wording for credential validation
  datadog/provider.go
Labels: size/XS
