Repository DataDog/terraform-provider-datadog, pull requests merged in 2019-07, with the labels that each got.

#257 Small corrections on example Datadog monitors docs
  website/docs/r/examples/monitors.html.markdown
Labels: documentation, size/XS

#260 Correction to the threshold_windows
  datadog/resource_datadog_monitor.go
  datadog/resource_datadog_monitor_test.go
Labels: size/S

#264 Downtime fixes
  datadog/resource_datadog_downtime.go
  datadog/resource_datadog_downtime_test.go
  website/docs/r/downtime.html.markdown
Labels: documentation, size/S

#266 Fix integration tests
  datadog/import_datadog_downtime_test.go
  datadog/resource_datadog_monitor_test.go
Labels: size/XS

#249 [dashboards] Add new Dashboard resource
  datadog/provider.go
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_test.go
  website/datadog.erb
  website/docs/r/dashboard.html.markdown
  website/docs/r/screenboard.html.markdown
  website/docs/r/timeboard.html.markdown
Labels: documentation, size/XXL

#267 Make sure downtime resource properly fixes state drifts in start/end attributes
  datadog/resource_datadog_downtime.go
Labels: size/M

#268 Prep 2.1.0 Release
  CHANGELOG.md
Labels: size/XS

#273 Add example Process Monitor
  website/docs/r/examples/monitors.html.markdown
Labels: documentation, size/XS
