Repository DataDog/terraform-provider-datadog, pull requests merged in 2019-08, with the labels that each got.

#274 Update dashboard.html.markdown
  website/docs/r/dashboard.html.markdown
Labels: documentation, size/XS

#277 Add support for style block in dashboard widgets
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_test.go
  website/docs/r/dashboard.html.markdown
Labels: documentation, size/L

#278 Add support for metadata block in dashboard widgets
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_test.go
  website/docs/r/dashboard.html.markdown
Labels: documentation, size/M

#256 [Synthetics] Fix follow redirects
  datadog/resource_datadog_synthetics_test_.go
  datadog/resource_datadog_synthetics_test_test.go
Labels: size/S

#281 Update go client
  go.mod
  go.sum
  vendor/github.com/zorkian/go-datadog-api/app_keys.go
  vendor/github.com/zorkian/go-datadog-api/boards.go
  vendor/github.com/zorkian/go-datadog-api/dashboards.go
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/helpers.go
  vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
  vendor/github.com/zorkian/go-datadog-api/service_level_objectives.go
  vendor/github.com/zorkian/go-datadog-api/synthetics.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#285 Correct typo on dashboard options
  website/docs/r/dashboard.html.markdown
  website/docs/r/screenboard.html.markdown
Labels: documentation, size/XS

#279 [Synthetics] Support SSL
  datadog/resource_datadog_synthetics_test_.go
  datadog/resource_datadog_synthetics_test_test.go
  website/docs/r/synthetics.html.markdown
Labels: dependencies, documentation, size/XL

#283 [dashboards] Safely type assert optional fields from log and apm query
  datadog/resource_datadog_dashboard.go
  website/docs/r/dashboard.html.markdown
Labels: documentation, size/XS

#288 [dashboards] Add safe type asserts to required fields
  datadog/resource_datadog_dashboard.go
Labels: size/XS

#263 Adds Service Level Objective (SLO) support
  datadog/provider.go
  datadog/resource_datadog_service_level_objective.go
  datadog/resource_datadog_service_level_objective_test.go
  website/datadog.erb
  website/docs/r/service_level_objective.html.markdown
Labels: dependencies, documentation, size/XL

#289 Update changelog for 2.2.0 release
  CHANGELOG.md
Labels: size/XS

#290 Add bullet formatting to changelog
  CHANGELOG.md
Labels: size/XS

#295 Add make command to update go api client dep
  GNUmakefile
Labels: size/XS

#297 Update go api client dep to latest master
  go.mod
  go.sum
  vendor/github.com/zorkian/go-datadog-api/board_widgets.go
  vendor/github.com/zorkian/go-datadog-api/client.go
  vendor/github.com/zorkian/go-datadog-api/dashboard_list_items_v2.go
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
  vendor/modules.txt
Labels: dependencies, size/XL

#272 [dashboards] Add resources for log, apm and process query in legacy dashboards
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_screenboard.go
  datadog/resource_datadog_screenboard_test.go
  datadog/resource_datadog_timeboard.go
  datadog/resource_datadog_timeboard_test.go
  website/docs/r/dashboard.html.markdown
  website/docs/r/screenboard.html.markdown
  website/docs/r/timeboard.html.markdown
Labels: dependencies, documentation, size/XXL

#304 Make sure PD services don't get removed by updating PD resource
  datadog/resource_datadog_integration_pagerduty.go
  datadog/resource_datadog_integration_pagerduty_service_object_test.go
  datadog/resource_datadog_integration_pagerduty_test.go
  website/docs/r/integration_pagerduty.html.markdown
Labels: documentation, size/M

#307 Update the zorkian client dep to v2.23.0
  go.mod
  go.sum
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/users.go
  vendor/modules.txt
Labels: dependencies, size/L

#308 Prep 2.3.0 release
  CHANGELOG.md
Labels: size/XS
