Repository DataDog/terraform-provider-datadog, pull requests merged in 2019-04, with the labels that each got.

#155 Add access_role to resource_datadog_user
  datadog/resource_datadog_user.go
  datadog/resource_datadog_user_test.go
Labels: size/XS

#169 Support Synthetics Tests
  datadog/provider.go
  datadog/resource_datadog_synthetics_test_.go
  datadog/resource_datadog_synthetics_test_test.go
  go.mod
  go.sum
  vendor/github.com/zorkian/go-datadog-api/README.md
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/events.go
  vendor/github.com/zorkian/go-datadog-api/helpers.go
  vendor/github.com/zorkian/go-datadog-api/monitors.go
  vendor/github.com/zorkian/go-datadog-api/synthetics.go
  vendor/modules.txt
  website/docs/r/synthetics.html.markdown
Labels: dependencies, documentation, size/XXL

#172 Update changelog with support of Synthetics resources
  CHANGELOG.md
Labels: size/XS

#174 Re-order doc links, and add synthetics link
  website/datadog.erb
Labels: documentation, size/XS

#175 Update the stable-website with whats on master
  CHANGELOG.md
  website/datadog.erb
Labels: documentation, size/XS

#176 Add request body to synthetics documentation
  website/docs/r/synthetics.html.markdown
Labels: documentation, size/XS

#171 Document HCL limitation of key interpolation. Fixes #159
  website/docs/r/monitor.html.markdown
Labels: documentation, size/XS

#178 Document access_role in favour of is_admin.
  website/docs/r/user.html.markdown
Labels: documentation, size/XS

#151 Add support for enable_logs_sample option in log monitors
  datadog/resource_datadog_monitor.go
  datadog/resource_datadog_monitor_test.go
  website/docs/r/monitor.html.markdown
Labels: documentation, size/M

#180 Improve documentation
  website/docs/r/synthetics.html.markdown
Labels: documentation, size/XS

#183 Fix typos
  website/docs/r/integration_aws.html.markdown
Labels: documentation, size/XS

#184 [dashboards] Support importing dashboards using the new string id + update to the latest go-datadog-api
  datadog/resource_datadog_screenboard.go
  datadog/resource_datadog_timeboard.go
  go.mod
  go.sum
  vendor/github.com/hashicorp/terraform/helper/schema/schema.go
  vendor/github.com/hashicorp/terraform/plugin/ui_input.go
  vendor/github.com/hashicorp/terraform/terraform/context.go
  vendor/github.com/hashicorp/terraform/terraform/ui_input.go
  vendor/github.com/hashicorp/terraform/terraform/ui_input_mock.go
  vendor/github.com/hashicorp/terraform/terraform/ui_input_prefix.go
  vendor/github.com/hashicorp/terraform/version/version.go
  vendor/github.com/zorkian/go-datadog-api/api_keys.go
  vendor/github.com/zorkian/go-datadog-api/board_widgets.go
  vendor/github.com/zorkian/go-datadog-api/boards.go
  vendor/github.com/zorkian/go-datadog-api/dashboards.go
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/downtimes.go
  vendor/github.com/zorkian/go-datadog-api/helpers.go
  vendor/github.com/zorkian/go-datadog-api/monitors.go
  vendor/github.com/zorkian/go-datadog-api/screenboards.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#152 Make the `metric_metadata` docs example adhere to `terraform fmt`
  website/docs/r/metric_metadata.html.markdown
Labels: documentation, size/XS

#167 Add monitor_tags getting and setting to downtime resource
  datadog/resource_datadog_downtime.go
  datadog/resource_datadog_downtime_test.go
  go.mod
  go.sum
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
Labels: dependencies, size/M

#186 Changelog and tidy
  CHANGELOG.md
  go.sum
Labels: documentation, size/XS
