Repository DataDog/terraform-provider-datadog, pull requests merged in 2019-10, with the labels that each got.

#333 add 'count' as valid aggregation method
  datadog/resource_datadog_screenboard.go
  datadog/resource_datadog_timeboard.go
  datadog/validators.go
Labels: size/S

#338 Document the monitor ID associated with the synthetics test
  website/docs/r/synthetics.html.markdown
Labels: documentation, size/XS

#332 Update logs pipeline to separate integration and customer pipelines
  datadog/import_datadog_logs_index_test.go
  datadog/import_datadog_logs_pipeline_test.go
  datadog/provider.go
  datadog/resource_datadog_logs_custom_pipeline.go
  datadog/resource_datadog_logs_custom_pipeline_test.go
  datadog/resource_datadog_logs_index_order_test.go
  datadog/resource_datadog_logs_index_test.go
  datadog/resource_datadog_logs_integration_pipeline.go
  datadog/resource_datadog_logs_pipeline_order.go
  datadog/resource_datadog_logs_pipeline_order_test.go
  website/datadog.erb
  website/docs/r/logs_custom_pipeline.html.markdown
  website/docs/r/logs_integration_pipeline.html.markdown
  website/docs/r/logs_pipeline_order.html.markdown
Labels: documentation, size/XL

#343 Prepare changelog for 2.5.0 release
  CHANGELOG.md
Labels: size/XS

#341 add example to the Downtime resource documentation
  website/docs/r/downtime.html.markdown
Labels: documentation, size/XS

#351 Add note about monitor summary widget
  website/docs/r/dashboard.html.markdown
Labels: documentation, size/XS

#354 Fix vertical/horizontal axis in dashboard/ & creenboard docs
  website/docs/r/dashboard.html.markdown
  website/docs/r/screenboard.html.markdown
Labels: documentation, size/XS
