Repository DataDog/terraform-provider-datadog, pull requests merged in 2019-09, with the labels that each got.

#282 Add full support for timeseries definitions
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_test.go
Labels: size/M

#296 Add dashboard list resource
  datadog/provider.go
  datadog/resource_datadog_dashboard_list.go
  datadog/resource_datadog_dashboard_list_test.go
  website/datadog.erb
  website/docs/r/dashboard_list.markdown
Labels: documentation, size/XL

#311 Fix integration tests (again)
  datadog/resource_datadog_dashboard_test.go
  datadog/resource_datadog_screenboard_test.go
  datadog/resource_datadog_service_level_objective_test.go
  datadog/resource_datadog_timeboard_test.go
Labels: size/XS

#313 Prepare changelog for 2.4.0 release
  CHANGELOG.md
Labels: size/XS

#317 Update API client to version 2.24.0
  go.mod
  go.sum
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/helpers.go
  vendor/github.com/zorkian/go-datadog-api/hosts.go
  vendor/github.com/zorkian/go-datadog-api/ip_ranges.go
  vendor/github.com/zorkian/go-datadog-api/logs_index_lists.go
  vendor/github.com/zorkian/go-datadog-api/logs_indexes.go
  vendor/github.com/zorkian/go-datadog-api/logs_pipeline_lists.go
  vendor/github.com/zorkian/go-datadog-api/logs_pipelines.go
  vendor/github.com/zorkian/go-datadog-api/logs_processors.go
  vendor/github.com/zorkian/go-datadog-api/monitors.go
  vendor/github.com/zorkian/go-datadog-api/request.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#322 Fix parsing compute.interval for apm and log queries in dashboards
  datadog/resource_datadog_dashboard.go
Labels: size/XS

#312 [Datadog] Add support for Logs Public config API
  datadog/import_datadog_logs_pipeline_test.go
  datadog/provider.go
  datadog/resource_datadog_logs_pipeline.go
  datadog/resource_datadog_logs_pipeline_order.go
  datadog/resource_datadog_logs_pipeline_order_test.go
  datadog/resource_datadog_logs_pipeline_test.go
  website/datadog.erb
  website/docs/r/logs_pipeline.html.markdown
  website/docs/r/logs_pipeline_order.html.markdown
Labels: documentation, size/XXL

#325 Fix parsing group_by.sort.facet for apm and log queries in dashboards
  datadog/resource_datadog_dashboard.go
Labels: size/XS

#324 Add missing 'exists' methods to PD integration and PD service objects
  datadog/resource_datadog_integration_pagerduty.go
  datadog/resource_datadog_integration_pagerduty_service_object.go
Labels: size/S

#326 Support Logs Index API
  datadog/import_datadog_logs_index_test.go
  datadog/provider.go
  datadog/resource_datadog_logs_index.go
  datadog/resource_datadog_logs_index_order.go
  datadog/resource_datadog_logs_index_order_test.go
  datadog/resource_datadog_logs_index_test.go
  website/datadog.erb
  website/docs/r/logs_index.html.markdown
  website/docs/r/logs_index_order.html.markdown
  website/docs/r/logs_pipeline_order.html.markdown
Labels: documentation, size/XL

#329 Properly add show_legend
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_test.go
  website/docs/r/dashboard.html.markdown
Labels: documentation, size/XS

#320 Add spacing
  website/docs/r/service_level_objective.html.markdown
Labels: documentation, size/XS

#330 Fix synth resource docs to reference `id` as exported attribute
  website/docs/r/synthetics.html.markdown
Labels: documentation, size/XS

#298 Add data source - IP ranges
  datadog/data_source_datadog_ip_ranges.go
  datadog/data_source_datadog_ip_ranges_test.go
  datadog/provider.go
  website/datadog.erb
  website/docs/d/ip_ranges.html.markdown
Labels: documentation, size/L

#331 Update requirements for exclusive filter
  datadog/resource_datadog_logs_index.go
  website/docs/r/logs_index.html.markdown
Labels: documentation, size/XS
