Repository DataDog/terraform-provider-datadog, pull requests merged in 2019-11, with the labels that each got.

#361 Update to go-datadog-api v2.25.0
  go.mod
  go.sum
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/github.com/zorkian/go-datadog-api/board_widgets.go
  vendor/github.com/zorkian/go-datadog-api/client.go
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/integrations.go
  vendor/github.com/zorkian/go-datadog-api/logs_processors.go
  vendor/github.com/zorkian/go-datadog-api/monitors.go
  vendor/github.com/zorkian/go-datadog-api/request.go
  vendor/github.com/zorkian/go-datadog-api/service_level_objectives.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#357 Support all processors in Logs pipeline
  datadog/resource_datadog_logs_custom_pipeline.go
  datadog/resource_datadog_logs_custom_pipeline_test.go
  website/docs/r/logs_custom_pipeline.html.markdown
Labels: documentation, size/L

#359 Add note about contributing from forks
  README.md
Labels: size/XS

#355 Add Datadog dashboard SLO widget support
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_test.go
  website/docs/r/dashboard.html.markdown
Labels: dependencies, documentation, size/L
