Repository DataDog/terraform-provider-datadog, pull requests merged in 2019-01, with the labels that each got.

#141 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
  datadog/import_datadog_downtime_test.go
  datadog/import_datadog_monitor_test.go
  datadog/import_datadog_user_test.go
  datadog/provider.go
  datadog/resource_datadog_downtime_test.go
  datadog/resource_datadog_integration_gcp_test.go
  datadog/resource_datadog_screenboard.go
  datadog/resource_datadog_timeboard.go
  datadog/resource_datadog_user_test.go
Labels: size/XL

#143 Bump go client to include type fix in widget struct
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
  vendor/vendor.json
Labels: dependencies, size/XS

#144 Fix fill_min and fill_max panic issue
  datadog/resource_datadog_screenboard.go
Labels: size/XS

#145 Fix order for reading start times on downtime
  datadog/resource_datadog_downtime.go
Labels: size/XS
