Repository DataDog/terraform-provider-datadog, pull requests merged in 2020-05, with the labels that each got.

#503 Make sure the aws host_tags and filters_tags are never nil
  datadog/resource_datadog_integration_aws.go
Labels: size/XS

#505 Do not set empty structures in request to create aws integration
  datadog/resource_datadog_integration_aws.go
Labels: size/XS

#501 Update aws_log_collection resource to use Datadog Go client
  datadog/cassettes/TestAccDatadogIntegrationAWSLogCollection.yaml
  datadog/resource_datadog_integration_aws.go
  datadog/resource_datadog_integration_aws_log_collection.go
  datadog/resource_datadog_integration_aws_log_collection_test.go
  datadog/resource_datadog_logs_index.go
  datadog/resource_datadog_monitor.go
  datadog/resource_datadog_service_level_objective.go
Labels: size/XL

#506 updating go-datadog-api v2.29.0, fix int issue dash id
  go.mod
  go.sum
Labels: size/XS

#508 Update make task to include new client + update README
  GNUmakefile
  README.md
Labels: size/XS

#499 Update synthetics resource to utilize Datadog Go Client
  datadog/cassettes/TestAccDatadogSyntheticsAPITest_Basic.yaml
  datadog/cassettes/TestAccDatadogSyntheticsAPITest_Updated.yaml
  datadog/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.yaml
  datadog/cassettes/TestAccDatadogSyntheticsBrowserTest_Basic.yaml
  datadog/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.yaml
  datadog/cassettes/TestAccDatadogSyntheticsBrowserTest_importBasic.yaml
  datadog/cassettes/TestAccDatadogSyntheticsSSLTest_Basic.yaml
  datadog/cassettes/TestAccDatadogSyntheticsSSLTest_Updated.yaml
  datadog/cassettes/TestAccDatadogSyntheticsSSLTest_importBasic.yaml
  datadog/resource_datadog_synthetics_test_.go
  datadog/resource_datadog_synthetics_test_test.go
  website/docs/r/synthetics.html.markdown
Labels: documentation, size/XXL

#497 Migrate AWS logs to use the official Go Client
  datadog/cassettes/TestAccDatadogIntegrationAWS.yaml
  datadog/cassettes/TestAccDatadogIntegrationAWSLambdaArn.yaml
  datadog/cassettes/TestAccDatadogIntegrationAWSLogCollection.yaml
  datadog/resource_datadog_integration_aws_lambda_arn.go
  datadog/resource_datadog_integration_aws_lambda_arn_test.go
  datadog/resource_datadog_integration_aws_log_collection.go
  datadog/resource_datadog_integration_aws_test.go
Labels: size/XL

#510 New UserAgent Header
  datadog/provider.go
Labels: dependencies, size/XS

#511 Update User Agent
  datadog/provider.go
Labels: size/XS

#514 Add default to deprecated `count` field to avoid sending 0
  datadog/resource_datadog_dashboard.go
Labels: size/XS

#515 Try converting similar structs
  datadog/resource_datadog_monitor.go
Labels: size/M

#489 Update dashboard resource to use Datadog Go client
  datadog/cassettes/TestAccDatadogDashboard_import.yaml
  datadog/cassettes/TestAccDatadogDashboard_update.yaml
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_test.go
Labels: size/XXL
