Repository DataDog/terraform-provider-datadog, pull requests merged in 2020-01, with the labels that each got.

#384 Ignore the change of no_data_timeframe if notify_no_data is false
  datadog/resource_datadog_monitor.go
Labels: size/XS

#386 Monitor type note
  website/docs/r/monitor.html.markdown
Labels: documentation, size/XS

#394 Update to go-datadog-api v2.26.0
  go.mod
  go.sum
  vendor/github.com/zorkian/go-datadog-api/board_widgets.go
  vendor/github.com/zorkian/go-datadog-api/client.go
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/integrations.go
  vendor/github.com/zorkian/go-datadog-api/log_lists.go
  vendor/github.com/zorkian/go-datadog-api/logs_processors.go
  vendor/github.com/zorkian/go-datadog-api/ratelimit.go
  vendor/github.com/zorkian/go-datadog-api/request.go
  vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
  vendor/github.com/zorkian/go-datadog-api/series.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#395 Prepare 2.6 release
  CHANGELOG.md
Labels: size/XS

#397 Removing failing integration tests due to env config complexities
  datadog/resource_datadog_logs_pipeline_order_test.go
Labels: size/S

#399 Set User-Agent header for terraform users with build information
  datadog/provider.go
  version/version.go
Labels: size/XS

#396 Add new monitor summary widget parameters
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_test.go
  datadog/resource_datadog_screenboard.go
  datadog/resource_datadog_screenboard_test.go
  website/docs/r/dashboard.html.markdown
  website/docs/r/screenboard.html.markdown
Labels: documentation, size/M
