Repository DataDog/terraform-provider-datadog, pull requests merged in 2020-07, with the labels that each got.

#563 Fix dashboard typo
  website/docs/r/dashboard_list.markdown
Labels: documentation, size/XS

#569 Add datasource for monitors
  datadog/cassettes/TestAccDatadogMonitorDatasource.yaml
  datadog/data_source_datadog_monitor.go
  datadog/data_source_datadog_monitor_test.go
  datadog/provider.go
Labels: size/XXL

#570 Add whitespace to allow list to render correctly
  website/docs/index.html.markdown
Labels: documentation, size/XS

#578 Add initial goreleaser configuration
  .gitignore
  .goreleaser.yml
Labels: size/S

#580 Respect TF_LOG for debug output
  datadog/provider.go
Labels: size/XS

#581 Synchronize state and diff function for trimmed fields
  datadog/resource_datadog_service_level_objective.go
Labels: size/S

#571 Update go client, use new synthetics target
  datadog/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertions.yaml
  datadog/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertions.yaml
  datadog/cassettes/TestAccDatadogSyntheticsAPITest_importBasicNewAssertions.yaml
  datadog/resource_datadog_synthetics_test_.go
  datadog/resource_datadog_synthetics_test_test.go
  go.mod
  go.sum
  vendor/github.com/DataDog/datadog-api-client-go/.apigentools-info
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/README.md
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_dashboards.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_usage_metering.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_downtime_recurrence.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_synthetics_assertion.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_synthetics_assertion_json_path_operator.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_synthetics_assertion_json_path_target.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_synthetics_assertion_json_path_target_target.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_synthetics_assertion_operator.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_synthetics_assertion_target.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_usage_billable_summary_body.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_usage_billable_summary_hour.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_usage_billable_summary_keys.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_usage_billable_summary_response.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/README.md
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/api_logs.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/client.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/configuration.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_log.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_log_attributes.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_log_type.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_logs_list_request.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_logs_list_request_filter.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_logs_list_request_page.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_logs_list_response.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_logs_list_response_links.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_logs_list_response_meta.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_logs_list_response_meta_page.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_logs_sort.go
  vendor/github.com/DataDog/datadog-api-client-go/version.go
  vendor/modules.txt
Labels: dependencies, resource/synthetics, size/XXL

#582 Add doc about new assertion format
  website/docs/r/synthetics.html.markdown
Labels: documentation, size/S

#583 Mention imports in logs archive docs
  website/docs/r/logs_archive.html.markdown
Labels: documentation, size/XS

#584 Deprecate pagerduty integration
  datadog/resource_datadog_integration_pagerduty.go
  website/docs/r/integration_pagerduty.html.markdown
  website/docs/r/integration_pagerduty_service_object.html.markdown
Labels: breaking-change, documentation, size/S

#585 Add doc for monitor datasource
  datadog/data_source_datadog_monitor.go
  website/datadog.erb
  website/docs/d/monitor.html.markdown
Labels: documentation, size/M

#586 Add support for basicAuth and query in Synthetics resource
  datadog/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertions.yaml
  datadog/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertions.yaml
  datadog/cassettes/TestAccDatadogSyntheticsAPITest_importBasicNewAssertions.yaml
  datadog/resource_datadog_synthetics_test_.go
  datadog/resource_datadog_synthetics_test_test.go
  website/docs/r/synthetics.html.markdown
Labels: documentation, size/XL

#587 Fix pagerduty integration tests
  datadog/cassettes/TestAccDatadogIntegrationPagerdutyServiceObject_Basic.yaml
  datadog/cassettes/TestAccDatadogIntegrationPagerduty_Basic.yaml
  datadog/cassettes/TestAccDatadogIntegrationPagerduty_Migrate2ServiceObjects.yaml
  datadog/cassettes/TestAccDatadogIntegrationPagerduty_TwoServices.yaml
  datadog/resource_datadog_integration_pagerduty_test.go
Labels: size/XXL

#589 Properly setup version.ProviderVersion when using goreleaser
  .goreleaser.yml
Labels: size/XS

#588 Update go client to beta7
  go.mod
  go.sum
  vendor/github.com/DataDog/datadog-api-client-go/.apigentools-info
  vendor/github.com/DataDog/datadog-api-client-go/CHANGELOG.md
  vendor/github.com/DataDog/datadog-api-client-go/LICENSE-3rdparty.csv
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/README.md
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_hosts.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_usage_metering.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/configuration.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_event.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_event_query_definition.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_log_query_definition.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_synthetics_test_details.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_synthetics_test_details_sub_type.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_synthetics_test_options.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_synthetics_test_options_retry.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_synthetics_tick_interval.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_usage_custom_reports_attributes.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_usage_custom_reports_data.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_usage_custom_reports_meta.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_usage_custom_reports_page.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_usage_custom_reports_response.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_usage_reports_type.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_usage_sort.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_usage_sort_direction.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_usage_specified_custom_reports_attributes.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_usage_specified_custom_reports_data.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_usage_specified_custom_reports_meta.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_usage_specified_custom_reports_page.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_usage_specified_custom_reports_response.go
  vendor/github.com/DataDog/datadog-api-client-go/go.mod
  vendor/github.com/DataDog/datadog-api-client-go/go.sum
  vendor/github.com/DataDog/datadog-api-client-go/version.go
  vendor/github.com/kr/text/go.mod
  vendor/modules.txt
Labels: dependencies, size/XXL

#590 Prepare changelog for 2.12.0 release
  CHANGELOG.md
Labels: size/XS

#597 Ignore diff to start on downtime resource
  datadog/cassettes/TestAccDatadogDowntime_DiffStart.yaml
  datadog/resource_datadog_downtime.go
  datadog/resource_datadog_downtime_test.go
Labels: bug, resource/monitor

#416 New data sources for widgets
  GNUmakefile
  datadog/cassettes/TestAccDatadogDashboard_import.yaml
  datadog/cassettes/TestAccDatadogDashboard_update.yaml
  datadog/cassettes/TestAccDatadogTimeboard_update.yaml
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_test.go
  go.mod
  go.sum
  vendor/github.com/DataDog/datadog-api-client-go/.apigentools-info
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_change_widget_request.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_distribution_widget_request.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_heat_map_widget_request.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_host_map_request.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_monitor_type.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_query_value_widget_request.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_scatter_plot_request.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_table_widget_request.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_timeseries_widget_request.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_toplist_widget_request.go
  vendor/github.com/DataDog/datadog-api-client-go/run-go-tests.sh
  vendor/github.com/DataDog/datadog-api-client-go/run-tests.sh
  vendor/github.com/DataDog/datadog-api-client-go/version.go
  vendor/modules.txt
Labels: size/L

#601 Reorganize docs to the new Terraform Registry format
  .github/workflows/test.yml
  GNUmakefile
  docs/data-sources/ip_ranges.md
  docs/data-sources/monitor.md
  docs/guides/monitors.md
  docs/index.md
  docs/resources/dashboard.md
  docs/resources/dashboard_list.md
  docs/resources/downtime.html.markdown
  docs/resources/integration_aws.md
  docs/resources/integration_aws_lambda_arn.md
  docs/resources/integration_aws_log_collection.md
  docs/resources/integration_azure.md
  docs/resources/integration_gcp.md
  docs/resources/integration_pagerduty.md
  docs/resources/integration_pagerduty_service_object.md
  docs/resources/logs_archive.md
  docs/resources/logs_custom_pipeline.md
  docs/resources/logs_index.md
  docs/resources/logs_index_order.md
  docs/resources/logs_integration_pipeline.md
  docs/resources/logs_pipeline_order.md
  docs/resources/metric_metadata.md
  docs/resources/monitor.md
  docs/resources/screenboard.md
  docs/resources/service_level_objective.md
  docs/resources/synthetics.md
  docs/resources/timeboard.md
  docs/resources/user.md
  website/datadog.erb
Labels: documentation

#602 Upgrade docs according to the latest recommendations
  docs/data-sources/ip_ranges.md
  docs/data-sources/monitor.md
  docs/guides/monitors.md
  docs/index.md
  docs/resources/dashboard.md
  docs/resources/dashboard_list.md
  docs/resources/downtime.md
  docs/resources/integration_aws.md
  docs/resources/integration_aws_lambda_arn.md
  docs/resources/integration_aws_log_collection.md
  docs/resources/integration_azure.md
  docs/resources/integration_gcp.md
  docs/resources/integration_pagerduty.md
  docs/resources/integration_pagerduty_service_object.md
  docs/resources/logs_archive.md
  docs/resources/logs_custom_pipeline.md
  docs/resources/logs_index.md
  docs/resources/logs_index_order.md
  docs/resources/logs_integration_pipeline.md
  docs/resources/logs_pipeline_order.md
  docs/resources/metric_metadata.md
  docs/resources/monitor.md
  docs/resources/screenboard.md
  docs/resources/service_level_objective.md
  docs/resources/synthetics.md
  docs/resources/timeboard.md
  docs/resources/user.md
Labels: documentation

#309 Add synthetics locations data source
  datadog/cassettes/TestAccDatatogSyntheticsLocation_existing.yaml
  datadog/data_source_datadog_synthetics_locations.go
  datadog/data_source_datadog_synthetics_locations_test.go
  datadog/provider.go
  docs/data-sources/synthetics_locations.md
Labels: documentation, size/M
