Repository DataDog/terraform-provider-datadog, pull requests merged in 2020-06, with the labels that each got.

#522 Update api docs links and add lambda arn to docs
  website/datadog.erb
  website/docs/r/dashboard.html.markdown
  website/docs/r/integration_aws.html.markdown
  website/docs/r/integration_aws_lambda_arn.html.markdown
  website/docs/r/integration_aws_log_collection.html.markdown
  website/docs/r/integration_gcp.html.markdown
  website/docs/r/integration_pagerduty.html.markdown
  website/docs/r/logs_custom_pipeline.html.markdown
  website/docs/r/logs_index.html.markdown
  website/docs/r/logs_index_order.html.markdown
  website/docs/r/logs_integration_pipeline.html.markdown
  website/docs/r/logs_pipeline_order.html.markdown
  website/docs/r/monitor.html.markdown
  website/docs/r/service_level_objective.html.markdown
Labels: documentation, size/M

#518 integration_pagerduty: fix perpetual diff in api_token
  datadog/cassettes/TestAccDatadogIntegrationPagerdutyServiceObject_Basic.yaml
  datadog/cassettes/TestAccDatadogIntegrationPagerduty_Basic.yaml
  datadog/cassettes/TestAccDatadogIntegrationPagerduty_Migrate2ServiceObjects.yaml
  datadog/cassettes/TestAccDatadogIntegrationPagerduty_TwoServices.yaml
  datadog/cassettes/TestDatadogIntegrationPagerduty_import.yaml
  datadog/import_datadog_integration_pagerduty_test.go
  datadog/resource_datadog_integration_pagerduty.go
  datadog/resource_datadog_integration_pagerduty_test.go
Labels: size/XXL

#517 Add column revamp properties to dashboard log stream
  datadog/cassettes/TestAccDatadogDashboard_import.yaml
  datadog/cassettes/TestAccDatadogDashboard_update.yaml
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_test.go
  website/docs/r/dashboard.html.markdown
Labels: documentation, size/XXL

#524 Add support for tags_execution
  datadog/resource_datadog_dashboard.go
Labels: size/S

#525 Add support for tags_execution - Doc update
  website/docs/r/dashboard.html.markdown
Labels: documentation, size/XS

#521 Add full AWS Update support
  datadog/cassettes/TestAccDatadogIntegrationAWS.yaml
  datadog/resource_datadog_integration_aws.go
  datadog/resource_datadog_integration_aws_test.go
  website/docs/r/integration_aws.html.markdown
Labels: documentation, size/XL

#527 Add missing doc to nav and alphabetical order
  datadog/provider.go
  website/datadog.erb
Labels: documentation, size/XS

#536 Safely access index field
  datadog/resource_datadog_dashboard.go
Labels: size/XS

#542 Fix data source for IPRanges
  datadog/data_source_datadog_ip_ranges.go
Labels: size/XS

#543 Fix indent in datadog_monitor
  website/docs/r/monitor.html.markdown
Labels: documentation, size/XS

#535 Add monitor force_delete parameter
  datadog/resource_datadog_monitor.go
  website/docs/r/monitor.html.markdown
Labels: documentation, size/XS

#541 Allow to pass http client when creating test provider
  datadog/provider_test.go
Labels: size/S

#547 docs/dashboard: correct argument name for event_timeline_definition
  website/docs/r/dashboard.html.markdown
Labels: documentation, size/XS

#546 Prepare 2.8.1 release
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/DataDog/datadog-api-client-go/.apigentools-info
  vendor/github.com/DataDog/datadog-api-client-go/CHANGELOG.md
  vendor/github.com/DataDog/datadog-api-client-go/RELEASING.md
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/README.md
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_dashboard_lists.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_dashboards.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_downtimes.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_events.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_hosts.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_key_management.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_logs_indexes.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_logs_pipelines.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_metrics.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_monitors.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_organizations.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_pager_duty_integration.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_service_level_objectives.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_synthetics.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_tags.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_users.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_logs_list_request.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_monitor_device_id.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_synthetics_device_id.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_synthetics_location.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_synthetics_locations.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_synthetics_test_options_retry.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_widget_legend_size.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/README.md
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/api_dashboard_lists.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/api_logs_archives.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/api_roles.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/api_security_monitoring.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/api_users.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_logs_archive_destination.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_role_attributes.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_role_create_attributes.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_role_create_request.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_role_create_response.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_role_create_response_data.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_role_response_relationships.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_role_update_attributes.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_role_update_request.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_role_update_response.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_role_update_response_data.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_user_create_request.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_user_invitations_request.go
  vendor/github.com/DataDog/datadog-api-client-go/api/v2/datadog/model_user_update_request.go
  vendor/github.com/DataDog/datadog-api-client-go/run-tests.sh
  vendor/github.com/DataDog/datadog-api-client-go/version.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#548 Tests Cleanup
  datadog/resource_datadog_dashboard_alert_graph_test.go
  datadog/resource_datadog_dashboard_alert_value_test.go
  datadog/resource_datadog_dashboard_change_test.go
  datadog/resource_datadog_dashboard_check_status_test.go
  datadog/resource_datadog_dashboard_distribution_test.go
  datadog/resource_datadog_dashboard_event_stream_test.go
  datadog/resource_datadog_dashboard_event_timeline_test.go
  datadog/resource_datadog_dashboard_free_text_test.go
  datadog/resource_datadog_dashboard_heatmap_test.go
  datadog/resource_datadog_dashboard_hostmap_test.go
  datadog/resource_datadog_dashboard_iframe_test.go
  datadog/resource_datadog_dashboard_image_test.go
  datadog/resource_datadog_dashboard_log_stream_test.go
  datadog/resource_datadog_dashboard_manage_status_test.go
  datadog/resource_datadog_dashboard_note_test.go
  datadog/resource_datadog_dashboard_query_table_test.go
  datadog/resource_datadog_dashboard_query_value_test.go
  datadog/resource_datadog_dashboard_scatterplot_test.go
  datadog/resource_datadog_dashboard_service_map_test.go
  datadog/resource_datadog_dashboard_slo_test.go
  datadog/resource_datadog_dashboard_test.go
  datadog/resource_datadog_dashboard_timeseries_test.go
  datadog/resource_datadog_dashboard_top_list_test.go
  datadog/resource_datadog_dashboard_trace_service_test.go
Labels: size/XL

#549 Add excluded_regions to datadog_integration_aws
  datadog/cassettes/TestAccDatadogIntegrationAWS.yaml
  datadog/cassettes/TestAccDatadogIntegrationAWSLambdaArn.yaml
  datadog/cassettes/TestAccDatadogIntegrationAWSLogCollection.yaml
  datadog/resource_datadog_integration_aws.go
  datadog/resource_datadog_integration_aws_test.go
  website/docs/r/integration_aws.html.markdown
Labels: documentation, size/XL

#550 Add ServiceMap widget to datadog_dashboard
  datadog/cassettes/TestAccDatadogDashboardServiceMap.yaml
  datadog/cassettes/TestAccDatadogDashboardServiceMap_import.yaml
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_service_map_test.go
Labels: size/XXL

#551 Add show_legend and legend_size fields to Distribution widget to data…
  datadog/cassettes/TestAccDatadogDashboardDistribution.yaml
  datadog/cassettes/TestAccDatadogDashboardDistribution_import.yaml
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_distribution_test.go
Labels: size/XL

#553 Update Documentation
  website/docs/r/dashboard.html.markdown
Labels: size/XS

#552 Add logset test scenario for log stream widget
  GNUmakefile
  datadog/cassettes/TestAccDatadogDashboardLogStream.yaml
  datadog/cassettes/TestAccDatadogDashboardLogStreamLogSet.yaml
  datadog/cassettes/TestAccDatadogDashboardLogStreamLogSet_import.yaml
  datadog/cassettes/TestAccDatadogDashboardLogStream_import.yaml
  datadog/resource_datadog_dashboard_log_stream_test.go
Labels: size/XXL

#555 Add network_query and rum_query to timeseries widget
  datadog/cassettes/TestAccDatadogDashboardTimeseries.yaml
  datadog/cassettes/TestAccDatadogDashboardTimeseries_import.yaml
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_timeseries_test.go
  website/docs/r/dashboard.html.markdown
Labels: documentation, size/XL

#554 Add event, legend_size and show_legend fields to heatmap widget
  datadog/cassettes/TestAccDatadogDashboardHeatMap.yaml
  datadog/cassettes/TestAccDatadogDashboardHeatMap_import.yaml
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_heatmap_test.go
  website/docs/r/dashboard.html.markdown
Labels: documentation, size/XL

#558 add readonly url field to dashboard
  GNUmakefile
  datadog/resource_datadog_dashboard.go
  website/docs/r/dashboard.html.markdown
Labels: documentation, size/XS

#559 Prepare 2.10.0 release
  CHANGELOG.md
Labels: size/XS

#544 [logs][archives] Add Resource
  datadog/cassettes/TestAccDatadogDashboard_update.yaml
  datadog/cassettes/TestAccDatadogLogsArchiveAzure_basic.yaml
  datadog/cassettes/TestAccDatadogLogsArchiveGCS_basic.yaml
  datadog/cassettes/TestAccDatadogLogsArchiveS3Update_basic.yaml
  datadog/cassettes/TestAccDatadogLogsArchiveS3_basic.yaml
  datadog/data_source_datadog_ip_ranges_test.go
  datadog/import_datadog_downtime_test.go
  datadog/import_datadog_integration_pagerduty_test.go
  datadog/import_datadog_logs_pipeline_test.go
  datadog/import_datadog_monitor_test.go
  datadog/import_datadog_user_test.go
  datadog/provider.go
  datadog/provider_test.go
  datadog/resource_datadog_dashboard_list_test.go
  datadog/resource_datadog_dashboard_test.go
  datadog/resource_datadog_downtime_test.go
  datadog/resource_datadog_integration_aws_lambda_arn_test.go
  datadog/resource_datadog_integration_aws_log_collection_test.go
  datadog/resource_datadog_integration_aws_test.go
  datadog/resource_datadog_integration_gcp_test.go
  datadog/resource_datadog_integration_pagerduty_service_object_test.go
  datadog/resource_datadog_integration_pagerduty_test.go
  datadog/resource_datadog_logs_archive.go
  datadog/resource_datadog_logs_archive_test.go
  datadog/resource_datadog_logs_custom_pipeline_test.go
  datadog/resource_datadog_metric_metadata_test.go
  datadog/resource_datadog_monitor_test.go
  datadog/resource_datadog_screenboard_test.go
  datadog/resource_datadog_service_level_objective_test.go
  datadog/resource_datadog_synthetics_test_test.go
  datadog/resource_datadog_timeboard_test.go
  datadog/resource_datadog_user_test.go
  go.sum
  website/datadog.erb
  website/docs/r/logs_archive.html.markdown
Labels: size/XXL

#556 Add Azure TF resource
  datadog/cassettes/TestAccDatadogIntegrationAzure.yaml
  datadog/provider.go
  datadog/resource_datadog_integration_azure.go
  datadog/resource_datadog_integration_azure_test.go
  website/datadog.erb
  website/docs/r/integration_azure.html.markdown
Labels: documentation, size/XL

#561 Use tf azure integration in archives test
  datadog/cassettes/TestAccDatadogLogsArchiveAzure_basic.yaml
  datadog/resource_datadog_integration_azure_test.go
  datadog/resource_datadog_logs_archive_test.go
Labels: size/XL

#562 Update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#560 Workaround for golang/go#21881
  datadog/resource_datadog_downtime.go
  go.mod
  go.sum
  vendor/4d63.com/embedfiles/LICENSE
  vendor/4d63.com/embedfiles/README.md
  vendor/4d63.com/embedfiles/main.go
  vendor/4d63.com/tz/.gitignore
  vendor/4d63.com/tz/.travis.yml
  vendor/4d63.com/tz/LICENSE
  vendor/4d63.com/tz/README.md
  vendor/4d63.com/tz/go.mod
  vendor/4d63.com/tz/go.sum
  vendor/4d63.com/tz/tools.go
  vendor/4d63.com/tz/tz.go
  vendor/4d63.com/tz/zoneinfo.go
  vendor/modules.txt
Labels: dependencies, size/XXL
