Repository DataDog/terraform-provider-datadog, pull requests merged in 2020-03, with the labels that each got.

#442 Stabilize TestDatadogDashListImport test by always creating resources in the same order
  datadog/resource_datadog_dashboard_list_test.go
Labels: size/XS

#441 Document recording cassettes, make it possible to re-record for subset of tests
  README.md
Labels: size/XS

#443 We don't need to remove all cassettes before regenerating, they'll be overwritten
  GNUmakefile
Labels: size/XS

#447 Update go-datadog-api client to v2.28.0, revendor deps
  go.mod
  go.sum
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression_vars_gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/github.com/zorkian/go-datadog-api/board_widgets.go
  vendor/github.com/zorkian/go-datadog-api/dashboards.go
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/helpers.go
  vendor/github.com/zorkian/go-datadog-api/monitors.go
  vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
  vendor/github.com/zorkian/go-datadog-api/service_level_objectives.go
  vendor/github.com/zorkian/go-datadog-api/synthetics.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#450 Api error mgmt + enhanced provider
  datadog/data_source_datadog_ip_ranges.go
  datadog/import_datadog_logs_pipeline_test.go
  datadog/provider.go
  datadog/provider_test.go
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_list.go
  datadog/resource_datadog_dashboard_list_test.go
  datadog/resource_datadog_dashboard_test.go
  datadog/resource_datadog_downtime.go
  datadog/resource_datadog_downtime_test.go
  datadog/resource_datadog_integration_aws.go
  datadog/resource_datadog_integration_gcp.go
  datadog/resource_datadog_integration_gcp_test.go
  datadog/resource_datadog_integration_pagerduty.go
  datadog/resource_datadog_integration_pagerduty_service_object.go
  datadog/resource_datadog_integration_pagerduty_service_object_test.go
  datadog/resource_datadog_integration_pagerduty_test.go
  datadog/resource_datadog_logs_custom_pipeline.go
  datadog/resource_datadog_logs_custom_pipeline_test.go
  datadog/resource_datadog_logs_index.go
  datadog/resource_datadog_logs_index_order.go
  datadog/resource_datadog_logs_integration_pipeline.go
  datadog/resource_datadog_logs_pipeline_order.go
  datadog/resource_datadog_metric_metadata.go
  datadog/resource_datadog_metric_metadata_test.go
  datadog/resource_datadog_monitor.go
  datadog/resource_datadog_monitor_test.go
  datadog/resource_datadog_screenboard.go
  datadog/resource_datadog_screenboard_test.go
  datadog/resource_datadog_service_level_objective.go
  datadog/resource_datadog_service_level_objective_test.go
  datadog/resource_datadog_synthetics_test_.go
  datadog/resource_datadog_synthetics_test_test.go
  datadog/resource_datadog_timeboard.go
  datadog/resource_datadog_timeboard_test.go
  datadog/resource_datadog_user.go
  datadog/resource_datadog_user_test.go
Labels: size/XXL

#453 Update scope docs with explicit example
  website/docs/r/downtime.html.markdown
Labels: documentation, size/XS

#452 Fail fast if index isn't imported
  datadog/resource_datadog_logs_index.go
Labels: size/XS

#455 Add terraform sdk + cli versions to user agent header
  datadog/provider.go
Labels: size/XS

#460 doc: AWS integration & EU Datadog clarifications
  website/docs/index.html.markdown
  website/docs/r/integration_aws.html.markdown
Labels: documentation, size/XS
