Repository DataDog/terraform-provider-datadog, pull requests merged in 2020-04, with the labels that each got.

#472 Update the api error message
  datadog/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/XS

#476 update dependencies and fix provider.go
  datadog/provider.go
  go.mod
  go.sum
Labels: size/M

#477 Add Generated client v2 API
  datadog/provider.go
  datadog/provider_test.go
Labels: size/L

#469 Add support for env variable with DD prefixes
  GNUmakefile
  README.md
  datadog/provider.go
  datadog/provider_test.go
  website/docs/index.html.markdown
Labels: documentation, size/S

#415 LI-104: Add support for lookup processor
  datadog/cassettes/TestAccDatadogLogsPipeline_basic.yaml
  datadog/resource_datadog_logs_custom_pipeline.go
  datadog/resource_datadog_logs_custom_pipeline_test.go
  website/docs/r/logs_custom_pipeline.html.markdown
Labels: documentation, size/XL

#490 Migrate SLO resource with Official Go SDK
  datadog/resource_datadog_service_level_objective.go
  datadog/resource_datadog_service_level_objective_test.go
Labels: size/M

#486 Update metric_metadata resource to use Datadog Go client
  datadog/cassettes/TestAccDatadogMetricMetadata_Basic.freeze
  datadog/cassettes/TestAccDatadogMetricMetadata_Basic.yaml
  datadog/cassettes/TestAccDatadogMetricMetadata_Updated.freeze
  datadog/cassettes/TestAccDatadogMetricMetadata_Updated.yaml
  datadog/resource_datadog_metric_metadata.go
Labels: size/XL

#482 Update GCP resource to use Datadog Go client
  datadog/cassettes/TestAccDatadogIntegrationGCP.yaml
  datadog/resource_datadog_integration_gcp.go
  datadog/resource_datadog_integration_gcp_test.go
Labels: size/XL

#436 Add AWS Log Lambda Integration
  datadog/cassettes/TestAccDatadogIntegrationAWS.yaml
  datadog/cassettes/TestAccDatadogIntegrationAWSLambdaArn.yaml
  datadog/provider.go
  datadog/resource_datadog_integration_aws_lambda_arn.go
  datadog/resource_datadog_integration_aws_lambda_arn_test.go
  datadog/resource_datadog_integration_aws_test.go
  website/docs/r/integration_aws_lambda_arn.html.markdown
Labels: documentation, size/XXL

#480 Update Downtime resource to use Datadog Go client
  datadog/cassettes/TestAccDatadogDowntimeDates.yaml
  datadog/cassettes/TestAccDatadogDowntime_Basic.yaml
  datadog/cassettes/TestAccDatadogDowntime_BasicMultiScope.yaml
  datadog/cassettes/TestAccDatadogDowntime_BasicNoRecurrence.yaml
  datadog/cassettes/TestAccDatadogDowntime_BasicUntilDateRecurrence.yaml
  datadog/cassettes/TestAccDatadogDowntime_BasicUntilOccurrencesRecurrence.yaml
  datadog/cassettes/TestAccDatadogDowntime_BasicWithMonitor.freeze
  datadog/cassettes/TestAccDatadogDowntime_BasicWithMonitor.yaml
  datadog/cassettes/TestAccDatadogDowntime_BasicWithMonitorTags.freeze
  datadog/cassettes/TestAccDatadogDowntime_BasicWithMonitorTags.yaml
  datadog/cassettes/TestAccDatadogDowntime_TrimWhitespace.yaml
  datadog/cassettes/TestAccDatadogDowntime_Updated.yaml
  datadog/cassettes/TestAccDatadogDowntime_WeekDayRecurring.yaml
  datadog/resource_datadog_downtime.go
  datadog/resource_datadog_downtime_test.go
Labels: size/XXL

#491 Migrate IP Range resource with Official Go SDK
  datadog/cassettes/TestAccDatadogIpRangesDatasource_existing.yaml
  datadog/data_source_datadog_ip_ranges.go
Labels: size/L

#488 Update pagerduty_service_object resource to use Datadog Go client
  datadog/cassettes/TestAccDatadogIntegrationPagerdutyServiceObject_Basic.yaml
  datadog/data_source_datadog_ip_ranges.go
  datadog/resource_datadog_integration_pagerduty_service_object.go
Labels: size/XL

#483 Update Logs resources resource to use Datadog Go client
  datadog/provider.go
  datadog/resource_datadog_logs_index.go
  datadog/resource_datadog_logs_index_order.go
  datadog/resource_datadog_logs_integration_pipeline.go
  datadog/resource_datadog_logs_pipeline_order.go
Labels: size/M

#437 Add aws log collection service resource
  datadog/cassettes/TestAccDatadogIntegrationAWSLogCollection.yaml
  datadog/provider.go
  datadog/resource_datadog_integration_aws_log_collection.go
  datadog/resource_datadog_integration_aws_log_collection_test.go
  website/docs/r/integration_aws_log_collection.html.markdown
Labels: documentation, size/XL

#421 Add legend_size to api request
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_test.go
  website/docs/r/dashboard.html.markdown
Labels: documentation, size/XS

#493 Update cassette for dashboard update test
  datadog/cassettes/TestAccDatadogDashboard_import.yaml
  datadog/cassettes/TestAccDatadogDashboard_update.yaml
Labels: size/XXL

#485 Update monitor resource to use Datadog Go client
  datadog/cassettes/TestAccDatadogMonitorServiceCheck_Basic.yaml
  datadog/cassettes/TestAccDatadogMonitor_Basic.yaml
  datadog/cassettes/TestAccDatadogMonitor_BasicNoTreshold.yaml
  datadog/cassettes/TestAccDatadogMonitor_Basic_float_int.yaml
  datadog/cassettes/TestAccDatadogMonitor_ComposeWithSyntheticsTest.yaml
  datadog/cassettes/TestAccDatadogMonitor_Log.yaml
  datadog/cassettes/TestAccDatadogMonitor_MuteUnmuteSpecificScopes.yaml
  datadog/cassettes/TestAccDatadogMonitor_NoThresholdWindows.yaml
  datadog/cassettes/TestAccDatadogMonitor_SilencedRemove.yaml
  datadog/cassettes/TestAccDatadogMonitor_SilencedUpdateNoDiff.yaml
  datadog/cassettes/TestAccDatadogMonitor_SilencedUpdatePastTimestamp.yaml
  datadog/cassettes/TestAccDatadogMonitor_ThresholdWindows.yaml
  datadog/cassettes/TestAccDatadogMonitor_TrimWhitespace.yaml
  datadog/cassettes/TestAccDatadogMonitor_Updated.yaml
  datadog/cassettes/TestAccDatadogMonitor_UpdatedToRemoveTags.yaml
  datadog/provider.go
  datadog/provider_test.go
  datadog/resource_datadog_monitor.go
  datadog/resource_datadog_monitor_test.go
Labels: size/XXL

#465 remove ignore_changes quotes in monitor example
  website/docs/r/monitor.html.markdown
Labels: documentation, size/XS

#496 add deprecation messages
  datadog/resource_datadog_integration_pagerduty.go
  datadog/resource_datadog_screenboard.go
  datadog/resource_datadog_timeboard.go
Labels: size/S

#479 Update Dashboard_list resource to use Datadog Go client
  datadog/cassettes/TestDatadogDashListImport.yaml
  datadog/resource_datadog_dashboard_list.go
  datadog/resource_datadog_dashboard_list_test.go
Labels: size/XL

#474 provider: add "validate" option that can disable validation
  datadog/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/S
