Repository DataDog/terraform-provider-datadog, pull requests merged in 2020-02, with the labels that each got.

#404 Properly set screenboard attributes from client response to not produce non-empty plans
  datadog/resource_datadog_screenboard.go
Labels: size/XS

#403 Hide deprecated monitor summary widget params
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_screenboard.go
  website/docs/r/dashboard.html.markdown
  website/docs/r/screenboard.html.markdown
Labels: documentation, size/XS

#405 Gracefully handle downtimes that were canceled manually
  datadog/resource_datadog_downtime.go
Labels: size/XS

#406 Improve monitor example with ignoring changes on silenced
  website/docs/r/monitor.html.markdown
Labels: documentation, size/XS

#407 Update go-datadog-api to 2.27.0 rerun mod vendoring + tidy up
  go.mod
  go.sum
  vendor/github.com/zorkian/go-datadog-api/Makefile
  vendor/github.com/zorkian/go-datadog-api/api_keys.go
  vendor/github.com/zorkian/go-datadog-api/app_keys.go
  vendor/github.com/zorkian/go-datadog-api/boards.go
  vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
  vendor/github.com/zorkian/go-datadog-api/integrations.go
  vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
  vendor/github.com/zorkian/go-datadog-api/synthetics.go
  vendor/modules.txt
Labels: dependencies, size/XL

#400 Fix optional threshold fields handling in update function
  datadog/resource_datadog_service_level_objective.go
  datadog/resource_datadog_service_level_objective_test.go
Labels: size/M

#401 Add template_variable_presets to datadog_dashboard
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_test.go
  website/docs/r/dashboard.html.markdown
Labels: documentation, size/L

#373 Add Datadog dashboard query table
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_test.go
  website/docs/r/dashboard.html.markdown
Labels: dependencies, documentation, size/L

#410 Prepare changelog for 2.7.0 release
  CHANGELOG.md
Labels: size/XS

#418 [MA-902] no data timeframe doc clarification
  website/docs/r/monitor.html.markdown
Labels: documentation, size/XS
