Repository DataDog/terraform-provider-datadog, pull requests merged in 2022-12, with the labels that each got.

#1660 [datadog_service_definition_yaml] Fix panic on missing name in service definition links
  datadog/resource_datadog_service_definition_yaml.go
Labels: changelog/bugfix

#1655 [datadog_logs_custom_pipeline] Handle nested empty filter query
  datadog/resource_datadog_logs_custom_pipeline.go
  datadog/tests/cassettes/TestAccDatadogLogsPipelineEmptyFilterQuery.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipelineEmptyFilterQuery.yaml
  datadog/tests/resource_datadog_logs_custom_pipeline_test.go
Labels: changelog/bugfix

#1657 [datadog_integration_aws] Properly handle missing resource when importing
  datadog/resource_datadog_integration_aws.go
Labels: changelog/bugfix

#1658 [datadog_logs_archive] mark `path` as optional
  datadog/resource_datadog_logs_archive.go
  docs/resources/logs_archive.md
Labels: changelog/bugfix

#1661 [datadog_logs_archive_order] Add a logs archive order data source
  datadog/data_source_datadog_logs_archives_order.go
  datadog/provider.go
  datadog/tests/cassettes/TestAccDatadogLogsArchivesOrderDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchivesOrderDatasource.yaml
  datadog/tests/data_source_datadog_logs_archives_order_test.go
  datadog/tests/provider_test.go
  docs/data-sources/logs_archives_order.md
Labels: changelog/feature

#1667 [datadog_downtime] Specify downtime start/end and timezone format
  datadog/resource_datadog_downtime.go
  docs/resources/downtime.md
Labels: changelog/no-changelog

#1663 Add warning about debug output to issue template
  .github/ISSUE_TEMPLATE.md
Labels: changelog/no-changelog

#1668 [datadog_synthetics_test] Add support for oauth authentication
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogRUMApplication_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogRUMApplication_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_importBasic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_importBasic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
  go.mod
  go.sum
Labels: changelog/feature, resource/datadog_synthetics_test

#1669 [datadog_synthetics_test] Add Digest auth
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/improvement, resource/datadog_synthetics_test

#1641 [datadog_rum_application] Add a RUM application data source
  datadog/data_source_datadog_rum_application.go
  datadog/provider.go
  datadog/resource_datadog_rum_application.go
  datadog/tests/cassettes/TestAccDatadogRUMApplicationDatasourceErrorMultiple.freeze
  datadog/tests/cassettes/TestAccDatadogRUMApplicationDatasourceErrorMultiple.yaml
  datadog/tests/cassettes/TestAccDatadogRUMApplicationDatasourceIDFilter.freeze
  datadog/tests/cassettes/TestAccDatadogRUMApplicationDatasourceIDFilter.yaml
  datadog/tests/cassettes/TestAccDatadogRUMApplicationDatasourceNameFilter.freeze
  datadog/tests/cassettes/TestAccDatadogRUMApplicationDatasourceNameFilter.yaml
  datadog/tests/data_source_datadog_rum_application_test.go
  datadog/tests/provider_test.go
  docs/data-sources/rum_application.md
Labels: changelog/improvement

#1670 [datadog_monitor] Add enable_samples monitor options
  datadog/data_source_datadog_monitor.go
  datadog/resource_datadog_monitor.go
  docs/data-sources/monitor.md
  docs/resources/monitor.md
  go.mod
  go.sum
Labels: changelog/feature

#1678 Bump `datadog-api-client` version to v2.6.1
  go.mod
  go.sum
Labels: provider, changelog/note, ci/integrations

#1683 [datadog_logs_metric] Fix `getUpdateCompute ` method for non distribution aggregation type
  datadog/resource_datadog_logs_metric.go
  datadog/tests/cassettes/TestAccDatadogLogsMetricCount_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsMetricCount_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_InvalidTypes.freeze
  datadog/tests/resource_datadog_logs_metric_test.go
Labels: changelog/bugfix, resource/datadog_logs_metric

#1688 Add more `site` examples and link to site docs page
  datadog/provider.go
  docs/index.md
Labels: changelog/no-changelog

#1686 [service_definition_yaml] Add tag normalization util
  datadog/internal/utils/tags.go
  datadog/internal/utils/tags_test.go
  datadog/resource_datadog_service_definition_yaml.go
  datadog/resource_datadog_service_level_objective.go
Labels: changelog/improvement

#1689 Fix slo examples by removing computed fields
  datadog/tests/data_source_datadog_logs_archives_order_test.go
  docs/resources/service_level_objective.md
  examples/resources/datadog_service_level_objective/resource.tf
Labels: changelog/no-changelog
