Repository DataDog/terraform-provider-datadog, pull requests merged in 2022-09, with the labels that each got.

#1542 [datadog_role] Upgrade provider from old single-permission APIs to newer UpdateRole API
  datadog/resource_datadog_role.go
  datadog/tests/cassettes/TestAccDatadogRole_CreateUpdate.freeze
  datadog/tests/cassettes/TestAccDatadogRole_CreateUpdate.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_Updated.yaml
  go.mod
  go.sum
Labels: changelog/improvement, aaa-access

#1549 Fix failing downtime integration tests
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_downtime_test.go
Labels: changelog/no-changelog, ci/integrations

#1547 Bump datadog-api-client to v2.2.0
  docs/resources/dashboard.md
  docs/resources/synthetics_global_variable.md
  docs/resources/synthetics_test.md
  go.mod
  go.sum
Labels: changelog/note, ci/integrations

#1422 Add release doc
  RELEASING.md
Labels: changelog/no-changelog

#1560 [datadog_ip_ranges] Fix `IPRanges` server configuration
  datadog/provider.go
Labels: changelog/bugfix, resource/datadog_ip_ranges

#1553 [datadog_synthetics_test] Add missing options for synthetics tests
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_importBasic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
  go.mod
  go.sum
Labels: changelog/improvement, ci/integrations

#1557 [datadog_dashboard] add Topology Map definition
  datadog/resource_datadog_dashboard.go
  datadog/tests/cassettes/TestAccDatadogDashboardTopologyMap.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardTopologyMap.yaml
  datadog/tests/cassettes/TestAccDatadogDashboardTopologyMap_import.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardTopologyMap_import.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_dashboard_topology_map_test.go
  docs/resources/dashboard.md
  go.mod
  go.sum
Labels: changelog/improvement, resource/datadog_dashboard

#1428 [datadog_integration_gcp] Add example w/ `google_service_account_key` resource
  docs/resources/integration_gcp.md
  examples/resources/datadog_integration_gcp/resource.tf
Labels: changelog/no-changelog

#1555 [datadog_logs_pipelines] Add a pipelines datasource
  datadog/data_source_datadog_logs_pipelines.go
  datadog/provider.go
  datadog/tests/cassettes/TestAccDatadogLogsPipelinesDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipelinesDatasource.yaml
  datadog/tests/cassettes/TestAccDatadogLogsPipelinesDatasourceReadonly.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipelinesDatasourceReadonly.yaml
  datadog/tests/data_source_datadog_logs_pipelines_test.go
  datadog/tests/provider_test.go
  docs/data-sources/logs_pipelines.md
  examples/data-sources/datadog_logs_pipelines/data-source.tf
Labels: changelog/feature, ci/integrations

#1490 [datadog_user] Add service account support
  datadog/resource_datadog_application_key.go
  datadog/resource_datadog_user.go
  datadog/tests/cassettes/TestAccDatadogUser_ServiceAccount.freeze
  datadog/tests/cassettes/TestAccDatadogUser_ServiceAccount.yaml
  datadog/tests/cassettes/TestAccDatadogUser_ServiceAccountForceNew.freeze
  datadog/tests/cassettes/TestAccDatadogUser_ServiceAccountForceNew.yaml
  datadog/tests/data_source_datadog_application_key_test.go
  datadog/tests/resource_datadog_application_key_test.go
  datadog/tests/resource_datadog_user_test.go
  docs/resources/application_key.md
  docs/resources/user.md
  examples/resources/datadog_application_key/resource.tf
  examples/resources/datadog_user/resource.tf
Labels: changelog/feature, ci/integrations, aaa-access, aaa-identity

#1576 [datadog_dashboards] Handle empty group definition
  datadog/internal/utils/key.go
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_logs_archive.go
  datadog/resource_datadog_logs_archive_order.go
  datadog/tests/data_source_datadog_application_key_test.go
  datadog/tests/resource_datadog_logs_archive_test.go
  docs/resources/dashboard.md
Labels: changelog/bugfix, resource/datadog_dashboard

#1579 [datadog_security_monitoring_default_rule] Add missing schema attribute `type`
  datadog/resource_datadog_security_monitoring_default_rule.go
  docs/resources/security_monitoring_default_rule.md
Labels: changelog/bugfix, resource/datadog_security_monitoring_default_rule

#1567 [datadog_synthetics_global_variable] Add support for local variable extract from test
  datadog/resource_datadog_synthetics_global_variable.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFromTest_LocalVariable.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFromTest_LocalVariable.yaml
  datadog/tests/resource_datadog_synthetics_global_variable_test.go
  docs/resources/synthetics_global_variable.md
Labels: changelog/feature, resource/datadog_synthetics_global_variable, ci/integrations

#1586 [datadog_user] Revert "[datadog_user] Add service account support (#1490)"
  datadog/resource_datadog_application_key.go
  datadog/resource_datadog_user.go
  datadog/tests/cassettes/TestAccDatadogUser_ServiceAccount.freeze
  datadog/tests/cassettes/TestAccDatadogUser_ServiceAccount.yaml
  datadog/tests/cassettes/TestAccDatadogUser_ServiceAccountForceNew.freeze
  datadog/tests/cassettes/TestAccDatadogUser_ServiceAccountForceNew.yaml
  datadog/tests/data_source_datadog_application_key_test.go
  datadog/tests/resource_datadog_application_key_test.go
  datadog/tests/resource_datadog_user_test.go
  docs/resources/application_key.md
  docs/resources/user.md
  examples/resources/datadog_application_key/resource.tf
  examples/resources/datadog_user/resource.tf
Labels: changelog/no-changelog

#1584 [datadog_security_monitoring] Update security-monitoring to use new api format
  datadog/data_source_datadog_security_monitoring_rules.go
  datadog/resource_datadog_security_monitoring_default_rule.go
  datadog/resource_datadog_security_monitoring_rule.go
  datadog/tests/data_source_datadog_security_monitoring_rules_test.go
  docs/resources/security_monitoring_rule.md
  go.mod
  go.sum
Labels: changelog/no-changelog, ci/integrations
