Repository DataDog/terraform-provider-datadog, pull requests merged in 2022-08, with the labels that each got.

#1509 [security_monitoring_filter] Fix security monitoring filter tests
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringFilter.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringFilter.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringFilterDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringFilterDatasource.yaml
  datadog/tests/resource_datadog_security_monitoring_filter_test.go
Labels: changelog/no-changelog, resource/datadog_security_monitoring_filters, ci/integrations

#1519 [datadog_synthetics_private_location] Improve restricted_roles handling
  datadog/resource_datadog_synthetics_private_location.go
Labels: changelog/bugfix

#1522 [Synthetics] Change documentation url for locations
  datadog/resource_datadog_synthetics_test_.go
  docs/resources/synthetics_test.md
Labels: changelog/no-changelog

#1527 [datadog_synthetics_test] Fix target for packet loss assertions
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsICMPTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsICMPTest_Basic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/bugfix, resource/datadog_synthetics_test

#1532 [datadog_synthetics_test] Add DiffSupressFunc for rum settings
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/improvement, resource/datadog_synthetics_test

#1534 [provider] Handle redirects by retaining the original request/redirect body
  datadog/internal/transport/custom_transport.go
Labels: changelog/bugfix

#1529 [datadog_monitor] Suppress diff when using `ok` and `unknown` thresholds in non `service check` monitors.
  datadog/resource_datadog_monitor.go
  datadog/tests/cassettes/TestAccDatadogMonitor_NoThresholdWindows.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_NoThresholdWindows.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_ThresholdWindows.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_ThresholdWindows.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_TrimWhitespace.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_TrimWhitespace.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_UpdatedToRemoveTags.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_UpdatedToRemoveTags.yaml
  datadog/tests/cassettes/TestDatadogMonitor_import.freeze
  datadog/tests/cassettes/TestDatadogMonitor_import.yaml
  datadog/tests/cassettes/TestDatadogMonitor_importNoDataTimeFrame.freeze
  datadog/tests/cassettes/TestDatadogMonitor_importNoDataTimeFrame.yaml
  datadog/tests/cassettes/TestDatadogMonitor_import_no_recovery.freeze
  datadog/tests/cassettes/TestDatadogMonitor_import_no_recovery.yaml
  datadog/tests/resource_datadog_monitor_test.go
  docs/resources/monitor.md
Labels: changelog/improvement

#1518 [datadog_synthetics_test] suppress whitespace diff when comparing files
  datadog/resource_datadog_synthetics_test_.go
Labels: changelog/bugfix, resource/datadog_synthetics_test

#1525 [datadog_dashboard] add support for priority parameters in ManageStatus widget
  datadog/resource_datadog_dashboard.go
  datadog/tests/cassettes/TestAccDatadogDashboardManageStatus.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardManageStatus.yaml
  datadog/tests/cassettes/TestAccDatadogDashboardManageStatus_import.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardManageStatus_import.yaml
  datadog/tests/cassettes/TestAccDatadogDashboard_import.freeze
  datadog/tests/cassettes/TestAccDatadogDashboard_import.yaml
  datadog/tests/cassettes/TestAccDatadogFreeDashboard.freeze
  datadog/tests/cassettes/TestAccDatadogFreeDashboard.yaml
  datadog/tests/resource_datadog_dashboard_manage_status_test.go
  datadog/tests/resource_datadog_dashboard_test.go
  docs/resources/dashboard.md
  go.mod
  go.sum
Labels: changelog/improvement, resource/datadog_dashboard

#1537 [RUM] Adds RUM Application resource support
  datadog/provider.go
  datadog/resource_datadog_rum_application.go
  datadog/tests/cassettes/TestAccDatadogRUMApplication_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogRUMApplication_Basic.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_rum_application_test.go
  docs/resources/rum_application.md
  examples/resources/datadog_rum_application/import.sh
  examples/resources/datadog_rum_application/resource.tf
Labels: changelog/feature, ci/integrations

#1538 RUM App support: Minor doc fix
  datadog/resource_datadog_rum_application.go
  docs/resources/rum_application.md
Labels: changelog/no-changelog

#1540 Update README.md
  README.md
Labels: changelog/no-changelog

#1546 [datadog_dashboard] Handle empty requests definition in hostmap widget
  datadog/resource_datadog_dashboard.go
Labels: changelog/bugfix
