Repository DataDog/terraform-provider-datadog, pull requests merged in 2022-10, with the labels that each got.

#1569 [dashboards] add support for storage parameter in widget queries
  datadog/resource_datadog_dashboard.go
  datadog/tests/cassettes/TestAccDatadogDashboardFormula.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardFormula.yaml
  datadog/tests/cassettes/TestAccDatadogDashboardFormula_import.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardFormula_import.yaml
  datadog/tests/cassettes/TestAccDatadogDashboardListStreamStorage.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardListStreamStorage.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_dashboard_list_stream_storage_test.go
  datadog/tests/resource_datadog_dashboard_timeseries_test.go
  docs/resources/dashboard.md
Labels: changelog/improvement

#1595 [datadog_dashboard] Add support for the SLO List widget
  DEVELOPMENT.md
  datadog/resource_datadog_dashboard.go
  datadog/tests/cassettes/TestAccDatadogDashboardSloList.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardSloList.yaml
  datadog/tests/cassettes/TestAccDatadogDashboardSloList_import.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardSloList_import.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_dashboard_slo_list_test.go
  docs/resources/dashboard.md
Labels: changelog/improvement

#1605 [datadog_synthetics_test] Add missing disable_cors option
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_importBasic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
Labels: changelog/improvement

#1608 [logs_metrics] add nil check to Logs Metrics getGroupBys
  datadog/resource_datadog_logs_metric.go
Labels: changelog/bugfix

#1610 Bump `datadog-api-client` to v2.4.0
  go.mod
  go.sum
Labels: changelog/note, ci/integrations

#1597 [datadog_provider] Bump `go` and `terraform-plugin-sdk` versions
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/test_integration.yml
  go.mod
  go.sum
Labels: changelog/note, ci/integrations

#1615 [datadog_monitor] Handle explicit null for `new_host_delay`
  datadog/resource_datadog_monitor.go
Labels: changelog/bugfix

#1614 [datadog_dashboard] Suppress URL attribute diff
  datadog/resource_datadog_dashboard.go
Labels: changelog/bugfix

#1618 Add import documentation for datadog_dashboard_json
  docs/resources/dashboard_json.md
  examples/resources/datadog_dashboard_json/import.sh
Labels: changelog/no-changelog

#1622 [datadog_dashboard] Add support for `values` and `defaults` in template variables
  datadog/resource_datadog_dashboard.go
  datadog/tests/cassettes/TestAccDatadogDashboardTemplateVariables.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardTemplateVariables.yaml
  datadog/tests/resource_datadog_dashboard_test.go
  docs/resources/dashboard.md
Labels: changelog/improvement
