Repository DataDog/terraform-provider-datadog, pull requests merged in 2022-07, with the labels that each got.

#1464 [synthetics_test] Add rum settings
  LICENSE-3rdparty.csv
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_importBasic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
  go.mod
  go.sum
Labels: changelog/improvement

#1480 Use client release 1.15
  go.mod
  go.sum
Labels: changelog/no-changelog, ci/integrations

#1472 Rename the security-monitoring Github team
  .github/CODEOWNERS
Labels: changelog/no-changelog

#1482 Fix failing monitors integration tests
  datadog/tests/cassettes/TestAccDatadogMonitorDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogMonitorDatasource.yaml
  datadog/tests/cassettes/TestAccDatadogMonitorJSONBasic.freeze
  datadog/tests/cassettes/TestAccDatadogMonitorJSONBasic.yaml
  datadog/tests/cassettes/TestAccDatadogMonitorJSONImport.freeze
  datadog/tests/cassettes/TestAccDatadogMonitorJSONImport.yaml
  datadog/tests/cassettes/TestAccDatadogMonitorServiceCheck_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogMonitorServiceCheck_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_BasicNoTreshold.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_BasicNoTreshold.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_Basic_float_int.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_Basic_float_int.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_ComposeWithSyntheticsTest.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_ComposeWithSyntheticsTest.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_Log.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_Log.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_NoThresholdWindows.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_NoThresholdWindows.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_RestrictedRoles.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_RestrictedRoles.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_ThresholdWindows.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_ThresholdWindows.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_TrimWhitespace.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_TrimWhitespace.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_UpdatedToRemoveTags.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_UpdatedToRemoveTags.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_ZeroDelay.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_ZeroDelay.yaml
  datadog/tests/cassettes/TestAccDatadogMonitorsDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogMonitorsDatasource.yaml
  datadog/tests/cassettes/TestDatadogMonitor_import.freeze
  datadog/tests/cassettes/TestDatadogMonitor_import.yaml
  datadog/tests/cassettes/TestDatadogMonitor_importNoDataTimeFrame.freeze
  datadog/tests/cassettes/TestDatadogMonitor_importNoDataTimeFrame.yaml
  datadog/tests/cassettes/TestDatadogMonitor_import_no_recovery.freeze
  datadog/tests/cassettes/TestDatadogMonitor_import_no_recovery.yaml
  datadog/tests/data_source_datadog_monitor_test.go
  datadog/tests/data_source_datadog_monitors_test.go
  datadog/tests/import_datadog_monitor_test.go
  datadog/tests/resource_datadog_monitor_test.go
Labels: changelog/no-changelog, ci/integrations

#1486 Don't use forked tf plugin docs version
  LICENSE-3rdparty.csv
  go.mod
  go.sum
Labels: changelog/no-changelog

#1500 [datadog_synthetics_test] Add support for grpc subtype
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsGRPCTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGRPCTest_Basic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
Labels: changelog/feature, resource/datadog_synthetics_test

#1501 [provider] Update go client
  go.mod
  go.sum
Labels: changelog/note

#1504 [datadog_synthetics_tests] Update tcp tests to include connection assertion
  datadog/tests/cassettes/TestAccDatadogSyntheticsTCPTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTCPTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTCPTest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTCPTest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTCPTest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTCPTest_importBasic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/no-changelog, resource/datadog_synthetics_test, ci/integrations

#1505 Rerecord roles test to fix cassettes
  datadog/tests/cassettes/TestAccDatadogRoleDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogRoleDatasource.yaml
  datadog/tests/cassettes/TestAccDatadogRoleDatasourceError.freeze
  datadog/tests/cassettes/TestAccDatadogRoleDatasourceError.yaml
  datadog/tests/cassettes/TestAccDatadogRoleDatasourceExactMatch.freeze
  datadog/tests/cassettes/TestAccDatadogRoleDatasourceExactMatch.yaml
  datadog/tests/cassettes/TestAccDatadogRole_CreateUpdate.freeze
  datadog/tests/cassettes/TestAccDatadogRole_CreateUpdate.yaml
  datadog/tests/cassettes/TestAccDatadogRole_InvalidPerm.freeze
  datadog/tests/cassettes/TestAccDatadogRolesDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogRolesDatasource.yaml
  datadog/tests/cassettes/TestAccDatadogRolesDatasourceMultipleMatch.freeze
  datadog/tests/cassettes/TestAccDatadogRolesDatasourceMultipleMatch.yaml
Labels: changelog/no-changelog
