Repository DataDog/terraform-provider-datadog, pull requests merged in 2022-04, with the labels that each got.

#1400 [datadog_monitor] Mark locked as deprecated
  datadog/resource_datadog_monitor.go
  docs/resources/monitor.md
Labels: changelog/note

#1407 [datadog_security_monitoring_rule] Add default for aggregation
  datadog/resource_datadog_security_monitoring_rule.go
Labels: changelog/bugfix

#1404 [resource_datadog_metric_metadata] Clarify supported metric types
  datadog/resource_datadog_metric_metadata.go
  docs/resources/metric_metadata.md
Labels: changelog/no-changelog

#1399 Add debug mode for developers
  DEVELOPMENT.md
  main.go
Labels: provider, changelog/note

#1409 Bump datadog-api-client-go to v1.12.0
  datadog/internal/utils/custom_request.go
  go.mod
  go.sum
Labels: changelog/note, ci/integrations

#1414 Bump datadog-api-client-go to latest master
  datadog/data_source_datadog_security_monitoring_rules.go
  datadog/data_source_datadog_synthetics_global_variable.go
  datadog/data_source_datadog_synthetics_test_.go
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_logs_custom_pipeline.go
  datadog/resource_datadog_logs_index.go
  datadog/resource_datadog_security_monitoring_default_rule.go
  datadog/resource_datadog_security_monitoring_rule.go
  datadog/resource_datadog_synthetics_global_variable.go
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogDowntime_BasicWithMonitor.freeze
  datadog/tests/cassettes/TestAccDatadogDowntime_BasicWithMonitor.yaml
  datadog/tests/cassettes/TestAccDatadogDowntime_BasicWithMonitorTags.freeze
  datadog/tests/cassettes/TestAccDatadogDowntime_BasicWithMonitorTags.yaml
  datadog/tests/cassettes/TestAccDatadogMonitorDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogMonitorDatasource.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_Basic_float_int.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_Basic_float_int.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_RestrictedRoles.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_RestrictedRoles.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_UpdatedToRemoveTags.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_UpdatedToRemoveTags.yaml
  datadog/tests/data_source_datadog_cloud_workload_security_agent_rules_test.go
  datadog/tests/data_source_datadog_security_monitoring_filters_test.go
  datadog/tests/data_source_datadog_security_monitoring_rules_test.go
  go.mod
  go.sum
Labels: changelog/no-changelog

#1415 [datadog_resource_dashboard] Implement support for timeseries background in query value widgets
  datadog/resource_datadog_dashboard.go
  datadog/tests/cassettes/TestAccDatadogDashboardQueryValue.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardQueryValue.yaml
  datadog/tests/cassettes/TestAccDatadogDashboardQueryValue_import.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardQueryValue_import.yaml
  datadog/tests/resource_datadog_dashboard_query_value_test.go
  docs/resources/dashboard.md
Labels: changelog/improvement

#1412 Fix integration tests
  datadog/tests/cassettes/TestAccDatadogRole_CreateUpdate.freeze
  datadog/tests/cassettes/TestAccDatadogRole_CreateUpdate.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringDefaultRule_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringDefaultRule_Basic.yaml
  datadog/tests/resource_datadog_role_test.go
  datadog/tests/resource_datadog_security_monitoring_default_rule_test.go
Labels: changelog/no-changelog, ci/integrations

#1416 Remove duplicate custom-links building
  datadog/resource_datadog_dashboard.go
Labels: changelog/no-changelog

#1419 Bump datadog-api-client-go to v1.13.0
  go.mod
  go.sum
Labels: changelog/note, ci/integrations
