Repository DataDog/terraform-provider-datadog, pull requests merged in 2023-02, with the labels that each got.

#1749 [datadog_monitor] Add support for `notification_preset_name`
  datadog/data_source_datadog_monitor.go
  datadog/resource_datadog_monitor.go
  datadog/tests/cassettes/TestAccDatadogMonitor_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_BasicNoTreshold.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_BasicNoTreshold.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_Basic_float_int.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_Basic_float_int.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_UpdatedToRemoveTags.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_UpdatedToRemoveTags.yaml
  datadog/tests/resource_datadog_monitor_test.go
  docs/data-sources/monitor.md
  docs/resources/monitor.md
Labels: changelog/improvement

#1752 [datadog_service_account] fix migration compilation error
  datadog/resource_datadog_service_account.go
  go.mod
  go.sum
Labels: changelog/bugfix

#1750 [datadog_monitor_config_policy] Add monitor config policies resource and data source
  datadog/data_source_datadog_monitor_config_policies.go
  datadog/internal/utils/api_instances_helper.go
  datadog/provider.go
  datadog/resource_datadog_monitor_config_policy.go
  datadog/tests/cassettes/TestAccDatadogMonitorConfigPoliciesDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogMonitorConfigPoliciesDatasource.yaml
  datadog/tests/cassettes/TestAccDatadogMonitorConfigPolicy_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogMonitorConfigPolicy_Basic.yaml
  datadog/tests/data_source_datadog_monitor_config_policies_test.go
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_monitor_config_policy_test.go
  docs/data-sources/monitor_config_policies.md
  docs/resources/monitor_config_policy.md
  examples/data-sources/datadog_monitor_config_policies/data-source.tf
  examples/resources/datadog_monitor_config_policy/resource.tf
Labels: changelog/feature

#1748 [datadog_integration_gcp] Support enabling the CSPM integration
  datadog/resource_datadog_integration_gcp.go
  datadog/tests/cassettes/TestAccDatadogIntegrationGCP.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationGCP.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchiveGCS_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchiveGCS_basic.yaml
  datadog/tests/resource_datadog_integration_gcp_test.go
  docs/resources/integration_gcp.md
Labels: changelog/improvement

#1757 [datadog_monitor_config_policies] Fix flaky test due to order of resource creation
  datadog/tests/cassettes/TestAccDatadogMonitorConfigPoliciesDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogMonitorConfigPoliciesDatasource.yaml
  datadog/tests/data_source_datadog_monitor_config_policies_test.go
Labels: changelog/no-changelog

#1755 [datadog_synthetics_test] Prevent setting secure property on config variables of type global
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/bugfix

#1764 [provider] Upgrade Go client to v2.8.0
  docs/resources/dashboard.md
  docs/resources/security_monitoring_rule.md
  go.mod
  go.sum
Labels: changelog/no-changelog

#1770 [datadog_dashboards] Docs update for event_size field in dashboard list_stream_definition
  datadog/resource_datadog_dashboard.go
  docs/resources/dashboard.md
Labels: changelog/no-changelog

#1765 [provider] Bump `terraform-plugin-sdk/v2`to latest
  go.mod
  go.sum
Labels: changelog/note

#1774 [datadog_service_level_objectives] Update docs to clarify primary time frame fields
  datadog/resource_datadog_service_level_objective.go
  docs/resources/service_level_objective.md
Labels: changelog/no-changelog

#1777 [datadog_synthetics_test] add advanced scheduling
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_AdvancedScheduling.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_AdvancedScheduling.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
Labels: documentation, changelog/feature, resource/datadog_synthetics_test

#1779 [datadog_dashboard] Add run-workflow widget definition
  datadog/resource_datadog_dashboard.go
  datadog/tests/cassettes/TestAccDatadogDashboardRunWorkflow.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardRunWorkflow.yaml
  datadog/tests/cassettes/TestAccDatadogDashboardRunWorkflow_import.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardRunWorkflow_import.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_dashboard_run_workflow_test.go
  docs/resources/dashboard.md
Labels: changelog/improvement

#1781 [datadog_ip_ranges] Adds orchestrator to the resource
  datadog/data_source_datadog_ip_ranges.go
  datadog/tests/cassettes/TestAccDatadogIpRangesDatasource_existing.freeze
  datadog/tests/cassettes/TestAccDatadogIpRangesDatasource_existing.yaml
  datadog/tests/data_source_datadog_ip_ranges_test.go
  docs/data-sources/ip_ranges.md
  go.mod
  go.sum
Labels: changelog/improvement

#1785 [datadog_service_definition_yaml] Add ordering of contacts in state func
  datadog/resource_datadog_service_definition_yaml.go
  datadog/tests/cassettes/TestAccDatadogServiceDefinition_Order.freeze
  datadog/tests/cassettes/TestAccDatadogServiceDefinition_Order.yaml
  datadog/tests/resource_datadog_service_definition_yaml_test.go
Labels: changelog/bugfix

#1737 [datadog_sensitive_data_scanner_group] Generate Sensitive Data Scanner group resources
  datadog/internal/utils/api_instances_helper.go
  datadog/provider.go
  datadog/resource_datadog_sensitive_data_scanner_group.go
  datadog/tests/cassettes/TestAccDatadogSensitiveDataScannerGroup_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSensitiveDataScannerGroup_Basic.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_sensitive_data_scanner_group_test.go
  docs/resources/sensitive_data_scanner_group.md
  examples/resources/datadog_sensitive_data_scanner_group/import.sh
  examples/resources/datadog_sensitive_data_scanner_group/resource.tf
Labels: changelog/feature

#1786 Update docs for synthetics_test renotify_interval
  datadog/resource_datadog_synthetics_test_.go
  docs/resources/synthetics_test.md
Labels: changelog/no-changelog
