Repository DataDog/terraform-provider-datadog, pull requests merged in 2023-09, with the labels that each got.

#2091 [datadog_cloud_configuration_rule] Fix cloud configuration policy tests
  datadog/tests/cassettes/TestAccDatadogCloudConfigurationRule_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogCloudConfigurationRule_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogCloudConfigurationRule_Import.freeze
  datadog/tests/cassettes/TestAccDatadogCloudConfigurationRule_Import.yaml
  datadog/tests/cassettes/TestAccDatadogCloudConfigurationRule_MandatoryFieldsOnly.freeze
  datadog/tests/cassettes/TestAccDatadogCloudConfigurationRule_MandatoryFieldsOnly.yaml
  datadog/tests/resource_datadog_cloud_configuration_rule_test.go
Labels: changelog/no-changelog, ci/integrations

#2092 [datadog_downtimes_schedule] Fix downtimes schedule with monitor id identifier
  datadog/fwprovider/resource_datadog_downtime_schedule.go
  datadog/tests/cassettes/TestAccDowntimeScheduleBasicOneTimeWithMonitorID.freeze
  datadog/tests/cassettes/TestAccDowntimeScheduleBasicOneTimeWithMonitorID.yaml
  datadog/tests/resource_datadog_downtime_schedule_test.go
Labels: changelog/bugfix

#2090 [datadog_downtime_schedule] GA the resource
  datadog/fwprovider/resource_datadog_downtime_schedule.go
  datadog/resource_datadog_downtime.go
  docs/resources/downtime.md
  docs/resources/downtime_schedule.md
Labels: changelog/note, resource/datadog_downtime, resource/datadog_downtime_schedule

#2099 [datadog_provider] Bump datadog-api-client to `2.17.0`
  datadog/fwprovider/framework_provider.go
  datadog/tests/framework_provider_test.go
  go.mod
  go.sum
Labels: changelog/note

#2097 [datadog_sensitive_data_scanner_group] Avoid panic when nil returned
  datadog/resource_datadog_sensitive_data_scanner_group.go
  docs/resources/sensitive_data_scanner_group.md
Labels: changelog/bugfix

#2101 [datadog_synthetics_test] Add support for timings scope for response assertions
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
  go.mod
  go.sum
Labels: changelog/improvement

#2108 Skip AWS log collection tests which use `access_key_id`
  datadog/tests/resource_datadog_integration_aws_lambda_arn_test.go
  datadog/tests/resource_datadog_integration_aws_log_collection_test.go
Labels: changelog/no-changelog, ci/integrations

#2103 [datadog_dashboard] Support Formula and Function requests in heatmap widget
  datadog/resource_datadog_dashboard.go
  datadog/tests/cassettes/TestAccDatadogDashboardHeatMapFormulaAndFunction.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardHeatMapFormulaAndFunction.yaml
  datadog/tests/resource_datadog_dashboard_heatmap_test.go
  docs/resources/dashboard.md
  go.mod
  go.sum
Labels: changelog/improvement, editorial review

#2109 [datadog_integration_confluent_account] Add note about Confluent Account import
  docs/resources/integration_confluent_account.md
  examples/resources/datadog_integration_confluent_account/import.sh
Labels: changelog/no-changelog

#2110 [datadog_integration_aws_*] remove access_key_id note
  datadog/resource_datadog_integration_aws_lambda_arn.go
  datadog/resource_datadog_integration_aws_log_collection.go
  datadog/resource_datadog_integration_aws_tag_filter.go
  docs/resources/integration_aws_lambda_arn.md
  docs/resources/integration_aws_log_collection.md
  docs/resources/integration_aws_tag_filter.md
Labels: changelog/no-changelog

#2113 [datadog_restriction_policy_test] Fix error check test
  datadog/tests/cassettes/TestAccRestrictionPolicyInvalidInput.freeze
  datadog/tests/cassettes/TestAccRestrictionPolicyInvalidInput.yaml
  datadog/tests/resource_datadog_dashboard_heatmap_test.go
  datadog/tests/resource_datadog_restriction_policy_test.go
Labels: changelog/no-changelog

#2121 [integration_pagerduty_service_object] Fix docs
  datadog/resource_datadog_integration_pagerduty_service_object.go
Labels: changelog/no-changelog

#2124 [datadog_synthetics_test] Prevent setting empty values for rum settings
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/bugfix
