Repository DataDog/terraform-provider-datadog, pull requests merged in 2023-12, with the labels that each got.

#2202 [datadog_integration_azure] Migrate resource to framework
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_azure_integration.go
  datadog/provider.go
  datadog/resource_datadog_integration_azure.go
  datadog/tests/resource_datadog_integration_aws_test.go
  datadog/tests/resource_datadog_integration_azure_test.go
  datadog/tests/resource_datadog_integration_gcp_test.go
  datadog/tests/resource_datadog_logs_archive_test.go
  docs/resources/integration_azure.md
Labels: changelog/improvement

#2203 [datadog_integration_azure] Add resource_collection_enabled
  .github/CODEOWNERS
  datadog/fwprovider/resource_datadog_azure_integration.go
  datadog/tests/cassettes/TestAccDatadogIntegrationAzure.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAzure.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchiveAzure_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchiveAzure_basic.yaml
  docs/resources/dashboard.md
  docs/resources/integration_azure.md
  docs/resources/powerpack.md
  go.mod
  go.sum
Labels: changelog/feature

#2205 [dashboards] Support for powerpack widgets
  datadog/resource_datadog_dashboard.go
  datadog/tests/cassettes/TestAccDatadogDashboardPowerpack.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardPowerpack.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_dashboard_powerpack_test.go
  docs/resources/dashboard.md
  examples/resources/datadog_dashboard/resource.tf
Labels: changelog/feature

#2195 [datadog_security_monitoring_rule] Support for Application Security rule type
  datadog/resource_datadog_security_monitoring_rule.go
  docs/resources/security_monitoring_rule.md
  go.mod
  go.sum
Labels: changelog/feature

#2207 [datadog_ip_ranges] Fix test to actually test values in state
  datadog/tests/data_source_datadog_ip_ranges_test.go
Labels: changelog/no-changelog

#2201 [datadog_integration_aws_*] Validate AWS account ID and improve error handling
  datadog/internal/validators/validators.go
  datadog/resource_datadog_integration_aws.go
  datadog/resource_datadog_integration_aws_lambda_arn.go
  datadog/resource_datadog_integration_aws_log_collection.go
  datadog/resource_datadog_integration_aws_tag_filter.go
  datadog/resource_datadog_logs_archive.go
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSAccessKey.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSAccessKey.yaml
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSLambdaArnAccessKey.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSLambdaArnAccessKey.yaml
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSLogCollectionAccessKey.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSLogCollectionAccessKey.yaml
  datadog/tests/resource_datadog_integration_aws_lambda_arn_test.go
  datadog/tests/resource_datadog_integration_aws_log_collection_test.go
  datadog/tests/resource_datadog_integration_aws_test.go
Labels: changelog/note

#2223 Update Watchdog monitor example
  docs/guides/monitors.md
  examples/guides/watchdog_monitor.tf
Labels: documentation, changelog/no-changelog
