Repository DataDog/terraform-provider-datadog, pull requests merged in 2023-04, with the labels that each got.

#1850 [provider] Fix test clock initialization in framework provider
  datadog/tests/framework_provider_test.go
Labels: changelog/no-changelog

#1856 [datadog_synthetics_test] Handle advanced scheduling in browser tests
  datadog/resource_datadog_synthetics_test_.go
Labels: changelog/bugfix

#1845 [provider] Bump go version to `1.19` and `terraform-plugin-framework` to `1.2.0`
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/test_integration.yml
  go.mod
  go.sum
Labels: changelog/note

#1854 [datadog_dashboard_json] Handle continuous diff if `is_read_only` is not set
  datadog/resource_datadog_dashboard_json.go
  datadog/tests/cassettes/TestAccDatadogDashboardJSONNoDiff.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardJSONNoDiff.yaml
  datadog/tests/resource_datadog_dashboard_json_test.go
Labels: changelog/bugfix

#1859 [provider] Add helper to validate normalized tags
  datadog/internal/validators/tags_set_is_nomalized.go
Labels: changelog/no-changelog

#1847 [datadog_hosts] Add a host list datasource
  datadog/fwprovider/data_source_datadog_hosts.go
  datadog/fwprovider/framework_provider.go
  datadog/tests/cassettes/TestAccDatadogHostsDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogHostsDatasource.yaml
  datadog/tests/data_source_datadog_hosts_test.go
  datadog/tests/provider_test.go
  docs/data-sources/hosts.md
  examples/data-sources/datadog_hosts/data-source.tf
Labels: changelog/feature

#1861 [datadog_synthetics_test] Refactor options for Synthetics tests
  datadog/resource_datadog_synthetics_test_.go
Labels: changelog/improvement

#1868 Add small note in doc mentioning using framework for all new resources
  DEVELOPMENT.md
Labels: changelog/no-changelog

#1851 [datadog_integration_confluent] Add Confluent integration resources
  .github/CODEOWNERS
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_integration_confluent_account.go
  datadog/fwprovider/resource_datadog_integration_confluent_resource.go
  datadog/internal/utils/api_instances_helper.go
  datadog/internal/utils/utils.go
  datadog/internal/validators/tags_set_is_nomalized.go
  datadog/tests/cassettes/TestAccIntegrationConfluentAccountBasic.freeze
  datadog/tests/cassettes/TestAccIntegrationConfluentAccountBasic.yaml
  datadog/tests/cassettes/TestAccIntegrationConfluentAccountUpdated.freeze
  datadog/tests/cassettes/TestAccIntegrationConfluentAccountUpdated.yaml
  datadog/tests/cassettes/TestAccIntegrationConfluentResourceBasic.freeze
  datadog/tests/cassettes/TestAccIntegrationConfluentResourceBasic.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_integration_confluent_account_test.go
  datadog/tests/resource_datadog_integration_confluent_resource_test.go
  docs/resources/integration_confluent_account.md
  docs/resources/integration_confluent_resource.md
  examples/resources/datadog_integration_confluent_account/import.sh
  examples/resources/datadog_integration_confluent_account/resource.tf
  examples/resources/datadog_integration_confluent_resource/import.sh
  examples/resources/datadog_integration_confluent_resource/resource.tf
Labels: changelog/feature

#1878 [datadog_monitor] Fix dropped `hour_starts` field when value is zero
  datadog/resource_datadog_monitor.go
  datadog/tests/cassettes/TestAccDatadogMonitor_SchedulingOptionsHourStart.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_SchedulingOptionsHourStart.yaml
  datadog/tests/resource_datadog_monitor_test.go
Labels: changelog/bugfix

#1879 [datadog_service_level_objective] Fix edge case removing fields that are both optional and computed
  datadog/resource_datadog_service_level_objective.go
Labels: changelog/bugfix

#1883 [service_definition_yaml] Add v2.1 service definition example
  docs/resources/service_definition_yaml.md
  examples/resources/datadog_service_definition_yaml/resource.tf
Labels: changelog/improvement

#1884 [datadog_synthetics_test] Fix missing default value for browser variables
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_importBasic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/bugfix

#1885 [datadog_monitor] Fix panic on scheduling option with empty evaluation window
  datadog/resource_datadog_monitor.go
Labels: changelog/bugfix

#1887 [datadog_synthetics_test] Add no screenshot option to browser steps
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTestBrowserNewBrowserStep_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTestBrowserNewBrowserStep_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTestBrowserVariables_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTestBrowserVariables_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_importBasic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserMML_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserMML_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserUserLocator_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserUserLocator_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserUserLocator_NoElement.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserUserLocator_NoElement.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
Labels: changelog/feature

#1880 [datadog_synthetics_test] Remove required from jsonpath and xpath targetvalue fields
  datadog/resource_datadog_synthetics_test_.go
  docs/resources/synthetics_test.md
Labels: changelog/bugfix

#1890 [datadog_dashboard] re record test with tags
  datadog/tests/cassettes/TestDatadogDashListImport.freeze
  datadog/tests/cassettes/TestDatadogDashListImport.yaml
Labels: changelog/no-changelog

#1853 [datadog_integration_cloudflare_account] Add Cloudflare account resource
  .github/CODEOWNERS
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_integration_cloudflare_account.go
  datadog/internal/utils/api_instances_helper.go
  datadog/tests/cassettes/TestAccIntegrationCloudflareAccountBasic.freeze
  datadog/tests/cassettes/TestAccIntegrationCloudflareAccountBasic.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_integration_cloudflare_account_test.go
  docs/resources/integration_cloudflare_account.md
  examples/resources/datadog_integration_cloudflare_account/import.sh
  examples/resources/datadog_integration_cloudflare_account/resource.tf
Labels: changelog/feature

#1892 [datadog_api_key] Set ID in state and change error message back to original
  datadog/fwprovider/data_source_datadog_api_key.go
Labels: changelog/bugfix, ci/integrations

#1893 [datadog_synthetics_test] fix synthetics tests due to new validations
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/no-changelog

#1889 [datadog_service_definition_yaml] Fix contact handles to valid values
  datadog/tests/cassettes/TestAccDatadogServiceDefinition_Order.freeze
  datadog/tests/cassettes/TestAccDatadogServiceDefinition_Order.yaml
  datadog/tests/resource_datadog_service_definition_yaml_test.go
Labels: changelog/no-changelog
