Repository DataDog/terraform-provider-datadog, pull requests merged in 2023-08, with the labels that each got.

#2023 [datadog_downtime_schedule] Add support for Downtime V2
  datadog/fwprovider/data_source_datadog_team.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_downtime_schedule.go
  datadog/internal/planmodifiers/types_object_remove_block_modifier.go
  datadog/internal/utils/api_instances_helper.go
  datadog/internal/validators/time_format_validator.go
  datadog/tests/cassettes/TestAccDowntimeScheduleBasicOneTime.freeze
  datadog/tests/cassettes/TestAccDowntimeScheduleBasicOneTime.yaml
  datadog/tests/cassettes/TestAccDowntimeScheduleBasicRecurring.freeze
  datadog/tests/cassettes/TestAccDowntimeScheduleBasicRecurring.yaml
  datadog/tests/cassettes/TestAccDowntimeScheduleBasicRecurring_Import.freeze
  datadog/tests/cassettes/TestAccDowntimeScheduleBasicRecurring_Import.yaml
  datadog/tests/cassettes/TestAccDowntimeScheduleChanged.freeze
  datadog/tests/cassettes/TestAccDowntimeScheduleChanged.yaml
  datadog/tests/framework_provider_test.go
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_downtime_schedule_test.go
  docs/resources/downtime_schedule.md
  examples/resources/datadog_downtime_schedule/import.sh
  examples/resources/datadog_downtime_schedule/resource.tf
  go.mod
  go.sum
Labels: changelog/feature, resource/datadog_downtime_schedule

#2041 [datadog_sensitive_data_scanner_rule] Handle empty string for `excluded_namespaces`
  datadog/resource_datadog_sensitive_data_scanner_rule.go
Labels: changelog/bugfix

#2042 Add support for enriching fw schema type `SetNestedBlock`
  datadog/internal/fwutils/fw_enrich_schema.go
Labels: changelog/no-changelog

#2038 [datadog_dashboard_list] Migrate to tf framework
  datadog/data_source_datadog_dashboard_list.go
  datadog/fwprovider/data_source_datadog_dashboard_list.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_dashboard_list.go
  datadog/provider.go
  datadog/resource_datadog_dashboard_list.go
  datadog/tests/cassettes/TestAccDatadogDashboardListDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardListDatasource.yaml
  datadog/tests/cassettes/TestDatadogDashListImport.freeze
  datadog/tests/cassettes/TestDatadogDashListImport.yaml
  datadog/tests/cassettes/TestDatadogDashListInDashboard.freeze
  datadog/tests/cassettes/TestDatadogDashListInDashboard.yaml
  datadog/tests/cassettes/TestDatadogDashListInDashboardJSON.freeze
  datadog/tests/cassettes/TestDatadogDashListInDashboardJSON.yaml
  datadog/tests/data_source_datadog_dashboard_list_test.go
  datadog/tests/resource_datadog_dashboard_json_test.go
  datadog/tests/resource_datadog_dashboard_list_test.go
Labels: changelog/improvement, resource/datadog_dashboard_list

#2043 [data_sources] Relax unparsed object check for datasources
  datadog/data_source_datadog_cloud_workload_security_agent_rules.go
  datadog/data_source_datadog_dashboard.go
  datadog/data_source_datadog_integration_aws_logs_services.go
  datadog/data_source_datadog_logs_archives_order.go
  datadog/data_source_datadog_logs_indexes.go
  datadog/data_source_datadog_logs_indexes_order.go
  datadog/data_source_datadog_logs_pipelines.go
  datadog/data_source_datadog_monitor.go
  datadog/data_source_datadog_monitor_config_policies.go
  datadog/data_source_datadog_monitors.go
  datadog/data_source_datadog_permissions.go
  datadog/data_source_datadog_role.go
  datadog/data_source_datadog_roles.go
  datadog/data_source_datadog_security_monitoring_filters.go
  datadog/data_source_datadog_security_monitoring_rules.go
  datadog/data_source_datadog_service_level_objective.go
  datadog/data_source_datadog_service_level_objectives.go
  datadog/data_source_datadog_synthetics_global_variable.go
  datadog/data_source_datadog_synthetics_locations.go
  datadog/data_source_datadog_user.go
  datadog/fwprovider/data_source_datadog_dashboard_list.go
  datadog/fwprovider/data_source_datadog_ip_ranges.go
Labels: changelog/improvement

#2046 [datadog_dashboard] Fix handling of nil notify_by list
  datadog/resource_datadog_dashboard.go
Labels: changelog/bugfix

#2053 Use validators to mark objects as required
  datadog/fwprovider/resource_datadog_downtime_schedule.go
  datadog/fwprovider/resource_datadog_spans_metric.go
  datadog/internal/planmodifiers/types_object_required.go
Labels: changelog/improvement

#2056 [datadog_spans_metric] Normalize tag value
  datadog/fwprovider/resource_datadog_spans_metric.go
  datadog/internal/planmodifiers/types_string_tag_normalizer.go
Labels: changelog/bugfix

#2057 Fix tutorial link
  docs/index.md
  templates/index.md.tmpl
Labels: changelog/no-changelog

#2059 [datadog_integration_azure] Add app_service_plan_filters, cspm, and custom metrics
  datadog/resource_datadog_integration_azure.go
  datadog/tests/cassettes/TestAccDatadogIntegrationAzure.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAzure.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchiveAzure_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchiveAzure_basic.yaml
  datadog/tests/resource_datadog_integration_azure_test.go
  docs/resources/dashboard.md
  docs/resources/integration_azure.md
  examples/resources/datadog_integration_azure/resource.tf
  go.mod
  go.sum
Labels: changelog/feature, resource/datadog_integration_azure

#2063 [datadog_integration_aws_tag_filter] Prevent concurrency issues with mutex
  datadog/resource_datadog_integration_aws_tag_filter.go
Labels: changelog/bugfix

#2069 [datadog_sensitive_data_scanner_group] Add ordering constraints to tests
  datadog/tests/data_source_datadog_sensitive_data_scanner_group_order_test.go
  datadog/tests/resource_datadog_sensitive_data_scanner_group_order_test.go
Labels: changelog/no-changelog

#2071 [provider_test] spellcheck fixes and remove unused cassettes
  datadog/data_source_datadog_user.go
  datadog/tests/cassettes/TestAccDatadogIntegrationPagerduty_Migrate2ServiceObjects.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationPagerduty_Migrate2ServiceObjects.yaml
  datadog/tests/cassettes/TestAccDatadogIntegrationPagerduty_TwoServices.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationPagerduty_TwoServices.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchiveAzure_basicDeprecated.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchiveAzure_basicDeprecated.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchiveGCS_basicDeprecated.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchiveGCS_basicDeprecated.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchiveS3_basicDeprecated.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchiveS3_basicDeprecated.yaml
  datadog/tests/cassettes/TestAccDatadogMetricTagConfiguration_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogMetricTagConfiguration_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogMetricTagConfiguration_import.freeze
  datadog/tests/cassettes/TestAccDatadogMetricTagConfiguration_import.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_SilencedUpdateNoDiff.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_SilencedUpdateNoDiff.yaml
  datadog/tests/cassettes/TestAccDatadogOrderedDashboard.yaml
  datadog/tests/cassettes/TestAccDatadogRolesDatasourceExactMatch.freeze
  datadog/tests/cassettes/TestAccDatadogRolesDatasourceExactMatch.yaml
  datadog/tests/cassettes/TestAccDatadogScreenboard_update.freeze
  datadog/tests/cassettes/TestAccDatadogScreenboard_update.yaml
  datadog/tests/cassettes/TestAccDatadogServiceDefinitionBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicDeprecated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicDeprecated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedDeprecated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedDeprecated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsLocation_existing.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsLocation_existing.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTest.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTest.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestWithUrl.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestWithUrl.yaml
  datadog/tests/cassettes/TestAccDatadogTimeboard_update.freeze
  datadog/tests/cassettes/TestAccDatadogTimeboard_update.yaml
  datadog/tests/cassettes/TestAccDatatogSyntheticsGlobalVariable.freeze
  datadog/tests/cassettes/TestAccDatatogSyntheticsGlobalVariable.yaml
  datadog/tests/cassettes/TestAccDatatogSyntheticsLocation_existing.freeze
  datadog/tests/cassettes/TestAccDatatogSyntheticsLocation_existing.yaml
  datadog/tests/cassettes/TestAccDatatogSyntheticsTest.freeze
  datadog/tests/cassettes/TestAccDatatogSyntheticsTest.yaml
  datadog/tests/cassettes/TestAccDatatogSyntheticsTestWithUrl.freeze
  datadog/tests/cassettes/TestAccDatatogSyntheticsTestWithUrl.yaml
  datadog/tests/cassettes/TestDatadogApiKey_import.freeze
  datadog/tests/cassettes/TestDatadogApiKey_import.yaml
  datadog/tests/cassettes/TestDatadogApplicationKey_import.freeze
  datadog/tests/cassettes/TestDatadogApplicationKey_import.yaml
  datadog/tests/data_source_datadog_application_key_test.go
  datadog/tests/data_source_datadog_synthetics_global_variable_test.go
  datadog/tests/data_source_datadog_synthetics_locations_test.go
  datadog/tests/data_source_datadog_synthetics_test_test.go
  datadog/tests/resource_datadog_integration_fastly_account_test.go
  docs/data-sources/user.md
Labels: changelog/no-changelog

#2074 [provider] Bump datadog-api-client to 2.16.0
  go.mod
  go.sum
Labels: changelog/note

#2073 [datadog_dashboard_list] Remove resource from state on 404
  datadog/fwprovider/resource_datadog_dashboard_list.go
Labels: changelog/no-changelog

#2070 [datadog_team_permission] Add team permission setting resource
  datadog/fwprovider/data_source_datadog_dashboard_list.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_dashboard_list.go
  datadog/fwprovider/resource_datadog_team_permission_setting.go
  datadog/internal/planmodifiers/types_string_tag_normalizer.go
  datadog/tests/cassettes/TestAccTeamPermissionSettingBasic.freeze
  datadog/tests/cassettes/TestAccTeamPermissionSettingBasic.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_dashboard_list_test.go
  datadog/tests/resource_datadog_team_permission_setting_test.go
  docs/resources/team_permission_setting.md
  examples/resources/datadog_team_permission_setting/resource.tf
Labels: changelog/feature

#2068 [datadog_synthetics_tests] Retrieve synthetics test in datasource by making 2 api calls
  datadog/data_source_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsTest.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTest.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestWithUrl.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestWithUrl.yaml
Labels: changelog/improvement

#2085 [datadog_integration_azure] Fix docs for app_service_plan_filters
  datadog/resource_datadog_integration_azure.go
  docs/resources/integration_azure.md
Labels: documentation, changelog/no-changelog
