Repository DataDog/terraform-provider-datadog, pull requests merged in 2023-03, with the labels that each got.

#1793 Clarify logs index order name
  docs/resources/logs_index_order.md
  examples/data-sources/datadog_logs_indexes_order/data-source.tf
  examples/resources/datadog_logs_index_order/import.sh
Labels: changelog/no-changelog

#1738 [datadog_sensitive_data_scanner_rule] Create Sensitive Data Scanner rule resources
  datadog/data_source_datadog_sensitive_data_scanner_standard_pattern.go
  datadog/provider.go
  datadog/resource_datadog_sensitive_data_scanner_group.go
  datadog/resource_datadog_sensitive_data_scanner_rule.go
  datadog/tests/cassettes/TestAccDatadogStandardPatternDatasourceErrorMultiple.freeze
  datadog/tests/cassettes/TestAccDatadogStandardPatternDatasourceErrorMultiple.yaml
  datadog/tests/cassettes/TestAccDatadogStandardPatternDatasourceErrorNotFound.freeze
  datadog/tests/cassettes/TestAccDatadogStandardPatternDatasourceErrorNotFound.yaml
  datadog/tests/cassettes/TestAccDatadogStandardPatternDatasourceNameFilter.freeze
  datadog/tests/cassettes/TestAccDatadogStandardPatternDatasourceNameFilter.yaml
  datadog/tests/cassettes/TestAccSensitiveDataScannerRuleBasic.freeze
  datadog/tests/cassettes/TestAccSensitiveDataScannerRuleBasic.yaml
  datadog/tests/cassettes/TestAccSensitiveDataScannerRuleWithStandardPattern.freeze
  datadog/tests/cassettes/TestAccSensitiveDataScannerRuleWithStandardPattern.yaml
  datadog/tests/data_source_datadog_sensitive_data_scanner_standard_pattern_test.go
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_sensitive_data_scanner_rule_test.go
  docs/data-sources/sensitive_data_scanner_standard_pattern.md
  docs/resources/sensitive_data_scanner_group.md
  docs/resources/sensitive_data_scanner_rule.md
  examples/resources/datadog_sensitive_data_scanner_rule/import.sh
  examples/resources/datadog_sensitive_data_scanner_rule/resource.tf
Labels: changelog/feature

#1796 [datadog_security_monitoring_rule] Don't cast nil values in `group_by_fields` or `distinct_fields`
  datadog/internal/validators/validators.go
  datadog/resource_datadog_security_monitoring_rule.go
Labels: changelog/bugfix

#1794 Fix failing tests due to new downtime scope validation
  datadog/tests/cassettes/TestAccDatadogDowntime_DiffStart.freeze
  datadog/tests/cassettes/TestAccDatadogDowntime_DiffStart.yaml
  datadog/tests/cassettes/TestAccDatadogDowntime_RRule.freeze
  datadog/tests/cassettes/TestAccDatadogDowntime_RRule.yaml
  datadog/tests/cassettes/TestAccDatadogDowntime_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogDowntime_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogDowntime_WeekDayRecurring.freeze
  datadog/tests/cassettes/TestAccDatadogDowntime_WeekDayRecurring.yaml
  datadog/tests/resource_datadog_downtime_test.go
Labels: changelog/no-changelog

#1799 [datadog_logs_index_order] Make name optional and computed
  datadog/resource_datadog_logs_index_order.go
  docs/resources/logs_index_order.md
Labels: changelog/bugfix

#1791 Cleanup transport and remove deprecated package usage
  datadog/internal/transport/custom_transport.go
  datadog/internal/utils/custom_request.go
  datadog/tests/provider_test.go
Labels: changelog/no-changelog, ci/integrations

#1803 [Provider] Bump datadog api client to 2.10.0
  docs/resources/dashboard.md
  go.mod
  go.sum
Labels: changelog/note

#1811 [datadog_downtime] Ignore start/end comparison on recurring downtimes
  datadog/resource_datadog_downtime.go
Labels: changelog/bugfix

#1814 [datadog_monitor] Make search required for f&f monitors
  datadog/resource_datadog_monitor.go
  docs/resources/monitor.md
Labels: changelog/bugfix

#1813 [datadog_synthetics_test] Allow empty values for service for Synthetics grpc tests
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsGRPCTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGRPCTest_Basic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/bugfix

#1788 [datadog_ip_allowlist] Support IP allowlist management in terraform
  datadog/internal/utils/api_instances_helper.go
  datadog/provider.go
  datadog/resource_datadog_ip_allowlist.go
  datadog/tests/cassettes/TestAccDatadogIPAllowlist_CreateUpdate.freeze
  datadog/tests/cassettes/TestAccDatadogIPAllowlist_CreateUpdate.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_ip_allowlist_test.go
  docs/resources/ip_allowlist.md
  go.mod
  go.sum
Labels: changelog/feature, ci/integrations, aaa-access

#1815 [datadog_synthetics/security_monitoring_rule] Add time units to synthetics and security monitoring rules
  datadog/resource_datadog_security_monitoring_rule.go
  datadog/resource_datadog_synthetics_test_.go
  docs/resources/security_monitoring_rule.md
  docs/resources/synthetics_test.md
Labels: changelog/no-changelog

#1818 [datadog_sensitive_data_scanner] Add mutex to SDS resource
  datadog/resource_datadog_sensitive_data_scanner_group.go
  datadog/resource_datadog_sensitive_data_scanner_rule.go
Labels: changelog/bugfix, ci/integrations

#1800 [datadog_logs_custom_pipeline] Add reference table logs processor
  datadog/resource_datadog_logs_custom_pipeline.go
  datadog/tests/cassettes/TestAccDatadogLogsPipeline_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipeline_basic.yaml
  datadog/tests/cassettes/TestAccDatadogLogsPipeline_import.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipeline_import.yaml
  datadog/tests/cassettes/TestAccDatadogLogsPipelinesDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipelinesDatasource.yaml
  datadog/tests/cassettes/TestAccDatadogLogsPipelinesDatasourceReadonly.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipelinesDatasourceReadonly.yaml
  datadog/tests/data_source_datadog_logs_pipelines_test.go
  datadog/tests/resource_datadog_logs_custom_pipeline_test.go
  docs/resources/logs_custom_pipeline.md
Labels: changelog/improvement

#1819 [datadog_metric_tag_configuration] Fix tag validation for metric tags configs
  datadog/resource_datadog_metric_tag_configuration.go
Labels: changelog/bugfix

#1827 [datadog_security_monitoring_default_rule] Update deprecation warning for security monitoring rule
  datadog/resource_datadog_security_monitoring_default_rule.go
Labels: changelog/no-changelog

#1834 [datadog_security_monitoring_default_rule] Add spaces to deprecation message
  datadog/resource_datadog_security_monitoring_default_rule.go
Labels: changelog/no-changelog

#1840 [datadog_monitor] remove Beta notice from notify_by Monitor resource
  datadog/resource_datadog_monitor.go
  docs/resources/monitor.md
Labels: changelog/improvement

#1838 [datadog_dashboard] Safeguard against empty formula definitions
  datadog/resource_datadog_dashboard.go
Labels: changelog/bugfix

#1837 [datadog_synthetics_test] Check error when building token API authentication
  datadog/resource_datadog_synthetics_test_.go
Labels: changelog/bugfix

#1835 [datadog_dashboard] Add sort block in slo_list_definition
  datadog/resource_datadog_dashboard.go
  datadog/tests/cassettes/TestAccDatadogDashboardSloList.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardSloList.yaml
  datadog/tests/cassettes/TestAccDatadogDashboardSloList_import.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardSloList_import.yaml
  datadog/tests/resource_datadog_dashboard_slo_list_test.go
  docs/resources/dashboard.md
Labels: changelog/improvement

#1842 [datadog_dashboard] Handle empty section in template variables
  datadog/resource_datadog_dashboard.go
Labels: changelog/bugfix

#1833 [datadog_service_definition_yaml] Add support for v2.1 schema of service catalog
  datadog/resource_datadog_service_definition_yaml.go
  datadog/tests/cassettes/TestAccDatadogServiceDefinition_BasicV2_1.freeze
  datadog/tests/cassettes/TestAccDatadogServiceDefinition_BasicV2_1.yaml
  datadog/tests/resource_datadog_service_definition_yaml_test.go
Labels: changelog/feature

#1843 Cleanup framework and env vars
  datadog/fwprovider/data_source_datadog_ip_ranges.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_api_key.go
  datadog/internal/utils/utils.go
  datadog/provider.go
  datadog/tests/cassettes/TestAccDatadogServiceDefinition_BasicV2_1.freeze
  datadog/tests/cassettes/TestAccDatadogServiceDefinition_BasicV2_1.yaml
  datadog/tests/framework_provider_test.go
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_api_key_test.go
  datadog/tests/resource_datadog_integration_slack_channel_test.go
  main.go
Labels: changelog/no-changelog
