Repository DataDog/terraform-provider-datadog, pull requests merged in 2023-11, with the labels that each got.

#2157 [datadog_powerpacks] Implement support for basic widgets
  datadog/internal/utils/api_instances_helper.go
  datadog/provider.go
  datadog/resource_datadog_powerpack.go
  datadog/tests/cassettes/TestAccDatadogPowerpackAlertGraph.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackAlertGraph.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackCheckStatus.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackCheckStatus.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackFreeText.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackFreeText.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackIFrame.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackIFrame.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackImage.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackImage.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackNote.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackNote.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackServicemap.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackServicemap.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpack_update.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpack_update.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_powerpack_alert_graph_test.go
  datadog/tests/resource_datadog_powerpack_check_status_test.go
  datadog/tests/resource_datadog_powerpack_free_text_test.go
  datadog/tests/resource_datadog_powerpack_iframe_test.go
  datadog/tests/resource_datadog_powerpack_image_test.go
  datadog/tests/resource_datadog_powerpack_note_test.go
  datadog/tests/resource_datadog_powerpack_servicemap_test.go
  datadog/tests/resource_datadog_powerpack_test.go
  docs/resources/powerpack.md
Labels: changelog/feature, editorial review

#2171 [datadog_powerpack] comment out unsupported to cleanup docs
  datadog/resource_datadog_powerpack.go
  docs/resources/powerpack.md
Labels: changelog/no-changelog

#2172 [data_source_datadog_service_level_objectives] Add ability to query slo with multiple tags
  datadog/data_source_datadog_service_level_objectives.go
  datadog/tests/cassettes/TestAccDatadogServiceLevelObjectiveDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogServiceLevelObjectiveDatasource.yaml
  datadog/tests/cassettes/TestAccDatadogServiceLevelObjectivesDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogServiceLevelObjectivesDatasource.yaml
  datadog/tests/data_source_datadog_service_level_objectives_test.go
  docs/data-sources/service_level_objectives.md
Labels: changelog/improvement, under_review

#2175 YAML typo In service definition guide and example
  docs/resources/service_definition_yaml.md
  examples/resources/datadog_service_definition_yaml/resource.tf
Labels: changelog/no-changelog

#2178 [datadog_service_definition_yaml] Keep `ci-pipeline-fingerprints` sorted in state
  datadog/resource_datadog_service_definition_yaml.go
Labels: changelog/bugfix

#2173 [datadog_powerpack] set reasonable default group widget layout value
  datadog/resource_datadog_powerpack.go
  datadog/tests/cassettes/TestAccDatadogPowerpackAlertGraph.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackAlertGraph.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackCheckStatus.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackCheckStatus.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackFreeText.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackFreeText.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackIFrame.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackIFrame.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackImage.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackImage.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackNote.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackNote.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackServicemap.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackServicemap.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpack_update.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpack_update.yaml
  docs/resources/powerpack.md
Labels: changelog/bugfix

#2158 [datadog_powerpacks] Implement support for live span and more widgets
  datadog/resource_datadog_powerpack.go
  datadog/tests/cassettes/TestAccDatadogPowerpackAlertValue.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackAlertValue.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackChange.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackChange.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackEventStream.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackEventStream.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackEventTimeline.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackEventTimeline.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackManageStatus.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackManageStatus.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackQueryValue.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackQueryValue.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackToplist.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackToplist.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackTraceService.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackTraceService.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpack_update.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpack_update.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_powerpack_alert_value_test.go
  datadog/tests/resource_datadog_powerpack_change_test.go
  datadog/tests/resource_datadog_powerpack_event_stream_test.go
  datadog/tests/resource_datadog_powerpack_event_timeline_test.go
  datadog/tests/resource_datadog_powerpack_manage_status_test.go
  datadog/tests/resource_datadog_powerpack_query_value_test.go
  datadog/tests/resource_datadog_powerpack_test.go
  datadog/tests/resource_datadog_powerpack_toplist_test.go
  datadog/tests/resource_datadog_powerpack_trace_service_test.go
  docs/resources/powerpack.md
Labels: changelog/feature

#2181 [repository] update min terraform version in testing
  .github/workflows/test.yml
Labels: changelog/no-changelog

#2179 [datadog_synthetics_test] Put schema of file field in examples
  datadog/resource_datadog_synthetics_test_.go
  docs/resources/synthetics_test.md
  examples/resources/datadog_synthetics_test/resource.tf
Labels: changelog/no-changelog

#2137 [apm_retention_filters] Add resources and datasource
  datadog/fwprovider/data_source_datadog_apm_retention_filters_order.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_apm_retention_filter.go
  datadog/fwprovider/resource_datadog_apm_retention_filter_order.go
  datadog/internal/utils/api_instances_helper.go
  datadog/internal/validators/validators.go
  datadog/internal/validators/validators_test.go
  datadog/tests/cassettes/TestAccApmRetentionFilter.freeze
  datadog/tests/cassettes/TestAccApmRetentionFilter.yaml
  datadog/tests/cassettes/TestAccDatadogApmRetentionFilterOrder.freeze
  datadog/tests/cassettes/TestAccDatadogApmRetentionFilterOrder.yaml
  datadog/tests/cassettes/TestAccDatadogApmRetentionFiltersOrderDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogApmRetentionFiltersOrderDatasource.yaml
  datadog/tests/data_source_datadog_apm_retention_filters_order_test.go
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_apm_retention_filter_order_test.go
  datadog/tests/resource_datadog_apm_retention_filter_test.go
  docs/data-sources/apm_retention_filters_order.md
  docs/resources/apm_retention_filter.md
  docs/resources/apm_retention_filter_order.md
  examples/data-sources/datadog_apm_retention_filters_order/data-source.tf
  examples/resources/datadog_apm_retention_filter/import.sh
  examples/resources/datadog_apm_retention_filter/resource.tf
  examples/resources/datadog_apm_retention_filter_order/import.sh
  examples/resources/datadog_apm_retention_filter_order/resource.tf
Labels: changelog/feature

#2177 [datadog_monitor] Add custom_schedule fields
  datadog/data_source_datadog_monitor.go
  datadog/resource_datadog_monitor.go
  datadog/tests/cassettes/TestAccDatadogMonitor_SchedulingOptions.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_SchedulingOptions.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_SchedulingOptionsCustomSchedule.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_SchedulingOptionsCustomSchedule.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_SchedulingOptionsCustomScheduleNoStart.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_SchedulingOptionsCustomScheduleNoStart.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_SchedulingOptionsHourStart.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_SchedulingOptionsHourStart.yaml
  datadog/tests/resource_datadog_monitor_test.go
  docs/data-sources/monitor.md
  docs/resources/monitor.md
Labels: changelog/improvement

#2184 [datadog_powerpack] Revert Powerpack commits
  datadog/internal/utils/api_instances_helper.go
  datadog/provider.go
  datadog/resource_datadog_powerpack.go
  datadog/tests/cassettes/TestAccDatadogPowerpackAlertGraph.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackAlertGraph.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackAlertValue.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackAlertValue.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackChange.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackChange.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackCheckStatus.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackCheckStatus.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackEventStream.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackEventStream.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackEventTimeline.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackEventTimeline.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackFreeText.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackFreeText.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackIFrame.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackIFrame.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackImage.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackImage.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackManageStatus.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackManageStatus.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackNote.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackNote.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackQueryValue.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackQueryValue.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackServicemap.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackServicemap.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackToplist.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackToplist.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackTraceService.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackTraceService.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpack_update.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpack_update.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_powerpack_alert_graph_test.go
  datadog/tests/resource_datadog_powerpack_alert_value_test.go
  datadog/tests/resource_datadog_powerpack_change_test.go
  datadog/tests/resource_datadog_powerpack_check_status_test.go
  datadog/tests/resource_datadog_powerpack_event_stream_test.go
  datadog/tests/resource_datadog_powerpack_event_timeline_test.go
  datadog/tests/resource_datadog_powerpack_free_text_test.go
  datadog/tests/resource_datadog_powerpack_iframe_test.go
  datadog/tests/resource_datadog_powerpack_image_test.go
  datadog/tests/resource_datadog_powerpack_manage_status_test.go
  datadog/tests/resource_datadog_powerpack_note_test.go
  datadog/tests/resource_datadog_powerpack_query_value_test.go
  datadog/tests/resource_datadog_powerpack_servicemap_test.go
  datadog/tests/resource_datadog_powerpack_test.go
  datadog/tests/resource_datadog_powerpack_toplist_test.go
  datadog/tests/resource_datadog_powerpack_trace_service_test.go
  docs/resources/powerpack.md
Labels: changelog/no-changelog

#1949 [datadog_metric_tag_configuration] Adds exclude_tags_mode; updates include_percentiles
  datadog/resource_datadog_metric_tag_configuration.go
  datadog/tests/cassettes/TestAccDatadogMetricTagConfiguration_Error.freeze
  datadog/tests/resource_datadog_metric_tag_configuration_test.go
  docs/resources/metric_tag_configuration.md
  examples/resources/datadog_metric_tag_configuration/resource.tf
  go.mod
  go.sum
Labels: changelog/feature

#2189 [datadog_dashboard] Don't crash on empty group_by in widgets
  datadog/resource_datadog_dashboard.go
Labels: changelog/bugfix
