Repository DataDog/terraform-provider-datadog, pull requests merged in 2023-07, with the labels that each got.

#1989 [datadog_synthetics_test] Allow synthetics web basicauth without password set
  datadog/resource_datadog_synthetics_test_.go
Labels: changelog/bugfix

#1957 [restriction_policy] Add restriction policy resource
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_restriction_policy.go
  datadog/internal/utils/api_instances_helper.go
  datadog/tests/cassettes/TestAccRestrictionPolicyBasic.freeze
  datadog/tests/cassettes/TestAccRestrictionPolicyBasic.yaml
  datadog/tests/cassettes/TestAccRestrictionPolicyInvalidInput.freeze
  datadog/tests/cassettes/TestAccRestrictionPolicyInvalidInput.yaml
  datadog/tests/cassettes/TestAccRestrictionPolicyUpdate.freeze
  datadog/tests/cassettes/TestAccRestrictionPolicyUpdate.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_restriction_policy_test.go
  docs/resources/restriction_policy.md
  examples/resources/datadog_restriction_policy/import.sh
  examples/resources/datadog_restriction_policy/resource.tf
Labels: changelog/feature

#1992 Add concurrency section to tests action
  .github/workflows/test.yml
Labels: changelog/no-changelog

#1993 [data_source_datadog_synthetics_test] Allow datasource to take a test URL as well as id
  datadog/data_source_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatatogSyntheticsTestWithUrl.freeze
  datadog/tests/cassettes/TestAccDatatogSyntheticsTestWithUrl.yaml
  datadog/tests/data_source_datadog_synthetics_test_test.go
  docs/data-sources/synthetics_test.md
Labels: changelog/improvement

#1994 Cache terraform executable in integration tests
  .github/workflows/test.yml
  .github/workflows/test_integration.yml
Labels: changelog/no-changelog, ci/integrations

#1997 [datadog_dashboard] Add a new field additional_query_filters to Formula and Function SLO query
  LICENSE-3rdparty.csv
  datadog/resource_datadog_dashboard.go
  datadog/tests/cassettes/TestAccDatadogDashboardFormula.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardFormula.yaml
  datadog/tests/cassettes/TestAccDatadogDashboardFormula_import.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardFormula_import.yaml
  datadog/tests/resource_datadog_dashboard_timeseries_test.go
  docs/resources/dashboard.md
  go.mod
  go.sum
Labels: changelog/improvement

#1995 [restriction_policy] Update restriction_policy resource documentation
  datadog/fwprovider/resource_datadog_restriction_policy.go
  docs/resources/restriction_policy.md
Labels: documentation, changelog/improvement

#2000 Check exit code instead of log output during terraform fmt
  scripts/fmtcheck.sh
Labels: changelog/no-changelog

#2008 [datadog_service_definition] support backstage schema validation v2
  datadog/resource_datadog_service_definition_yaml.go
Labels: changelog/feature

#2006 [datadog_dashboard] Support overlay display type in dashboard widget definition requests
  datadog/tests/cassettes/TestAccDatadogDashboardFormula.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardFormula.yaml
  datadog/tests/cassettes/TestAccDatadogDashboardFormula_import.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardFormula_import.yaml
  datadog/tests/cassettes/TestAccIntegrationConfluentResourceBasic.freeze
  datadog/tests/cassettes/TestAccIntegrationConfluentResourceBasic.yaml
  datadog/tests/resource_datadog_dashboard_timeseries_test.go
  docs/resources/dashboard.md
  examples/resources/datadog_dashboard/resource.tf
  go.mod
  go.sum
Labels: changelog/improvement

#2009 [datadog_logs_archive] Fix Azure logs archive test
  datadog/tests/cassettes/TestAccDatadogLogsArchiveAzure_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchiveAzure_basic.yaml
  datadog/tests/resource_datadog_logs_archive_test.go
Labels: changelog/no-changelog

#2012 [datadog_dashboard_json] Check if widgets are valid while casting
  datadog/resource_datadog_dashboard_json.go
Labels: changelog/bugfix

#2013 [provider] Bump Datadog Go SDK to 2.15.0
  go.mod
  go.sum
Labels: changelog/no-changelog

#2016 Cleanup CODEOWNERS file
  .github/CODEOWNERS
Labels: changelog/no-changelog

#2017 [repo] Use Github issue forms instead of issue templates
  .github/ISSUE_TEMPLATE/FR_FORM.yml
  .github/ISSUE_TEMPLATE/ISSUE_FORM.yml
Labels: changelog/no-changelog

#2020 [repo] Remove old issue template and add terraform cli input
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/ISSUE_FORM.yml
Labels: changelog/no-changelog

#2021 Add Datadog links to template chooser
  .github/ISSUE_TEMPLATE/config.yml
Labels: changelog/no-changelog

#2015 [datadog_cloud_configuration_rule] Added filter field
  datadog/resource_datadog_cloud_configuration_rule.go
  datadog/tests/cassettes/TestAccDatadogCloudConfigurationRule_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogCloudConfigurationRule_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogCloudConfigurationRule_Import.freeze
  datadog/tests/cassettes/TestAccDatadogCloudConfigurationRule_Import.yaml
  datadog/tests/cassettes/TestAccDatadogCloudConfigurationRule_MandatoryFieldsOnly.freeze
  datadog/tests/cassettes/TestAccDatadogCloudConfigurationRule_MandatoryFieldsOnly.yaml
  datadog/tests/resource_datadog_cloud_configuration_rule_test.go
  docs/resources/cloud_configuration_rule.md
Labels: changelog/feature

#2026 [repo] Fix docs code ownership
  .github/CODEOWNERS
Labels: changelog/no-changelog

#2029 [datadog_restriction_policy] remove version mention from docs
  datadog/fwprovider/resource_datadog_restriction_policy.go
  docs/resources/restriction_policy.md
Labels: changelog/no-changelog

#2030 Bump go version to `1.20` and other terraform package versions
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/test_integration.yml
  docs/data-sources/api_key.md
  docs/data-sources/application_key.md
  docs/data-sources/cloud_workload_security_agent_rules.md
  docs/data-sources/dashboard.md
  docs/data-sources/dashboard_list.md
  docs/data-sources/hosts.md
  docs/data-sources/integration_aws_logs_services.md
  docs/data-sources/integration_aws_namespace_rules.md
  docs/data-sources/ip_ranges.md
  docs/data-sources/logs_archives_order.md
  docs/data-sources/logs_indexes.md
  docs/data-sources/logs_indexes_order.md
  docs/data-sources/logs_pipelines.md
  docs/data-sources/monitor.md
  docs/data-sources/monitor_config_policies.md
  docs/data-sources/monitors.md
  docs/data-sources/permissions.md
  docs/data-sources/role.md
  docs/data-sources/roles.md
  docs/data-sources/rum_application.md
  docs/data-sources/security_monitoring_filters.md
  docs/data-sources/security_monitoring_rules.md
  docs/data-sources/sensitive_data_scanner_group_order.md
  docs/data-sources/sensitive_data_scanner_standard_pattern.md
  docs/data-sources/service_account.md
  docs/data-sources/service_level_objective.md
  docs/data-sources/service_level_objectives.md
  docs/data-sources/synthetics_global_variable.md
  docs/data-sources/synthetics_locations.md
  docs/data-sources/synthetics_test.md
  docs/data-sources/team.md
  docs/data-sources/team_memberships.md
  docs/data-sources/user.md
  docs/resources/child_organization.md
  docs/resources/integration_opsgenie_service_object.md
  docs/resources/integration_pagerduty.md
  docs/resources/integration_pagerduty_service_object.md
  docs/resources/ip_allowlist.md
  docs/resources/monitor_config_policy.md
  go.mod
  go.sum
Labels: changelog/note

#2035 Deduplicate Github action jobs
  .github/workflows/test.yml
Labels: changelog/no-changelog
