Repository DataDog/terraform-provider-datadog, pull requests merged in 2023-06, with the labels that each got.

#1947 [datadog_team_membership] Fix team membership call loop
  datadog/fwprovider/resource_datadog_team_membership.go
Labels: changelog/no-changelog

#1941 [datadog_dashboard] Add sort block to Dashboard list_stream query block
  datadog/resource_datadog_dashboard.go
  datadog/tests/cassettes/TestAccDatadogDashboardListStreamEvents.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardListStreamEvents.yaml
  datadog/tests/resource_datadog_dashboard_list_stream_test.go
  docs/resources/dashboard.md
Labels: changelog/improvement

#1948 [datadog_synthetics_test] Fix segfault on uninitialized basic auth fields
  datadog/resource_datadog_synthetics_test_.go
Labels: changelog/bugfix

#1946 [datadog_team] Add datadog team data sources
  .github/CODEOWNERS
  datadog/fwprovider/data_source_datadog_team.go
  datadog/fwprovider/data_source_datadog_team_memberships.go
  datadog/fwprovider/framework_provider.go
  datadog/tests/cassettes/TestAccDatadogTeamDatasourceBasic.freeze
  datadog/tests/cassettes/TestAccDatadogTeamDatasourceBasic.yaml
  datadog/tests/cassettes/TestAccDatadogTeamMembershipsDatasourceBasic.freeze
  datadog/tests/cassettes/TestAccDatadogTeamMembershipsDatasourceBasic.yaml
  datadog/tests/data_source_datadog_team_memberships_test.go
  datadog/tests/data_source_datadog_team_test.go
  datadog/tests/provider_test.go
  docs/data-sources/team.md
  docs/data-sources/team_memberships.md
  examples/data-sources/datadog_team/data-source.tf
  examples/data-sources/datadog_team_memberships/data-source.tf
Labels: changelog/feature

#1951 [datadog_hosts] Fix hosts datasource test returning no results
  datadog/tests/cassettes/TestAccDatadogHostsDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogHostsDatasource.yaml
  datadog/tests/data_source_datadog_hosts_test.go
Labels: changelog/no-changelog

#1953 Update Github Actions
  .github/workflows/changelog.yaml
  .github/workflows/prepare_release.yml
  .github/workflows/release.yml
Labels: changelog/no-changelog

#1956 [datadog_synthetics_test] Fix for optional fields in synthetics oauth
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/bugfix

#1965 [datadog_integration_gcp] Mark resource as deprecated
  datadog/resource_datadog_integration_gcp.go
  docs/resources/integration_gcp.md
Labels: changelog/note

#1962 [provider] Add datasource wrapper
  datadog/fwprovider/data_source_datadog_api_key.go
  datadog/fwprovider/data_source_datadog_hosts.go
  datadog/fwprovider/data_source_datadog_integration_aws_namespace_rules.go
  datadog/fwprovider/data_source_datadog_ip_ranges.go
  datadog/fwprovider/data_source_datadog_sensitive_data_scanner_group_order.go
  datadog/fwprovider/data_source_datadog_team.go
  datadog/fwprovider/data_source_datadog_team_memberships.go
  datadog/fwprovider/framework_provider.go
Labels: changelog/note

#1955 [datadog_service_account_application_key] Add service_account_application_key resource and service_account data source
  .github/CODEOWNERS
  datadog/fwprovider/data_source_datadog_service_account.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_service_account_application_key.go
  datadog/tests/cassettes/TestAccDatadogServiceAccountDatasourceError.freeze
  datadog/tests/cassettes/TestAccDatadogServiceAccountDatasourceError.yaml
  datadog/tests/cassettes/TestAccDatadogServiceAccountDatasourceMatchFilter.freeze
  datadog/tests/cassettes/TestAccDatadogServiceAccountDatasourceMatchFilter.yaml
  datadog/tests/cassettes/TestAccDatadogServiceAccountDatasourceMatchID.freeze
  datadog/tests/cassettes/TestAccDatadogServiceAccountDatasourceMatchID.yaml
  datadog/tests/cassettes/TestAccServiceAccountApplicationKeyBasic.freeze
  datadog/tests/cassettes/TestAccServiceAccountApplicationKeyBasic.yaml
  datadog/tests/cassettes/TestAccServiceAccountApplicationKeyBasic_import.freeze
  datadog/tests/cassettes/TestAccServiceAccountApplicationKeyBasic_import.yaml
  datadog/tests/data_source_datadog_service_account_test.go
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_service_account_application_key_test.go
  docs/data-sources/service_account.md
  docs/resources/service_account_application_key.md
  examples/resources/datadog_service_account_application_key/import.sh
  examples/resources/datadog_service_account_application_key/resource.tf
Labels: changelog/feature

#1970 [datadog_monitor] Fix unsetting of `restricted_roles`
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_downtime.go
  datadog/resource_datadog_monitor.go
  datadog/tests/cassettes/TestAccDatadogDowntime_BasicWithMonitor.freeze
  datadog/tests/cassettes/TestAccDatadogDowntime_BasicWithMonitor.yaml
  datadog/tests/cassettes/TestAccDatadogDowntime_BasicWithMonitorTags.freeze
  datadog/tests/cassettes/TestAccDatadogDowntime_BasicWithMonitorTags.yaml
  datadog/tests/cassettes/TestAccDatadogMonitorDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogMonitorDatasource.yaml
  datadog/tests/cassettes/TestAccDatadogMonitorServiceCheck_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogMonitorServiceCheck_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_BasicNoTreshold.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_BasicNoTreshold.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_Basic_float_int.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_Basic_float_int.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_ComposeWithSyntheticsTest.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_ComposeWithSyntheticsTest.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_FormulaFunction.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_FormulaFunction.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_Log.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_Log.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_LogMultiAlert.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_LogMultiAlert.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_NoThresholdWindows.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_NoThresholdWindows.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_RestrictedRoles.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_RestrictedRoles.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_SchedulingOptions.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_SchedulingOptions.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_SchedulingOptionsHourStart.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_SchedulingOptionsHourStart.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_ThresholdWindows.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_ThresholdWindows.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_TrimWhitespace.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_TrimWhitespace.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_UpdatedToRemoveTags.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_UpdatedToRemoveTags.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_ZeroDelay.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_ZeroDelay.yaml
  datadog/tests/cassettes/TestAccDatadogMonitorsDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogMonitorsDatasource.yaml
  datadog/tests/cassettes/TestDatadogMonitor_import.freeze
  datadog/tests/cassettes/TestDatadogMonitor_import.yaml
  datadog/tests/cassettes/TestDatadogMonitor_importNoDataTimeFrame.freeze
  datadog/tests/cassettes/TestDatadogMonitor_importNoDataTimeFrame.yaml
  datadog/tests/cassettes/TestDatadogMonitor_import_no_recovery.freeze
  datadog/tests/cassettes/TestDatadogMonitor_import_no_recovery.yaml
  docs/resources/monitor.md
  go.mod
  go.sum
Labels: changelog/bugfix

#1968 [datadog_user] Add support for `exact_match` in data source
  datadog/data_source_datadog_user.go
  datadog/tests/cassettes/TestAccDatadogUserDatasourceWithExactMatch.freeze
  datadog/tests/cassettes/TestAccDatadogUserDatasourceWithExactMatch.yaml
  datadog/tests/cassettes/TestAccDatadogUserDatasourceWithExactMatchError.freeze
  datadog/tests/cassettes/TestAccDatadogUserDatasourceWithExactMatchError.yaml
  datadog/tests/data_source_datadog_user_test.go
  docs/data-sources/user.md
  examples/data-sources/datadog_user/data-source.tf
Labels: changelog/improvement

#1972 [datadog_spans_metric] Convert `group_by` to set
  datadog/fwprovider/resource_datadog_spans_metric.go
  datadog/tests/resource_datadog_spans_metric_test.go
  docs/resources/spans_metric.md
Labels: changelog/bugfix

#1976 Mark `TestAccDatadogLogsArchiveGCS_basic` as replay only
  datadog/tests/resource_datadog_logs_archive_test.go
Labels: changelog/no-changelog

#1975 [datadog_dashboard] Add note about tf managed dashboard lists when using `dashboard_lists` resource
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_dashboard_json.go
  docs/resources/dashboard.md
  docs/resources/dashboard_json.md
Labels: changelog/improvement

#1977 [provider] Cleanup package namespace
  datadog/fwprovider/data_source_datadog_api_key.go
  datadog/fwprovider/data_source_datadog_hosts.go
  datadog/fwprovider/data_source_datadog_integration_aws_namespace_rules.go
  datadog/fwprovider/data_source_datadog_ip_ranges.go
  datadog/fwprovider/data_source_datadog_sensitive_data_scanner_group_order.go
  datadog/fwprovider/data_source_datadog_service_account.go
  datadog/fwprovider/data_source_datadog_team.go
  datadog/fwprovider/data_source_datadog_team_memberships.go
  datadog/fwprovider/resource_datadog_api_key.go
  datadog/fwprovider/resource_datadog_integration_cloudflare_account.go
  datadog/fwprovider/resource_datadog_integration_confluent_account.go
  datadog/fwprovider/resource_datadog_integration_confluent_resource.go
  datadog/fwprovider/resource_datadog_integration_fastly_account.go
  datadog/fwprovider/resource_datadog_integration_fastly_service.go
  datadog/fwprovider/resource_datadog_integration_gcp_sts.go
  datadog/fwprovider/resource_datadog_sensitive_data_scanner_group_order.go
  datadog/fwprovider/resource_datadog_service_account_application_key.go
  datadog/fwprovider/resource_datadog_spans_metric.go
  datadog/fwprovider/resource_datadog_synthetics_concurrency_cap.go
  datadog/fwprovider/resource_datadog_team.go
  datadog/fwprovider/resource_datadog_team_link.go
  datadog/fwprovider/resource_datadog_team_membership.go
Labels: changelog/no-changelog

#1966 [datadog_synthetics_test] Fix targetvalue for isUndefined json path assertions
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  go.mod
  go.sum
Labels: changelog/bugfix

#1988 [provider] bump datadog-api-client Go SDK to v2.14.0
  go.mod
  go.sum
Labels: changelog/note
