Repository DataDog/terraform-provider-datadog, pull requests merged in 2024-03, with the labels that each got.

#2307 [datadog_monitor] Check eval window cast before using
  datadog/resource_datadog_monitor.go
  docs/resources/monitor.md
Labels: changelog/bugfix

#2134 [datadog_integration_gcp_sts] Add Account tags, ResourceCollectionEnabled and IsSecurityCommandCenterEnabled support to gcp tf module
  datadog/fwprovider/resource_datadog_integration_gcp_sts.go
  datadog/tests/cassettes/TestAccIntegrationGcpStsBasic.yaml
  datadog/tests/cassettes/TestAccIntegrationGcpStsDefault.yaml
  datadog/tests/resource_datadog_integration_gcp_sts_test.go
  docs/resources/integration_gcp_sts.md
Labels: changelog/feature, gcp-integrations

#2230 [datadog_integration_gcp] Migrate to FW Provider, Add ResourceCollectionEnabled and IsSecurityCommandCenterEnabled fields
  .github/CODEOWNERS
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_integration_gcp.go
  datadog/provider.go
  datadog/resource_datadog_integration_gcp.go
  datadog/tests/cassettes/TestAccDatadogIntegrationGCP.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchiveGCS_basic.yaml
  docs/resources/integration_gcp.md
Labels: changelog/improvement, gcp-integrations

#2312 [datadog_logs_archive] Fix project id for logsArchive
  datadog/resource_datadog_logs_archive.go
  go.mod
  go.sum
Labels: changelog/bugfix

#2314 [datadog_logs_archive] Remove required check for `project_id`
  datadog/resource_datadog_logs_archive.go
Labels: changelog/no-changelog

#2302 [datadog_users] Don't panic if no users is found
  datadog/resource_datadog_user.go
Labels: changelog/bugfix

#2318 [datadog_provider] Bump datadog-api-client-go version
  go.mod
  go.sum
Labels: changelog/note

#2324 format tf files
  docs/resources/dashboard.md
  examples/resources/datadog_dashboard/resource.tf
Labels: changelog/no-changelog

#2325 [datadog_openapi_api] Update documentation
  datadog/fwprovider/resource_datadog_openapi_api.go
  docs/resources/openapi_api.md
  examples/resources/datadog_openapi_api/resource.tf
Labels: documentation, changelog/no-changelog

#2323 [synthetics] support http_version in multi-step API tests
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
  go.mod
  go.sum
Labels: changelog/bugfix

#2316 [datadog_csm_threats_agent_rules] Add ressource and datasource for CSM Threats agent rule
  datadog/fwprovider/data_source_datadog_csm_threats_agent_rule.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_csm_threats_agent_rule.go
  datadog/tests/cassettes/TestAccCSMThreatsAgentRuleDataSource.freeze
  datadog/tests/cassettes/TestAccCSMThreatsAgentRuleDataSource.yaml
  datadog/tests/cassettes/TestAccCSMThreatsAgentRule_CreateAndUpdate.freeze
  datadog/tests/cassettes/TestAccCSMThreatsAgentRule_CreateAndUpdate.yaml
  datadog/tests/data_source_datadog_csm_threats_agent_rules_test.go
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_csm_threats_agent_rule_test.go
  docs/data-sources/csm_threats_agent_rules.md
  docs/resources/csm_threats_agent_rule.md
  examples/resources/datadog_csm_threats_agent_rule/import.sh
  examples/resources/datadog_csm_threats_agent_rule/resource.tf
Labels: changelog/feature

#2334 [datadog_security_monitoring_rule] Explicitly remove filters when none remain in config
  datadog/resource_datadog_security_monitoring_rule.go
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_CwsRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_CwsRule.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_ImpossibleTravelRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_ImpossibleTravelRule.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_NewValueRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_NewValueRule.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_ThirdParty.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_ThirdParty.yaml
Labels: changelog/bugfix

#2339 Rename integrations-tools-and-libraries to api-clients in CODEOWNERS
  .github/CODEOWNERS
Labels: changelog/no-changelog
