Repository DataDog/terraform-provider-datadog, pull requests merged in 2024-11, with the labels that each got.

#2633 Add Resources to Cloudflare Terraform Provider
  datadog/fwprovider/resource_datadog_integration_cloudflare_account.go
  datadog/tests/cassettes/TestAccDatadogSoftwareCatalogEntity_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSoftwareCatalogEntity_Basic.yaml
  datadog/tests/cassettes/TestAccIntegrationCloudflareAccountBasic.freeze
  datadog/tests/cassettes/TestAccIntegrationCloudflareAccountBasic.yaml
  datadog/tests/resource_datadog_integration_cloudflare_account_test.go
  docs/resources/integration_cloudflare_account.md
Labels: changelog/no-changelog

#2644 Update the version.
  datadog/fwprovider/resource_datadog_integration_gcp.go
  datadog/fwprovider/resource_datadog_user_role.go
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogCatalogEntity_Order.freeze
  datadog/tests/cassettes/TestAccDatadogCatalogEntity_Order.yaml
  datadog/tests/cassettes/TestAccDatadogIntegrationGCP.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchiveGCS_basic.yaml
  datadog/tests/cassettes/TestAccDatadogRoleUsersDatasourceBasic.freeze
  datadog/tests/cassettes/TestAccDatadogRoleUsersDatasourceBasic.yaml
  datadog/tests/cassettes/TestAccDatadogRoleUsersDatasourceExactMatch.freeze
  datadog/tests/cassettes/TestAccDatadogRoleUsersDatasourceExactMatch.yaml
  docs/resources/dashboard.md
  docs/resources/powerpack.md
  docs/resources/synthetics_test.md
  go.mod
  go.sum
Labels: changelog/no-changelog

#2653 [datadog_synthetics_test] Handle secure `config_variables` on import
  datadog/resource_datadog_synthetics_test_.go
Labels: changelog/bugfix

#2650 [datadog_integration_gcp_sts] Add Support for MetricNamesapceConfig & IsResourceCollectionChangeEnabled for GCP Service Accounts
  datadog/fwprovider/resource_datadog_integration_gcp.go
  datadog/fwprovider/resource_datadog_integration_gcp_sts.go
  datadog/tests/cassettes/TestAccDatadogIntegrationGCP.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationGCP.yaml
  datadog/tests/cassettes/TestAccIntegrationGcpStsBasic.freeze
  datadog/tests/cassettes/TestAccIntegrationGcpStsBasic.yaml
  datadog/tests/cassettes/TestAccIntegrationGcpStsDefault.freeze
  datadog/tests/cassettes/TestAccIntegrationGcpStsDefault.yaml
  datadog/tests/resource_datadog_integration_gcp_sts_test.go
  datadog/tests/resource_datadog_integration_gcp_test.go
  docs/resources/integration_gcp.md
  docs/resources/integration_gcp_sts.md
  go.mod
  go.sum
Labels: changelog/feature, gcp-integrations

#2637 [resource_datadog_domain_allowlist] Domain allowlist provider support
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_domain_allowlist.go
  datadog/internal/utils/api_instances_helper.go
  datadog/tests/cassettes/TestAccDatadogDomainAllowlist_CreateUpdate.freeze
  datadog/tests/cassettes/TestAccDatadogDomainAllowlist_CreateUpdate.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_domain_allowlist_test.go
  docs/resources/domain_allowlist.md
  examples/resources/datadog_domain_allowlist/resource.tf
Labels: changelog/feature

#2658 [datadog_cloudflare] Remove default and update doc
  datadog/fwprovider/resource_datadog_integration_cloudflare_account.go
  docs/resources/integration_cloudflare_account.md
Labels: changelog/bugfix

#2662 [datadog_dashboard][datadog_powerpack] Update go client to support `good_minutes` and `bad_minutes` for Time Slice SLOs
  docs/resources/dashboard.md
  docs/resources/powerpack.md
  go.mod
  go.sum
Labels: changelog/feature

#2667 Make recommended keywords an opt-out option in terraform
  .github/CODEOWNERS
  datadog/resource_datadog_sensitive_data_scanner_rule.go
  datadog/tests/cassettes/TestAccSensitiveDataScannerRuleBasic.freeze
  datadog/tests/cassettes/TestAccSensitiveDataScannerRuleBasic.yaml
  datadog/tests/resource_datadog_sensitive_data_scanner_rule_test.go
  docs/resources/sensitive_data_scanner_rule.md
  examples/resources/datadog_sensitive_data_scanner_rule/resource.tf
  go.mod
Labels: changelog/note

#2670 Revert "Make recommended keywords an opt-out option in terraform"
  .github/CODEOWNERS
  datadog/resource_datadog_sensitive_data_scanner_rule.go
  datadog/tests/cassettes/TestAccSensitiveDataScannerRuleBasic.freeze
  datadog/tests/cassettes/TestAccSensitiveDataScannerRuleBasic.yaml
  datadog/tests/resource_datadog_sensitive_data_scanner_rule_test.go
  docs/resources/sensitive_data_scanner_rule.md
  examples/resources/datadog_sensitive_data_scanner_rule/resource.tf
  go.mod
Labels: changelog/no-changelog

#2671 [datadog_integration_aws_tag_filter] include `step_functions` as valid enum for v1 AWS tag filter
  docs/resources/integration_aws_tag_filter.md
  go.mod
  go.sum
Labels: changelog/bugfix, mergequeue-status: in_progress

#2674 [datadog_sensitive_data_scanner_rule] make recommended keywords an opt-out option
  .github/CODEOWNERS
  datadog/resource_datadog_sensitive_data_scanner_rule.go
  datadog/tests/cassettes/TestAccSensitiveDataScannerRuleBasic.freeze
  datadog/tests/cassettes/TestAccSensitiveDataScannerRuleBasic.yaml
  datadog/tests/resource_datadog_sensitive_data_scanner_rule_test.go
  docs/resources/sensitive_data_scanner_rule.md
  examples/resources/datadog_sensitive_data_scanner_rule/resource.tf
  go.mod
Labels: changelog/note

#2638 [resource_monitor_json] Avoid restricted role diffs with restriction_policy
  datadog/resource_datadog_monitor_json.go
  datadog/tests/cassettes/TestAccDatadogMonitorJSONBasic.yaml
  datadog/tests/cassettes/TestAccDatadogMonitorJSONImport.yaml
Labels: bug, changelog/bugfix, resource/datadog_monitor_json

#2657 [datadog_integration_ms_teams_tenant_based_handle] Added Resource
  .github/CODEOWNERS
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_integration_microsoft_teams_handle.go
  datadog/internal/utils/api_instances_helper.go
  datadog/tests/cassettes/TestAccMSTeamsTenantBasedHandlesBasic.freeze
  datadog/tests/cassettes/TestAccMSTeamsTenantBasedHandlesBasic.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_integration_microsoft_teams_handle_test.go
  docs/resources/integration_aws_tag_filter.md
  docs/resources/integration_ms_teams_tenant_based_handle.md
  examples/resources/datadog_integration_microsoft_teams_tenant_based_handle/import.sh
  examples/resources/datadog_integration_microsoft_teams_tenant_based_handle/resource.tf
  go.mod
  go.sum
Labels: changelog/feature, mergequeue-status: rejected

#2643 [datadog_rum_metric] Add support for the resource.
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_rum_metric.go
  datadog/internal/utils/api_instances_helper.go
  datadog/tests/cassettes/TestAccRumMetricAttributes.freeze
  datadog/tests/cassettes/TestAccRumMetricAttributes.yaml
  datadog/tests/cassettes/TestAccRumMetricImport.freeze
  datadog/tests/cassettes/TestAccRumMetricImport.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_rum_metric_test.go
  docs/resources/rum_metric.md
  examples/resources/datadog_rum_metric/import.sh
  examples/resources/datadog_rum_metric/resource.tf
Labels: changelog/feature

#2689 [datadog_webhook] Fix panic on missing encode_as field
  datadog/fwprovider/resource_datadog_webhook.go
Labels: changelog/bugfix

#2691 [provider_test] skip a bunch of failing tests
  datadog/tests/data_source_datadog_application_key_test.go
  datadog/tests/resource_datadog_application_key_test.go
  datadog/tests/resource_datadog_domain_allowlist_test.go
Labels: changelog/no-changelog

#2688 [datadog_synthetics_test] Add comment regarding browser step available auths
  datadog/resource_datadog_synthetics_test_.go
Labels: changelog/no-changelog, resource/datadog_synthetics_test

#2686 [datadog_authn_mapping] Read team assignment when importing AuthN mappings
  datadog/resource_datadog_authn_mapping.go
  datadog/tests/cassettes/TestAccDatadogAuthNMapping_import.freeze
  datadog/tests/cassettes/TestAccDatadogAuthNMapping_import.yaml
  datadog/tests/resource_datadog_authn_mapping_test.go
Labels: changelog/bugfix

#2692 Update Logs code ownership to specific teams
  .github/CODEOWNERS
Labels: changelog/no-changelog

#2697 [provider] Bump Datadog Go SDK
  docs/resources/integration_aws_tag_filter.md
  go.mod
  go.sum
Labels: changelog/improvement
