Repository DataDog/terraform-provider-datadog, pull requests merged in 2024-04, with the labels that each got.

#2348 Re-record `TestAccRestrictionPolicyUpdate` cassettes
  datadog/tests/cassettes/TestAccRestrictionPolicyUpdate.freeze
  datadog/tests/cassettes/TestAccRestrictionPolicyUpdate.yaml
Labels: changelog/no-changelog

#2346 [datadog_user] Re-order role updates
  datadog/resource_datadog_user.go
Labels: changelog/bugfix, aaa-access

#2350 [datadog_restriction_policy] Update test to check new error format
  datadog/tests/cassettes/TestAccRestrictionPolicyInvalidInput.freeze
  datadog/tests/cassettes/TestAccRestrictionPolicyInvalidInput.yaml
  datadog/tests/resource_datadog_restriction_policy_test.go
Labels: changelog/no-changelog

#2351 [datadog_webhook] Update webhook urls to include a scheme
  datadog/tests/cassettes/TestAccDatadogWebhook_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogWebhook_Basic.yaml
  datadog/tests/resource_datadog_webhook_test.go
Labels: changelog/no-changelog

#2349 [datadog_service_level_objective] Add query_interval_seconds to time-slice SLO condition parameters
  datadog/resource_datadog_service_level_objective.go
  datadog/tests/cassettes/TestAccDatadogServiceLevelObjective_TimeSlice.freeze
  datadog/tests/cassettes/TestAccDatadogServiceLevelObjective_TimeSlice.yaml
  docs/resources/service_level_objective.md
  go.mod
  go.sum
Labels: changelog/improvement

#2356 [resource_datadog_monitor] Remove usage of locked field from tests
  datadog/tests/cassettes/TestAccDatadogMonitorJSONBasic.freeze
  datadog/tests/cassettes/TestAccDatadogMonitorJSONBasic.yaml
  datadog/tests/cassettes/TestAccDatadogMonitorJSONImport.freeze
  datadog/tests/cassettes/TestAccDatadogMonitorJSONImport.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_UpdatedToRemoveTags.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_UpdatedToRemoveTags.yaml
  datadog/tests/data_source_datadog_monitor_test.go
  datadog/tests/data_source_datadog_monitors_test.go
  datadog/tests/import_datadog_monitor_test.go
  datadog/tests/resource_datadog_monitor_json_test.go
  datadog/tests/resource_datadog_monitor_test.go
  docs/resources/monitor_json.md
  examples/resources/datadog_monitor_json/resource.tf
Labels: changelog/no-changelog

#2317 [datadog_service_account_application_key] Improve service account application key error messages
  datadog/fwprovider/resource_datadog_service_account_application_key.go
Labels: changelog/no-changelog

#2347 [security_monitoring_rule] Deprecate filter field for some rule types
  datadog/resource_datadog_security_monitoring_rule.go
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_OnlyRequiredFields.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_OnlyRequiredFields.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_SignalCorrelation.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_SignalCorrelation.yaml
  datadog/tests/resource_datadog_security_monitoring_rule_test.go
  docs/resources/security_monitoring_rule.md
Labels: changelog/note

#2359 [datadog_monitor] Handle empty `scheduling_options` struct
  datadog/resource_datadog_monitor.go
  datadog/tests/cassettes/TestAccDatadogMonitor_EmptySchedulingOptions.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_EmptySchedulingOptions.yaml
  datadog/tests/resource_datadog_monitor_test.go
Labels: changelog/bugfix

#2358 [datadog_service_level_objective] Handle nil time slice query
  datadog/resource_datadog_service_level_objective.go
Labels: changelog/no-changelog

#2361 [framework_provider] handle empty import id
  datadog/fwprovider/framework_provider.go
  docs/resources/integration_cloudflare_account.md
  examples/resources/datadog_integration_cloudflare_account/import.sh
Labels: changelog/improvement

#2311 [datadog_user_role] Creating a new `datadog_user_role` resource
  datadog/fwprovider/data_source_datadog_role_users.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_user_role.go
  datadog/resource_datadog_user.go
  datadog/tests/cassettes/TestAccDatadogRoleUsersDatasourceBasic.freeze
  datadog/tests/cassettes/TestAccDatadogRoleUsersDatasourceBasic.yaml
  datadog/tests/cassettes/TestAccDatadogRoleUsersDatasourceExactMatch.freeze
  datadog/tests/cassettes/TestAccDatadogRoleUsersDatasourceExactMatch.yaml
  datadog/tests/cassettes/TestAccUserRoleBasic.freeze
  datadog/tests/cassettes/TestAccUserRoleBasic.yaml
  datadog/tests/data_source_datadog_role_users_test.go
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_user_role_test.go
  docs/data-sources/role_users.md
  docs/resources/user_role.md
  examples/resources/datadog_user_role/import.sh
  examples/resources/datadog_user_role/resource.tf
Labels: changelog/feature, aaa-access, mergequeue-status: removed

#2365 [datadog_integration_aws] Add extended resource collection field
  datadog/fwprovider/resource_datadog_security_monitoring_suppression.go
  datadog/internal/utils/utils.go
  datadog/resource_datadog_integration_aws.go
  datadog/tests/cassettes/TestAccDatadogIntegrationAWS.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAWS.yaml
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSAccessKey.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSAccessKey.yaml
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSLambdaArn.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSLambdaArn.yaml
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSLambdaArnAccessKey.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSLambdaArnAccessKey.yaml
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSLogCollection.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSLogCollection.yaml
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSLogCollectionAccessKey.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSLogCollectionAccessKey.yaml
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSLogsServicesDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSLogsServicesDatasource.yaml
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSNamespaceRulesDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSNamespaceRulesDatasource.yaml
  datadog/tests/cassettes/TestAccDatadogIntegrationAwsTagFilter_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAwsTagFilter_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogIntegrationAwsTagFilter_BasicAccessKey.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAwsTagFilter_BasicAccessKey.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchiveS3Update_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchiveS3Update_basic.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchiveS3_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchiveS3_basic.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchivesOrderDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchivesOrderDatasource.yaml
  datadog/tests/cassettes/TestAccIntegrationAwsEventBridgeBasic.freeze
  datadog/tests/cassettes/TestAccIntegrationAwsEventBridgeBasic.yaml
  datadog/tests/resource_datadog_integration_aws_test.go
  docs/resources/integration_aws.md
  go.mod
  go.sum
Labels: changelog/improvement

#2364 [datadog_apm_retention_filter] Fix retention filter update query
  datadog/fwprovider/resource_datadog_apm_retention_filter.go
  go.mod
  go.sum
Labels: changelog/no-changelog

#2366 [datadog_logs_archive] Better error message when no read permission on logs archive
  datadog/resource_datadog_logs_archive.go
Labels: changelog/no-changelog

#2373 [datadog_monitor_json] Ignore the POST null for the restriction_policy field
  datadog/resource_datadog_monitor_json.go
Labels: changelog/bugfix

#2386 [datadog_security_monitoring_suppression] Fix error handling when creating suppression payload
  datadog/fwprovider/resource_datadog_security_monitoring_suppression.go
Labels: changelog/bugfix

#2376 [datadog_sensitive_data_scanner_rule] Add priority level in rules
  datadog/resource_datadog_sensitive_data_scanner_rule.go
  datadog/tests/cassettes/TestAccSensitiveDataScannerRuleBasic.freeze
  datadog/tests/cassettes/TestAccSensitiveDataScannerRuleBasic.yaml
  datadog/tests/resource_datadog_sensitive_data_scanner_rule_test.go
  docs/resources/sensitive_data_scanner_rule.md
  examples/resources/datadog_sensitive_data_scanner_rule/resource.tf
Labels: changelog/improvement

#2357 [resource_datadog_security_monitoring_rule] Add a validation step in security_monitoring_rule_resource provider.
  datadog/data_source_datadog_security_monitoring_rules.go
  datadog/resource_datadog_security_monitoring_rule.go
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_CreateInvalidRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_CreateInvalidRule.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_CwsRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_CwsRule.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_Import.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_Import.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_ImpossibleTravelRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_ImpossibleTravelRule.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_InvalidTypes.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_NewValueRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_NewValueRule.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_OnlyRequiredFields.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_OnlyRequiredFields.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_SignalCorrelation.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_SignalCorrelation.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_ThirdParty.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_ThirdParty.yaml
  datadog/tests/resource_datadog_security_monitoring_rule_test.go
  docs/resources/security_monitoring_rule.md
Labels: changelog/improvement

#2369 [datadog_synthetics_test] Add support for variablesFromScript for API tests
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
  go.mod
  go.sum
Labels: changelog/feature

#2389 [datadog_synthetics_documentation] Update synthetics GRPC example
  docs/resources/synthetics_test.md
  examples/resources/datadog_synthetics_test/resource.tf
Labels: changelog/improvement

#2390 [repo] Fix badge and image in readme
  README.md
Labels: documentation, changelog/no-changelog
