Repository DataDog/terraform-provider-datadog, pull requests merged in 2024-08, with the labels that each got.

#2516 [datadog_synthetics_test] Support upload file in multistep API test
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsApiTestFileUpload_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsApiTestFileUpload_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsApiTest_FileUpload.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsApiTest_FileUpload.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFromTest_LocalVariable.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFromTest_LocalVariable.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_FileUpload.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_FileUpload.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/feature

#2520 [provider] Improve description of api_url to specify the default and requiredness
  datadog/fwprovider/framework_provider.go
  datadog/provider.go
  docs/index.md
Labels: changelog/no-changelog

#2523 [datadog_dashboard] Update docs for new `incident_analytics` datasource
  docs/resources/dashboard.md
  docs/resources/powerpack.md
  go.mod
  go.sum
Labels: changelog/feature

#2524 [repository] Enable ci for merge queue branches
  .github/workflows/test.yml
Labels: changelog/no-changelog

#2521 [provider] remove required mention for `api_url` since there is a default
  datadog/fwprovider/framework_provider.go
  datadog/provider.go
  docs/index.md
Labels: changelog/no-changelog, mergequeue-status: in_progress

#2486 [provider] Add a default_tags attribute in the Datadog provider config.
  datadog/fwprovider/framework_provider.go
  datadog/provider.go
  datadog/resource_datadog_monitor.go
  datadog/tests/cassettes/TestAccDatadogMonitor_DefaultTags.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_DefaultTags.yaml
  datadog/tests/cassettes/TestAccDatadogMonitor_UpdatedToRemoveTags.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_UpdatedToRemoveTags.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_monitor_test.go
  docs/index.md
Labels: changelog/feature, mergequeue-status: in_progress

#2527 Organise synthetics resource file
  datadog/resource_datadog_synthetics_test_.go
Labels: changelog/no-changelog

#2513 [datadog_integration_aws_lambda_arn] Add region note
  datadog/resource_datadog_integration_aws_lambda_arn.go
  docs/resources/integration_aws_lambda_arn.md
Labels: changelog/no-changelog, mergequeue-status: in_progress

#2512 [datadog_service_account][datadog_user] Fix typo in service_account and user
  datadog/fwprovider/resource_datadog_service_account.go
  datadog/resource_datadog_user.go
  docs/resources/service_account.md
  docs/resources/user.md
Labels: changelog/no-changelog

#2533 [datadog_synthetics_test] Do not send `field` if empty
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/bugfix

#2538 [SYNTH-15394] use new SyntheticsGlobalVariableRequest in global variable terraform resource
  datadog/resource_datadog_synthetics_global_variable.go
  go.mod
  go.sum
Labels: changelog/no-changelog, mergequeue-status: in_progress

#2537 [datadog_software_catalog] Entity resource
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_software_catalog.go
  datadog/internal/customtypes/yaml_string_type.go
  datadog/internal/customtypes/yaml_string_value.go
  datadog/tests/cassettes/TestAccDatadogCatalogEntity_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogCatalogEntity_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogCatalogEntity_Order.freeze
  datadog/tests/cassettes/TestAccDatadogCatalogEntity_Order.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_software_catalog_test.go
  docs/resources/software_catalog.md
  examples/resources/datadog_software_catalog/import.sh
  examples/resources/datadog_software_catalog/resource.tf
Labels: changelog/feature

#2542 [datadog_logs_custom_destination] Introduce logs custom destination resource
  datadog/internal/utils/api_instances_helper.go
  datadog/provider.go
  datadog/resource_datadog_logs_custom_destination.go
  datadog/tests/cassettes/TestAccDatadogLogsCustomDestination_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsCustomDestination_basic.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_logs_custom_destination_test.go
  docs/resources/logs_custom_destination.md
  examples/resources/datadog_logs_custom_destination/import.sh
  examples/resources/datadog_logs_custom_destination/resource.tf
Labels: changelog/feature

#2546 [repo] block sdkv2 resources
  .github/sdkv2-warning.yml
  .github/workflows/sdkv2_deprecation.yaml
Labels: changelog/no-changelog

#2541 [datadog_api_key] Add deprecation warning to datadog_api_key data source
  datadog/fwprovider/data_source_datadog_api_key.go
  docs/data-sources/api_key.md
Labels: changelog/note, mergequeue-status: in_progress

#2543 [datadog_api_key] Add deprecation warning for importing datadog_api_key resources
  datadog/fwprovider/resource_datadog_api_key.go
  docs/resources/api_key.md
Labels: changelog/note, mergequeue-status: in_progress

#2544 [datadog_api_key] Stop overwriting key values in state when the API omits the key
  datadog/fwprovider/resource_datadog_api_key.go
  datadog/tests/resource_datadog_api_key_test.go
Labels: changelog/bugfix, mergequeue-status: in_progress

#2545 [datadog_restriction_policy] Allow policy deletions outside of terraform to prompt resource recreation
  datadog/fwprovider/resource_datadog_restriction_policy.go
  datadog/tests/resource_datadog_restriction_policy_test.go
Labels: changelog/bugfix, mergequeue-status: in_progress

#2532 [SOCE-1320] update description for slo validate option
  datadog/resource_datadog_service_level_objective.go
  docs/resources/service_level_objective.md
Labels: changelog/note, mergequeue-status: in_progress

#2547 [repo] Add comment mentioning sdkv2 deprecation
  datadog/provider.go
Labels: changelog/no-changelog
