Repository DataDog/terraform-provider-datadog, pull requests merged in 2024-06, with the labels that each got.

#2419 [datadog_integration_gcp_sts] Add a mutex around the mutating calls in the GCP STS module
  datadog/fwprovider/resource_datadog_integration_gcp_sts.go
Labels: changelog/bugfix, gcp-integrations

#2400 [provider] Bump SDK and fix style nits
  datadog/fwprovider/resource_datadog_apm_retention_filter.go
  datadog/internal/utils/api_instances_helper.go
  go.mod
  go.sum
Labels: changelog/bugfix

#2421 [datadog_security_monitoring_suppression] Set test expiration date to future value
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateThenAddAndRemoveExpirationDate.freeze
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateThenAddAndRemoveExpirationDate.yaml
  datadog/tests/resource_datadog_security_monitoring_suppression_test.go
Labels: changelog/no-changelog

#2420 [datadog_azure_integration] Fix error when updating client_id and tenant_name
  datadog/fwprovider/resource_datadog_azure_integration.go
  datadog/tests/cassettes/TestAccDatadogIntegrationAzure.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAzure.yaml
  datadog/tests/resource_datadog_integration_azure_test.go
Labels: changelog/bugfix

#2422 [datadog_synthetics_test] support file upload for api test
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsApiTestFileUpload_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsApiTestFileUpload_Basic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
Labels: changelog/feature

#2425 [datadog_synthetics_test] Fix docs for `browser_step.params.email`
  datadog/resource_datadog_synthetics_test_.go
  docs/resources/synthetics_test.md
Labels: changelog/no-changelog

#2430 [datadog_security_monitoring_rule] Upgrade go client.
  datadog/resource_datadog_security_monitoring_rule.go
  go.mod
  go.sum
Labels: changelog/bugfix

#2431 [datadog_synthetics_test] Support the bodyHash assertion.
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
  go.mod
  go.sum
Labels: changelog/improvement

#2437 [datadog_synthetics_test] support json schema assertion in api and multi test
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
Labels: changelog/feature

#2438 Synthetics CT takes ownership of the datadog_synthetics resources
  .github/CODEOWNERS
Labels: changelog/no-changelog

#2435 [datadog_synthetics_test] Test re-assigning multi-locator when creating / deleting / reordering test steps
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowser_UpdateSteps.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowser_UpdateSteps.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/no-changelog

#2433 [datadog_logs_metric][datadog_metric_metadata] Normalize invalid metric name
  datadog/internal/utils/utils.go
  datadog/internal/utils/utils_test.go
  datadog/resource_datadog_logs_metric.go
  datadog/resource_datadog_metric_metadata.go
Labels: changelog/bugfix

#2449 [datadog_logs_index] Set index name to replace on modify
  datadog/resource_datadog_logs_index.go
  docs/resources/logs_index.md
Labels: changelog/bugfix

#2447 [datadog_service_account] Implement exact match filtering
  datadog/fwprovider/data_source_datadog_service_account.go
  docs/data-sources/service_account.md
Labels: changelog/improvement, aaa-access

#2454 [datadog_synthetics_test] add grpc health test example in documentation
  docs/resources/synthetics_test.md
  examples/resources/datadog_synthetics_test/resource.tf
Labels: changelog/no-changelog

#2427 [datadog_synthetics_test] Add original file name to API files
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsApiTestFileUpload_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsApiTestFileUpload_Basic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
Labels: changelog/improvement

#2461 [Repo] Update CODEOWNERS for dashboards resources
  .github/CODEOWNERS
Labels: changelog/no-changelog

#2463 [datadog_team_link] Fix example of position field
  docs/resources/team_link.md
  examples/resources/datadog_team_link/resource.tf
Labels: changelog/no-changelog

#2453 [security_monitoring_suppression] Update example in docs
  docs/resources/security_monitoring_suppression.md
  examples/resources/datadog_security_monitoring_suppression/resource.tf
Labels: changelog/no-changelog

#2464 [provider] Introduce a non-enriched enum validator for enum edge cases
  datadog/fwprovider/resource_datadog_team_permission_setting.go
  datadog/internal/fwutils/fw_enrich_schema.go
  datadog/internal/validators/enum_validator.go
  docs/resources/synthetics_test.md
  docs/resources/team_permission_setting.md
  examples/resources/datadog_synthetics_test/resource.tf
Labels: changelog/no-changelog

#2396 [datadog_organization_settings] Add Security Contacts support
  .github/CODEOWNERS
  datadog/internal/utils/utils.go
  datadog/internal/validators/validators.go
  datadog/resource_datadog_child_organization.go
  datadog/resource_datadog_organization_settings.go
  datadog/tests/cassettes/TestAccDatadogOrganizationSettings_Import.freeze
  datadog/tests/cassettes/TestAccDatadogOrganizationSettings_Import.yaml
  datadog/tests/cassettes/TestAccDatadogOrganizationSettings_IncorrectName.freeze
  datadog/tests/cassettes/TestAccDatadogOrganizationSettings_IncorrectName.yaml
  datadog/tests/cassettes/TestAccDatadogOrganizationSettings_SecurityContacts.freeze
  datadog/tests/cassettes/TestAccDatadogOrganizationSettings_SecurityContacts.yaml
  datadog/tests/cassettes/TestAccDatadogOrganizationSettings_Update.freeze
  datadog/tests/cassettes/TestAccDatadogOrganizationSettings_Update.yaml
  datadog/tests/cassettes/TestDatadogOrganizationSettings_import.freeze
  datadog/tests/cassettes/TestDatadogOrganizationSettings_import.yaml
  datadog/tests/resource_datadog_organization_settings_test.go
  docs/resources/organization_settings.md
  go.mod
  go.sum
Labels: changelog/feature
