Repository DataDog/terraform-provider-datadog, pull requests merged in 2024-02, with the labels that each got.

#2265 [datadog_dashboards] Bump limit for allowed graphs in split graph widget
  datadog/resource_datadog_dashboard.go
  docs/resources/dashboard.md
Labels: changelog/improvement

#2263 [datadog_logs_index] Add daily limit reset options to log indexes
  datadog/data_source_datadog_logs_indexes.go
  datadog/resource_datadog_logs_index.go
  datadog/tests/cassettes/TestAccDatadogLogsIndex_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsIndex_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogLogsIndexesDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogLogsIndexesDatasource.yaml
  datadog/tests/resource_datadog_logs_index_test.go
  docs/data-sources/logs_indexes.md
  docs/resources/logs_index.md
  examples/resources/datadog_logs_index/resource.tf
Labels: changelog/improvement

#2266 [repo] Remove web integrations from codeowner of saas integration resources
  .github/CODEOWNERS
Labels: changelog/no-changelog

#2270 [provider] Bump Go SDK
  go.mod
  go.sum
Labels: changelog/no-changelog

#2275 [datadog_monitor] Sync search query validation with backend API
  datadog/resource_datadog_monitor.go
Labels: changelog/bugfix

#2274 [datadog_synthetics_test] Small doc style change
  datadog/resource_datadog_synthetics_test_.go
  docs/resources/synthetics_test.md
Labels: changelog/no-changelog

#2280 [datadog_logs_index] Fix permadiff on omitted reset time
  datadog/resource_datadog_logs_index.go
Labels: changelog/bugfix

#2282 [codeowners] Add Synthetics CT team
  .github/CODEOWNERS
Labels: changelog/no-changelog, mergequeue-status: removed

#2286 [datadog_integration_pagerduty_service_object] Add importer
  datadog/resource_datadog_integration_pagerduty_service_object.go
  docs/resources/integration_pagerduty_service_object.md
  examples/resources/datadog_integration_pagerduty_service_object/import.sh
Labels: changelog/improvement

#2287 [datadog_metric_metadata] don't send `type` field for distribution metrics
  datadog/resource_datadog_metric_metadata.go
Labels: changelog/no-changelog

#2295 [provider] Update go version
  datadog/fwprovider/data_source_security_monitoring_suppression.go
  datadog/fwprovider/resource_datadog_ip_allowlist.go
  datadog/fwprovider/resource_datadog_openapi_api.go
  datadog/fwprovider/resource_datadog_security_monitoring_suppression.go
  datadog/fwprovider/resource_datadog_service_account.go
  datadog/internal/planmodifiers/types_string_ip_normalizer.go
  datadog/tests/data_source_datadog_security_monitoring_suppressions_test.go
  datadog/tests/resource_datadog_openapi_api_test.go
  datadog/tests/resource_datadog_security_monitoring_suppression_test.go
  datadog/tests/resource_datadog_service_account_test.go
  docs/resources/monitor.md
  docs/resources/synthetics_test.md
  go.mod
  go.sum
Labels: changelog/improvement

#2299 [datadog_logs_archive] Make project id optional in GCS destination
  datadog/resource_datadog_logs_archive.go
  docs/resources/logs_archive.md
Labels: changelog/improvement

#2301 [datadog_sensitive_data_scanner_group] Mark resource as missing when not found
  datadog/resource_datadog_sensitive_data_scanner_group.go
Labels: changelog/bugfix
