Repository DataDog/terraform-provider-datadog, pull requests merged in 2024-10, with the labels that each got.

#2599 Bump go library.
  docs/resources/synthetics_test.md
  go.mod
  go.sum
Labels: changelog/no-changelog

#2587 [datadog_dashboard] Add support for text_formats in query table widget requests
  datadog/resource_datadog_dashboard.go
  datadog/tests/cassettes/TestAccDatadogDashboardQueryTableWithTextFormats.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardQueryTableWithTextFormats.yaml
  datadog/tests/cassettes/TestAccDatadogDashboardQueryTableWithTextFormats_import.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardQueryTableWithTextFormats_import.yaml
  datadog/tests/resource_datadog_dashboard_query_table_test.go
  docs/resources/dashboard.md
  docs/resources/powerpack.md
  go.sum
Labels: changelog/bugfix, editorial review

#2601 Revert "Release 3.45.0"
  CHANGELOG.md
Labels: changelog/no-changelog

#2603 Fix permissions
  .github/workflows/release.yml
Labels: changelog/no-changelog

#2604 Remove workflows permission.
  .github/workflows/release.yml
Labels: changelog/no-changelog

#2591 [datadog_software_catalog] v3 terraform needs to hydrate the current state from raw content
  datadog/fwprovider/resource_datadog_software_catalog.go
  datadog/tests/cassettes/TestAccDatadogSoftwareCatalogEntity_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSoftwareCatalogEntity_Basic.yaml
  datadog/tests/resource_datadog_software_catalog_test.go
Labels: changelog/bugfix, mergequeue-status: in_progress

#2607 [datadog_user_role] refactor
  datadog/fwprovider/resource_datadog_user_role.go
Labels: changelog/no-changelog, mergequeue-status: in_progress

#2611 [datadog_dashboard] Add support for x and y axis controls on distribution widgets
  datadog/resource_datadog_dashboard.go
  datadog/tests/cassettes/TestAccDatadogDashboardApmStatsQueryDistribution.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardApmStatsQueryDistribution.yaml
  datadog/tests/cassettes/TestAccDatadogDashboardDistribution.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardDistribution.yaml
  datadog/tests/cassettes/TestAccDatadogDashboardDistribution_import.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardDistribution_import.yaml
  datadog/tests/resource_datadog_dashboard_distribution_test.go
  docs/resources/dashboard.md
  docs/resources/powerpack.md
Labels: changelog/feature, mergequeue-status: in_progress

#2612 [datadog_integration_gcp_sts] Add CloudRevisionRunFilters field to GCPStsServiceAccount Tf module
  datadog/fwprovider/resource_datadog_integration_gcp.go
  datadog/fwprovider/resource_datadog_integration_gcp_sts.go
  datadog/tests/cassettes/TestAccDatadogIntegrationGCP.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationGCP.yaml
  datadog/tests/cassettes/TestAccIntegrationGcpStsBasic.freeze
  datadog/tests/cassettes/TestAccIntegrationGcpStsBasic.yaml
  datadog/tests/cassettes/TestAccIntegrationGcpStsDefault.freeze
  datadog/tests/cassettes/TestAccIntegrationGcpStsDefault.yaml
  datadog/tests/resource_datadog_integration_gcp_sts_test.go
  datadog/tests/resource_datadog_integration_gcp_test.go
  docs/resources/integration_gcp.md
  docs/resources/integration_gcp_sts.md
  examples/resources/datadog_integration_gcp/resource.tf
  examples/resources/datadog_integration_gcp_sts/resource.tf
Labels: changelog/feature, gcp-integrations

#2582 Add team and user principals to restriction_policy documentation
  datadog/fwprovider/resource_datadog_restriction_policy.go
  docs/resources/restriction_policy.md
Labels: changelog/no-changelog

#2628 [cloud_configuration_rule] Make order of cloud configuration rule tags deterministic
  datadog/resource_datadog_cloud_configuration_rule.go
  datadog/tests/cassettes/TestAccDatadogCloudConfigurationRule_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogCloudConfigurationRule_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogCloudConfigurationRule_Import.freeze
  datadog/tests/cassettes/TestAccDatadogCloudConfigurationRule_Import.yaml
  datadog/tests/cassettes/TestAccDatadogCloudConfigurationRule_MandatoryFieldsOnly.freeze
  datadog/tests/cassettes/TestAccDatadogCloudConfigurationRule_MandatoryFieldsOnly.yaml
  datadog/tests/resource_datadog_cloud_configuration_rule_test.go
Labels: changelog/bugfix

#2630 [datadog_ip_allowlist_test] Skip failing test due to backend bug
  datadog/tests/cassettes/TestAccDatadogIPAllowlist_CreateUpdate.freeze
  datadog/tests/cassettes/TestAccDatadogIPAllowlist_CreateUpdate.yaml
  datadog/tests/resource_datadog_ip_allowlist_test.go
Labels: changelog/no-changelog
