Repository DataDog/terraform-provider-datadog, pull requests merged in 2024-05, with the labels that each got.

#2394 Remove roles from synthetics tests
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_importBasic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_importBasic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_importBasic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.yaml
  datadog/tests/resource_datadog_synthetics_global_variable_test.go
  datadog/tests/resource_datadog_synthetics_private_location_test.go
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/no-changelog

#2393 [datadog_synthetics_test] Ensure tags are non-empty and castable
  datadog/resource_datadog_synthetics_test_.go
Labels: changelog/bugfix

#2398 [datadog_powerpack] Cleanup example
  docs/resources/powerpack.md
  examples/resources/datadog_powerpack/resource.tf
Labels: changelog/no-changelog

#2403 [resource_integration_fastly_service] update import docs
  docs/resources/integration_fastly_service.md
  examples/resources/datadog_integration_fastly_service/import.sh
Labels: changelog/no-changelog

#2402 [resource_datadog_role] Skip name update check
  datadog/tests/cassettes/TestAccDatadogRole_CreateUpdate.freeze
  datadog/tests/cassettes/TestAccDatadogRole_CreateUpdate.yaml
  datadog/tests/resource_datadog_role_test.go
Labels: changelog/no-changelog

#2407 [CWS-2164] - Put the cloud workload security resources as deprecated
  datadog/data_source_datadog_cloud_workload_security_agent_rules.go
  datadog/resource_datadog_cloud_workload_security_agent_rule.go
  docs/data-sources/cloud_workload_security_agent_rules.md
  docs/resources/cloud_workload_security_agent_rule.md
Labels: changelog/note

#2416 Mark private location tests as replay only
  datadog/resource_datadog_authn_mapping.go
  datadog/tests/resource_datadog_authn_mapping_test.go
  datadog/tests/resource_datadog_synthetics_private_location_test.go
Labels: changelog/no-changelog

#2412 Add deprecation message on cloud_workload_security_agent_rules resource and data source
  datadog/data_source_datadog_cloud_workload_security_agent_rules.go
  datadog/resource_datadog_cloud_workload_security_agent_rule.go
  docs/data-sources/cloud_workload_security_agent_rules.md
  docs/resources/cloud_workload_security_agent_rule.md
Labels: changelog/note, mergequeue-status: removed
