Repository DataDog/terraform-provider-datadog, pull requests merged in 2024-12, with the labels that each got.

#2700 Fixes and helpers to handle defaults in nested blocks with oneOf constraints
  datadog/fwprovider/resource_datadog_aws_account_v2.go
  datadog/internal/fwutils/modify_plan.go
Labels: changelog/no-changelog

#2687 [datadog_synthetics_test] Add maximum value in docs for retry and interval
  datadog/resource_datadog_synthetics_test_.go
  docs/resources/synthetics_test.md
Labels: mergequeue-status: removed, changelog/documentation

#2704 [datadog_sensitive_data_standard_pattern] add description and deprecate pattern
  datadog/data_source_datadog_sensitive_data_scanner_standard_pattern.go
  docs/data-sources/sensitive_data_scanner_standard_pattern.md
  docs/resources/synthetics_test.md
Labels: changelog/feature

#2713 fix(github-workflows): use official GitHub action for token generation
  .github/workflows/changelog.yaml
  .github/workflows/prepare_release.yml
  .github/workflows/release.yml
Labels: changelog/no-changelog

#2717 [datadog_synthetics_test] Add support for mobile steps
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsMobileTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsMobileTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsMobileTest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsMobileTest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsMobileTest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsMobileTest_importBasic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
Labels: changelog/feature

#2683 [datadog_synthetics_test] Fix multistep client certificate
  datadog/resource_datadog_synthetics_test_.go
Labels: changelog/bugfix, resource/datadog_synthetics_test, mergequeue-status: in_progress

#2716 [resource_datadog_logs_index] Fix having zero retention logs indexes with flex
  datadog/resource_datadog_logs_index.go
  datadog/tests/cassettes/TestAccDatadogLogsIndex_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsIndex_Basic.yaml
  datadog/tests/resource_datadog_logs_index_test.go
Labels: changelog/bugfix

#2682 [datadog_integration_aws_account] Add `datadog_integration_aws_account` resource
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_integration_aws_account.go
  datadog/internal/fwutils/modify_plan.go
  datadog/internal/utils/api_instances_helper.go
  datadog/resource_datadog_integration_aws.go
  datadog/resource_datadog_integration_aws_lambda_arn.go
  datadog/resource_datadog_integration_aws_log_collection.go
  datadog/resource_datadog_integration_aws_tag_filter.go
  datadog/tests/cassettes/TestAccIntegrationAwsAccountKeyBased.freeze
  datadog/tests/cassettes/TestAccIntegrationAwsAccountKeyBased.yaml
  datadog/tests/cassettes/TestAccIntegrationAwsAccount_RoleBased.freeze
  datadog/tests/cassettes/TestAccIntegrationAwsAccount_RoleBased.yaml
  datadog/tests/framework_provider_test.go
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_integration_aws_account_test.go
  docs/resources/integration_aws_account.md
  examples/resources/datadog_integration_aws_account/import.sh
  examples/resources/datadog_integration_aws_account/resource.tf
  scripts/generate-docs.sh
Labels: changelog/feature

#2719 testacc when testing tofu
  .github/workflows/test.yml
Labels: changelog/no-changelog

#2709 [datadog_integration_aws_available_namespaces] Create AWS Integrations V2 datasources `datadog_integration_aws_available_logs_services/namespaces`
  datadog/fwprovider/data_source_datadog_integration_aws_available_logs_services.go
  datadog/fwprovider/data_source_datadog_integration_aws_available_namespaces.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_integration_aws_account.go
  datadog/internal/utils/api_instances_helper.go
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSAvailableLogsServicesDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSAvailableLogsServicesDatasource.yaml
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSAvailableNamespacesDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSAvailableNamespacesDatasource.yaml
  datadog/tests/data_source_datadog_integration_aws_available_logs_services_test.go
  datadog/tests/data_source_datadog_integration_aws_available_namespaces_test.go
  datadog/tests/framework_provider_test.go
  datadog/tests/provider_test.go
  docs/data-sources/integration_aws_available_logs_services.md
  docs/data-sources/integration_aws_available_namespaces.md
  docs/resources/integration_aws_account.md
Labels: changelog/feature

#2724 [datadog_integration_cloudflare_account] Don't set email left empty and ignore resource order
  datadog/fwprovider/resource_datadog_integration_cloudflare_account.go
  docs/resources/integration_cloudflare_account.md
Labels: changelog/bugfix

#2680 [datadog_monitor] Change enable_samples to optional
  datadog/resource_datadog_monitor.go
  docs/resources/monitor.md
Labels: changelog/bugfix

#2726 bump go
  go.mod
  go.sum
Labels: changelog/no-changelog

#2731 [datadog_synthetics_test] Prevent updating `files` with the backend response to keep the plan stable
  datadog/resource_datadog_synthetics_test_.go
Labels: changelog/bugfix, mergequeue-status: in_progress

#2735 [datadog_integration_aws_account] Fix incorrect import docs instructions
  docs/resources/integration_aws_account.md
  examples/resources/datadog_integration_aws_account/import.sh
Labels: changelog/documentation

#2743 bump tofu
  .github/workflows/test.yml
Labels: changelog/no-changelog

#2742 [datadog_webhook] fix import
  datadog/fwprovider/resource_datadog_webhook.go
Labels: changelog/bugfix

#2744 [datadog_synthetics_test] Add step public id in the state
  datadog/resource_datadog_synthetics_test_.go
  docs/resources/synthetics_test.md
  go.mod
  go.sum
Labels: changelog/improvement
