Repository DataDog/terraform-provider-datadog, pull requests merged in 2024-01, with the labels that each got.

#2215 [datadog_rum_application] migrate to framework
  datadog/data_source_datadog_rum_application.go
  datadog/fwprovider/data_source_datadog_rum_application.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_rum_application.go
  datadog/provider.go
  datadog/resource_datadog_rum_application.go
  datadog/tests/data_source_datadog_rum_application_test.go
  datadog/tests/resource_datadog_rum_application_test.go
  docs/data-sources/rum_application.md
  docs/resources/rum_application.md
Labels: changelog/improvement

#2204 [datadog_integration_aws_event_bridge] Add support for AWS Event Bridge integration
  datadog/fwprovider/data_source_datadog_rum_application.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_integration_aws_event_bridge.go
  datadog/internal/utils/utils.go
  datadog/resource_datadog_integration_aws.go
  datadog/resource_datadog_integration_aws_lambda_arn.go
  datadog/resource_datadog_integration_aws_log_collection.go
  datadog/resource_datadog_integration_aws_tag_filter.go
  datadog/tests/cassettes/TestAccIntegrationAwsEventBridgeBasic.freeze
  datadog/tests/cassettes/TestAccIntegrationAwsEventBridgeBasic.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_integration_aws_event_bridge_test.go
  docs/guides/monitors.md
  docs/resources/integration_aws_event_bridge.md
  examples/guides/watchdog_monitor.tf
  examples/resources/datadog_integration_aws_event_bridge/import.sh
  examples/resources/datadog_integration_aws_event_bridge/resource.tf
Labels: changelog/feature

#2211 [datadog_dashboard][datadog_powerpack] Support cloud cost query in F&F queries
  datadog/resource_datadog_dashboard.go
  datadog/tests/cassettes/TestAccDatadogDashboardFormula.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardFormula.yaml
  datadog/tests/cassettes/TestAccDatadogDashboardFormula_import.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardFormula_import.yaml
  datadog/tests/cassettes/TestAccDatadogPowerpackTimeseriesFormula.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackTimeseriesFormula.yaml
  datadog/tests/resource_datadog_dashboard_timeseries_test.go
  datadog/tests/resource_datadog_powerpack_timeseries_test.go
  docs/resources/dashboard.md
  docs/resources/powerpack.md
  examples/resources/datadog_dashboard/resource.tf
Labels: changelog/improvement

#2233 Mark std pattern tests as integration only
  datadog/tests/cassettes/TestAccDatadogStandardPatternDatasourceErrorMultiple.freeze
  datadog/tests/cassettes/TestAccDatadogStandardPatternDatasourceErrorMultiple.yaml
  datadog/tests/cassettes/TestAccDatadogStandardPatternDatasourceErrorNotFound.freeze
  datadog/tests/cassettes/TestAccDatadogStandardPatternDatasourceErrorNotFound.yaml
  datadog/tests/cassettes/TestAccDatadogStandardPatternDatasourceNameFilter.freeze
  datadog/tests/cassettes/TestAccDatadogStandardPatternDatasourceNameFilter.yaml
  datadog/tests/cassettes/TestAccSensitiveDataScannerRuleWithStandardPattern.freeze
  datadog/tests/cassettes/TestAccSensitiveDataScannerRuleWithStandardPattern.yaml
  datadog/tests/data_source_datadog_sensitive_data_scanner_standard_pattern_test.go
  datadog/tests/resource_datadog_sensitive_data_scanner_rule_test.go
Labels: changelog/no-changelog

#2220 [datadog_users] Added support for the Users data source
  datadog/fwprovider/data_source_datadog_users.go
  datadog/fwprovider/framework_provider.go
  datadog/tests/cassettes/TestAccDatadogUsersDatasourceFilter.freeze
  datadog/tests/cassettes/TestAccDatadogUsersDatasourceFilter.yaml
  datadog/tests/cassettes/TestAccDatadogUsersDatasourceFilterStatus.freeze
  datadog/tests/cassettes/TestAccDatadogUsersDatasourceFilterStatus.yaml
  datadog/tests/data_source_datadog_users_test.go
  datadog/tests/provider_test.go
  docs/data-sources/users.md
  examples/data-sources/datadog_users/data-source.tf
Labels: changelog/feature

#2224 [application_key] Migrate application key resource to framework
  datadog/data_source_datadog_application_key.go
  datadog/fwprovider/data_source_datadog_application_key.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_application_key.go
  datadog/provider.go
  datadog/resource_datadog_application_key.go
  datadog/tests/data_source_datadog_application_key_test.go
  datadog/tests/resource_datadog_application_key_test.go
Labels: changelog/improvement

#2222 [datadog_metric_metadata] correct consistency of type
  datadog/resource_datadog_metric_metadata.go
  docs/resources/metric_metadata.md
Labels: changelog/improvement

#2234 Bump datadog-api-client client to 2.21.0
  docs/resources/service_level_objective.md
  go.mod
  go.sum
Labels: changelog/note

#2236 [datadog_gcp_sts] Avoid initializing attributes using `WithDefault()`
  datadog/fwprovider/resource_datadog_integration_gcp_sts.go
  datadog/tests/cassettes/TestAccIntegrationGcpStsDefault.freeze
  datadog/tests/cassettes/TestAccIntegrationGcpStsDefault.yaml
  datadog/tests/resource_datadog_integration_gcp_sts_test.go
Labels: changelog/improvement

#2239 [ip_allow_list] Migrate ip allow list to framework
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_ip_allowlist.go
  datadog/internal/planmodifiers/types_string_ip_normalizer.go
  datadog/internal/utils/utils.go
  datadog/internal/validators/cidr_ip_validator.go
  datadog/provider.go
  datadog/resource_datadog_ip_allowlist.go
  datadog/tests/cassettes/TestAccDatadogIPAllowlist_CreateUpdate.yaml
  datadog/tests/resource_datadog_ip_allowlist_test.go
  docs/resources/ip_allowlist.md
Labels: changelog/improvement

#2240 [ip_allowlist] Add ipv6 to test case
  datadog/tests/cassettes/TestAccDatadogIPAllowlist_CreateUpdate.freeze
  datadog/tests/cassettes/TestAccDatadogIPAllowlist_CreateUpdate.yaml
  datadog/tests/resource_datadog_ip_allowlist_test.go
Labels: changelog/no-changelog

#2249 [datadog_synthetics_test] Fix no_saving_response_body option to the request config for multi api test
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFromTest_LocalVariable.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFromTest_LocalVariable.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/bugfix

#2252 [datadog_synthetics_test] Check if ci options block is valid
  datadog/resource_datadog_synthetics_test_.go
Labels: changelog/bugfix

#2245 [datadog_service_level_objective] Add support for time-slice SLOs
  datadog/resource_datadog_service_level_objective.go
  datadog/tests/cassettes/TestAccDatadogServiceLevelObjective_TimeSlice.freeze
  datadog/tests/cassettes/TestAccDatadogServiceLevelObjective_TimeSlice.yaml
  datadog/tests/resource_datadog_service_level_objective_test.go
  docs/resources/service_level_objective.md
  examples/resources/datadog_service_level_objective/resource.tf
Labels: changelog/improvement

#2254 Docs6983/update permissions note
  docs/resources/integration_gcp_sts.md
  examples/resources/datadog_integration_gcp_sts/resource.tf
Labels: changelog/no-changelog, mergequeue-status: waiting

#2247 [datadog_api_key][datadog_application_key] Add exact_match option to data sources
  datadog/fwprovider/data_source_datadog_api_key.go
  datadog/fwprovider/data_source_datadog_application_key.go
  datadog/tests/data_source_datadog_api_key_test.go
  datadog/tests/data_source_datadog_application_key_test.go
  docs/data-sources/api_key.md
  docs/data-sources/application_key.md
Labels: changelog/improvement

#2244 [datadog_apm_retention_filter] User mutex to prevent concurrent operation
  .github/CODEOWNERS
  datadog/fwprovider/resource_datadog_apm_retention_filter.go
  datadog/tests/cassettes/TestAccApmRetentionFilter.freeze
  datadog/tests/cassettes/TestAccApmRetentionFilter.yaml
  datadog/tests/resource_datadog_apm_retention_filter_test.go
Labels: changelog/bugfix

#2258 [datadog_monitor] Omit recurrence start field if its an empty string
  datadog/resource_datadog_monitor.go
Labels: changelog/bugfix

#2259 add saas ints
  .github/CODEOWNERS
Labels: changelog/no-changelog

#2246 [datadog_security_monitoring_suppression] Add support for suppressions
  datadog/fwprovider/data_source_security_monitoring_suppression.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_security_monitoring_suppression.go
  datadog/tests/cassettes/TestAccIntegrationGcpStsBasic.freeze
  datadog/tests/cassettes/TestAccIntegrationGcpStsBasic.yaml
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppressionDataSource.freeze
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppressionDataSource.yaml
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateAndUpdateWithoutExpirationDate.freeze
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateAndUpdateWithoutExpirationDate.yaml
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateThenAddAndRemoveExpirationDate.freeze
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateThenAddAndRemoveExpirationDate.yaml
  datadog/tests/data_source_datadog_security_monitoring_suppressions_test.go
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_security_monitoring_suppression_test.go
  docs/data-sources/security_monitoring_suppressions.md
  docs/resources/security_monitoring_suppression.md
  go.mod
  go.sum
Labels: changelog/feature

#2253 Fix link in old changelog entry
  CHANGELOG.md
Labels: changelog/no-changelog

#2261 [repo] Add a test target for OpenTofu
  .github/workflows/test.yml
Labels: do-not-merge/WIP, changelog/no-changelog

#2262 [datadog_openapi_api] Add support for API management resource
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_openapi_api.go
  datadog/internal/utils/api_instances_helper.go
  datadog/tests/cassettes/TestAccOpenapiApiBasic.freeze
  datadog/tests/cassettes/TestAccOpenapiApiBasic.yaml
  datadog/tests/framework_provider_test.go
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_openapi_api_test.go
  docs/resources/openapi_api.md
  examples/resources/datadog_openapi_api/import.sh
  examples/resources/datadog_openapi_api/resource.tf
  go.mod
  go.sum
Labels: changelog/feature
