Repository DataDog/terraform-provider-datadog, pull requests merged in 2024-07, with the labels that each got.

#2469 [datadog_synthetics_test] Add validation on synthetics test header
  datadog/internal/validators/validators.go
  datadog/resource_datadog_synthetics_test_.go
Labels: changelog/improvement

#2472 [datadog_synthetics_test] Add handling of a wait step for multistep api tests
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
  go.mod
  go.sum
Labels: changelog/feature

#2474 [datadog_synthetics_test] Add support for `force_delete_dependencies` field
  datadog/resource_datadog_synthetics_test_.go
  docs/resources/monitor.md
  docs/resources/synthetics_test.md
  go.mod
  go.sum
Labels: changelog/improvement

#2476 Replace --rm-dist with --clean
  .github/workflows/release.yml
Labels: changelog/no-changelog

#2477 Revert "Release 3.40.0"
  CHANGELOG.md
Labels: changelog/no-changelog

#2457 [datadog_synthetics_test] Fix `renotify_interval` drift when saving from UI
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowser_UpdateSteps.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowser_UpdateSteps.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/bugfix

#2459 [datadog_synthetics_test] Remove `request_definition.timeout` default value
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTestBrowserNewBrowserStep_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTestBrowserNewBrowserStep_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTestBrowserVariables_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTestBrowserVariables_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsDNSTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsDNSTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsDNSTest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsDNSTest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsDNSTest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsDNSTest_importBasic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGRPCTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGRPCTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsICMPTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsICMPTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsSSLMissingTagsAttributeTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsSSLMissingTagsAttributeTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsSSLTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsSSLTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsSSLTest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsSSLTest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsSSLTest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsSSLTest_importBasic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTCPTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTCPTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTCPTest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTCPTest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTCPTest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTCPTest_importBasic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTest.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTest.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserMML_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserMML_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserUserLocator_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserUserLocator_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserUserLocator_NoElement.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserUserLocator_NoElement.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestWithUrl.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestWithUrl.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsUDPTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsUDPTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsWebsocketTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsWebsocketTest_Basic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
Labels: changelog/bugfix

#2450 [datadog_dashboard] Add `cross_org_uuid support`
  datadog/resource_datadog_dashboard.go
  datadog/tests/cassettes/TestAccDatadogDashboardCrossOrg.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardCrossOrg.yaml
  datadog/tests/cassettes/TestAccDatadogDashboardCrossOrg_import.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardCrossOrg_import.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_dashboard_cross_org_test.go
  docs/resources/dashboard.md
  docs/resources/powerpack.md
Labels: changelog/feature

#2460 [datadog_synthetics_test] prevent overriding the local state element from the backend response
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserMML_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserMML_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserUserLocator_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserUserLocator_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserUserLocator_NoElement.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserUserLocator_NoElement.yaml
Labels: changelog/bugfix

#2434 [datadog_service_account] Role-assignment improvements for service accounts
  datadog/fwprovider/data_source_datadog_service_account.go
  datadog/fwprovider/resource_datadog_service_account.go
  datadog/fwprovider/resource_datadog_user_role.go
  docs/data-sources/service_account.md
  docs/resources/user_role.md
Labels: changelog/bugfix

#2483 [datadog_integration_azure] Stop testing updating client id and tenant name
  datadog/tests/cassettes/TestAccDatadogIntegrationAzure.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAzure.yaml
  datadog/tests/resource_datadog_integration_azure_test.go
Labels: changelog/no-changelog

#2468 [datadog_application_key] Add deprecation warning for importing datadog_application_key resources
  datadog/fwprovider/resource_datadog_application_key.go
  docs/resources/application_key.md
Labels: changelog/note

#2465 [datadog_application_key] Add deprecation warning to datadog_application_key data source
  datadog/fwprovider/data_source_datadog_application_key.go
  datadog/tests/data_source_datadog_application_key_test.go
  docs/data-sources/application_key.md
Labels: changelog/note

#2451 [datadog_application_key] Stop overwriting key values in state when the API omits the key
  datadog/fwprovider/resource_datadog_application_key.go
  datadog/tests/resource_datadog_application_key_test.go
Labels: changelog/bugfix

#2485 [documentation] Fix import examples with empty string IDs
  docs/resources/restriction_policy.md
  docs/resources/sensitive_data_scanner_group.md
  docs/resources/sensitive_data_scanner_rule.md
  examples/resources/datadog_restriction_policy/import.sh
  examples/resources/datadog_sensitive_data_scanner_group/import.sh
  examples/resources/datadog_sensitive_data_scanner_rule/import.sh
Labels: changelog/no-changelog

#2375 [datadog_hosts] Add tags_by_source for datadog_hosts data source
  datadog/fwprovider/data_source_datadog_hosts.go
  docs/data-sources/hosts.md
Labels: changelog/improvement

#2458 [datadog_powerpack] add support for datadog_powerpack data source
  datadog/fwprovider/data_source_datadog_powerpack.go
  datadog/fwprovider/framework_provider.go
  datadog/tests/cassettes/TestAccDatadogPowerpackDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogPowerpackDatasource.yaml
  datadog/tests/data_source_datadog_powerpack_test.go
  datadog/tests/provider_test.go
  docs/data-sources/powerpack.md
Labels: changelog/feature, editorial review

#2494 [provider] Bump datadog-api-client to latest master
  datadog/resource_datadog_synthetics_test_.go
  docs/resources/dashboard.md
  docs/resources/monitor.md
  docs/resources/powerpack.md
  go.mod
  go.sum
Labels: changelog/improvement

#2496 [datadog_provider] Reduce idle connection timeout
  datadog/fwprovider/framework_provider.go
  datadog/internal/utils/utils.go
  datadog/provider.go
Labels: changelog/improvement

#2498 bump SDK
  docs/resources/dashboard.md
  docs/resources/powerpack.md
  docs/resources/security_monitoring_rule.md
  go.mod
  go.sum
Labels: changelog/no-changelog

#2500 [datadog_webhook_custom_variable][datadog_webhook] migrate resources to framework
  .gitignore
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_webhook.go
  datadog/fwprovider/resource_datadog_webhook_custom_variable.go
  datadog/provider.go
  datadog/resource_datadog_webhook.go
  datadog/resource_datadog_webhook_custom_variable.go
  datadog/tests/resource_datadog_webhook_custom_variable_test.go
  datadog/tests/resource_datadog_webhook_test.go
Labels: changelog/no-changelog

#2497 [RUM] Update terraform definition with `rum_stream` for `data_source`
  datadog/tests/cassettes/TestAccDatadogDashboardListRumEvents.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardListRumEvents.yaml
  datadog/tests/resource_datadog_dashboard_list_stream_test.go
Labels: changelog/improvement

#2502 [datadog_integration_aws] Use AWS access key format in tests to pass validation
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSAccessKey.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSAccessKey.yaml
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSLambdaArnAccessKey.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSLambdaArnAccessKey.yaml
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSLogCollectionAccessKey.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSLogCollectionAccessKey.yaml
  datadog/tests/cassettes/TestAccDatadogIntegrationAwsTagFilter_BasicAccessKey.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAwsTagFilter_BasicAccessKey.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_integration_aws_tag_filter_test.go
Labels: changelog/no-changelog

#2503 [datadog_synthetics_test] prevent unnecessary marshalling unmarshalling of proto files / json descriptors
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsGRPCTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGRPCTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGRPCTest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGRPCTest_importBasic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/bugfix

#2505 [datadog_integration_azure_test] Fix azure tests to follow new backend validation
  datadog/tests/cassettes/TestAccDatadogIntegrationAzure.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAzure.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchiveAzure_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchiveAzure_basic.yaml
  datadog/tests/resource_datadog_integration_azure_test.go
  datadog/tests/resource_datadog_logs_archive_test.go
Labels: changelog/no-changelog

#2504 [datadog_apm_retention_filter] Adds doc and change example
  datadog/fwprovider/resource_datadog_apm_retention_filter.go
  docs/resources/apm_retention_filter.md
  examples/resources/datadog_apm_retention_filter/resource.tf
Labels: changelog/no-changelog

#2509 [datadog_ip_allowlist] add ip allowlist example
  docs/resources/ip_allowlist.md
  examples/resources/datadog_ip_allowlist/resource.tf
Labels: changelog/improvement, mergequeue-status: removed

#2511 [datadog_ip_allowlist] fix ip_allowlist code example error
  docs/resources/ip_allowlist.md
  examples/resources/datadog_ip_allowlist/resource.tf
Labels: changelog/no-changelog
