Repository DataDog/terraform-provider-datadog, pull requests merged in 2025-09, with the labels that each got.

#3216 [datadog_integration_aws_account] Fix missing double quotes breaking docs rendering
  docs/resources/integration_aws_account.md
Labels: changelog/documentation, resource/datadog_integration_aws_account

#3208 [datadog_security_monitoring_rule] Add has_optional_group_by_fields to security rule query
  datadog/data_source_datadog_security_monitoring_rules.go
  datadog/resource_datadog_security_monitoring_default_rule.go
  datadog/resource_datadog_security_monitoring_rule.go
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_AppsecRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_AppsecRule.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_CreateInvalidRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_CreateInvalidRule.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_CwsRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_CwsRule.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_DefaultTags.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_DefaultTags.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_Import.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_Import.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_ImpossibleTravelRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_ImpossibleTravelRule.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_InvalidTypes.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_NewValueRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_NewValueRule.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_OnlyRequiredFields.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_OnlyRequiredFields.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_SignalCorrelation.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_SignalCorrelation.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_ThirdParty.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_ThirdParty.yaml
  datadog/tests/cassettes/TestAccRestrictionPolicyBasic.freeze
  datadog/tests/cassettes/TestAccRestrictionPolicyBasic.yaml
  datadog/tests/cassettes/TestAccRestrictionPolicyInvalidInput.freeze
  datadog/tests/cassettes/TestAccRestrictionPolicyInvalidInput.yaml
  datadog/tests/cassettes/TestAccRestrictionPolicyUpdate.freeze
  datadog/tests/cassettes/TestAccRestrictionPolicyUpdate.yaml
  datadog/tests/resource_datadog_security_monitoring_rule_test.go
  docs/data-sources/security_monitoring_rules.md
  docs/resources/security_monitoring_default_rule.md
  docs/resources/security_monitoring_rule.md
Labels: changelog/no-changelog

#3220 [datadog_metric_tags] fix: data source incorrect metric name
  datadog/fwprovider/data_source_datadog_metric_tags.go
  datadog/tests/cassettes/TestAccDatadogMetricTagsDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogMetricTagsDatasource.yaml
Labels: changelog/bugfix, datasource/datadog_metric_tags

#3219 [datadog_integration_gcp][datadog_integration_gcp_sts] Add monitored_resource_configs to v1 and v2 terraform modules
  datadog/fwprovider/resource_datadog_integration_gcp.go
  datadog/fwprovider/resource_datadog_integration_gcp_sts.go
  datadog/tests/cassettes/TestAccDatadogIntegrationGCP.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationGCP.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchiveGCS_basic.yaml
  datadog/tests/cassettes/TestAccIntegrationGcpStsBasic.freeze
  datadog/tests/cassettes/TestAccIntegrationGcpStsBasic.yaml
  datadog/tests/cassettes/TestAccIntegrationGcpStsDefault.freeze
  datadog/tests/cassettes/TestAccIntegrationGcpStsDefault.yaml
  datadog/tests/resource_datadog_integration_gcp_sts_test.go
  datadog/tests/resource_datadog_integration_gcp_test.go
  docs/resources/integration_gcp.md
  docs/resources/integration_gcp_sts.md
  go.mod
  go.sum
Labels: changelog/feature, gcp-integrations

#3181 [datadog_security_monitoring_rule] Support Cloud SIEM scheduled rules
  datadog/resource_datadog_security_monitoring_rule.go
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRuleJSON_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRuleJSON_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_AppsecRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_AppsecRule.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_CreateInvalidRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_CreateInvalidRule.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_CwsRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_CwsRule.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_DefaultTags.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_DefaultTags.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_Import.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_Import.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_ImpossibleTravelRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_ImpossibleTravelRule.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_InvalidTypes.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_NewValueRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_NewValueRule.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_OnlyRequiredFields.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_OnlyRequiredFields.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_RemoveReferenceTables.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_RemoveReferenceTables.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_ScheduledRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_ScheduledRule.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_SignalCorrelation.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_SignalCorrelation.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_ThirdParty.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_ThirdParty.yaml
  datadog/tests/cassettes/TestAccRestrictionPolicyUpdate.freeze
  datadog/tests/cassettes/TestAccRestrictionPolicyUpdate.yaml
  datadog/tests/resource_datadog_security_monitoring_rule_test.go
  docs/data-sources/security_monitoring_rules.md
  docs/resources/security_monitoring_rule.md
Labels: changelog/feature

#3231 [datadog_restriction_policy] Update comment for usage with monitors
  datadog/fwprovider/resource_datadog_restriction_policy.go
  docs/resources/restriction_policy.md
Labels: changelog/documentation

#3229 [org_connection] Terraform Resource for Org Connection
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_org_connection.go
  datadog/internal/utils/api_instances_helper.go
  datadog/tests/cassettes/TestAccDatadogOrgConnection_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogOrgConnection_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogOrgConnection_InvalidInput.freeze
  datadog/tests/cassettes/TestAccDatadogOrgConnection_InvalidInput.yaml
  datadog/tests/cassettes/TestAccDatadogOrgConnection_Update.freeze
  datadog/tests/cassettes/TestAccDatadogOrgConnection_Update.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_org_connection_test.go
  docs/resources/org_connection.md
  examples/resources/datadog_org_connection/import.sh
  examples/resources/datadog_org_connection/resource.tf
Labels: changelog/feature

#3212 [datadog_security_monitoring_rule] Defer JSON filtering to Read to fix “inconsistent result after apply”
  datadog/fwprovider/resource_datadog_security_monitoring_rule_json.go
Labels: changelog/bugfix

#3235 [datadog_observability_pipeline] add Google PubSub destination
  datadog/fwprovider/resource_datadog_observability_pipeline.go
  datadog/tests/cassettes/TestAccDatadogObservabilityPipeline_googlePubSubDestination.freeze
  datadog/tests/cassettes/TestAccDatadogObservabilityPipeline_googlePubSubDestination.yaml
  datadog/tests/resource_datadog_observability_pipeline_test.go
  docs/resources/dashboard.md
  docs/resources/observability_pipeline.md
  docs/resources/powerpack.md
  docs/resources/security_monitoring_rule.md
  go.mod
  go.sum
Labels: changelog/feature

#3251 [SyntheticsGlobalVariableResource] Fix dynamic block parsing
  datadog/fwprovider/resource_datadog_synthetics_global_variable.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_DynamicBlocks.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_DynamicBlocks.yaml
  datadog/tests/resource_datadog_synthetics_global_variable_test.go
Labels: changelog/bugfix

#3252 [datadog_aws_cur_config] Add support for Cloud Cost AWS CUR Config resource and datasource
  .generator/src/generator/type.py
  datadog/fwprovider/data_source_datadog_aws_cur_config.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_aws_cur_config.go
  datadog/tests/cassettes/TestAccAwsCurConfigBasic.freeze
  datadog/tests/cassettes/TestAccAwsCurConfigBasic.yaml
  datadog/tests/cassettes/TestAccAwsCurConfigImport.freeze
  datadog/tests/cassettes/TestAccAwsCurConfigImport.yaml
  datadog/tests/cassettes/TestAccAwsCurConfigWithAccountFilters.freeze
  datadog/tests/cassettes/TestAccAwsCurConfigWithAccountFilters.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_aws_cur_config_test.go
  docs/data-sources/aws_cur_config.md
  docs/resources/aws_cur_config.md
  examples/resources/datadog_aws_cur_config/import.sh
  examples/resources/datadog_aws_cur_config/resource.tf
  go.mod
  go.sum
Labels: changelog/feature

#3255 [chore] Remove accidental replace for datadog-api-client-go in go.mod
  go.mod
Labels: changelog/no-changelog
