Repository DataDog/terraform-provider-datadog, pull requests merged in 2025-07, with the labels that each got.

#3079 [datadog_monitor_notification_rule] remove preview info notif rule
  datadog/fwprovider/resource_datadog_monitor_notification_rule.go
  docs/resources/monitor_notification_rule.md
Labels: changelog/documentation, resource/datadog_monitor_notification_rule

#3091 [datadog_synthetics_test] Add extract body email step
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.yaml
  docs/resources/synthetics_test.md
  go.mod
  go.sum
Labels: changelog/feature, resource/datadog_synthetics_test

#3106 [datadog_synthetics_test] Add append_to_content option for text input
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
Labels: changelog/feature, resource/datadog_synthetics_test

#3054 [app_key_registration] Add App Key Registration Resource
  .github/CODEOWNERS
  datadog/fwprovider/data_source_datadog_action_connection.go
  datadog/fwprovider/data_source_datadog_app_builder_app.go
  datadog/fwprovider/data_source_datadog_workflow_automation.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_action_connection.go
  datadog/fwprovider/resource_datadog_app_builder_app.go
  datadog/fwprovider/resource_datadog_app_key_registration.go
  datadog/fwprovider/resource_datadog_workflow_automation.go
  datadog/tests/cassettes/TestAccDatadogAppKeyRegistrationResource.freeze
  datadog/tests/cassettes/TestAccDatadogAppKeyRegistrationResource.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_app_key_registration_test.go
  docs/data-sources/action_connection.md
  docs/data-sources/app_builder_app.md
  docs/data-sources/workflow_automation.md
  docs/resources/action_connection.md
  docs/resources/app_builder_app.md
  docs/resources/app_key_registration.md
  docs/resources/workflow_automation.md
  examples/resources/datadog_app_key_registration/import.sh
  examples/resources/datadog_app_key_registration/resource.tf
Labels: changelog/feature

#3109 Fix app key registration test
  datadog/tests/cassettes/TestAccDatadogAppKeyRegistrationResource.yaml
  datadog/tests/resource_datadog_app_key_registration_test.go
Labels: changelog/no-changelog

#3066 [datadog_synthetics_test] Rewrite all `log.Printf` into `diags`
  datadog/resource_datadog_synthetics_test_.go
Labels: do-not-merge/WIP, changelog/improvement

#3119 [datadog_logs_pipelines] Updates Datadog Go API client to v2.43.0
  go.mod
  go.sum
Labels: changelog/improvement

#3118 [synthetics_test] Fix file upload issue in the terraform provider
  datadog/resource_datadog_synthetics_test_.go
Labels: changelog/bugfix, resource/datadog_synthetics_test

#3049 [datadog_synthetics_test] Add QoL feedback when converting multistep API test
  datadog/resource_datadog_synthetics_test_.go
  docs/resources/synthetics_test.md
Labels: changelog/improvement

#3127 [datadog_apm_retention_filter_order] docs: Fix typo
  docs/resources/apm_retention_filter_order.md
  examples/resources/datadog_apm_retention_filter_order/resource.tf
Labels: changelog/no-changelog, resource/datadog_apm_retention_filter_order

#3130 [datadog_observability_pipeline] Datadog Tags Processor
  datadog/fwprovider/observability_pipeline/custom_processor.go
  datadog/fwprovider/observability_pipeline/datadog_tags_processor.go
  datadog/fwprovider/resource_datadog_observability_pipeline.go
  datadog/tests/cassettes/TestAccDatadogObservabilityPipeline_customProcessor.freeze
  datadog/tests/cassettes/TestAccDatadogObservabilityPipeline_customProcessor.yaml
  datadog/tests/cassettes/TestAccDatadogObservabilityPipeline_datadogTagsProcessor.freeze
  datadog/tests/cassettes/TestAccDatadogObservabilityPipeline_datadogTagsProcessor.yaml
  datadog/tests/cassettes/TestAccDatadogObservabilityPipeline_remapVrlProcessor.freeze
  datadog/tests/cassettes/TestAccDatadogObservabilityPipeline_remapVrlProcessor.yaml
  datadog/tests/resource_datadog_observability_pipeline_test.go
  go.mod
  go.sum
Labels: changelog/feature

#3132 Remove web-frameworks as codeowners
  .github/CODEOWNERS
Labels: changelog/no-changelog
