Repository DataDog/terraform-provider-datadog, pull requests merged in 2025-08, with the labels that each got.

#3145 [datadog_observability_pipeline] add group_by to sample processor
  datadog/fwprovider/resource_datadog_observability_pipeline.go
  datadog/tests/cassettes/TestAccDatadogObservabilityPipeline_sampleProcessor.freeze
  datadog/tests/cassettes/TestAccDatadogObservabilityPipeline_sampleProcessor.yaml
  datadog/tests/resource_datadog_observability_pipeline_test.go
  go.mod
  go.sum
Labels: changelog/feature

#3150 [datadog_observability_pipeline] Amazon S3 Destination
  datadog/fwprovider/observability_pipeline/amazon_s3_destination.go
  datadog/fwprovider/observability_pipeline/aws_auth.go
  datadog/fwprovider/resource_datadog_observability_pipeline.go
  datadog/tests/resource_datadog_observability_pipeline_test.go
Labels: changelog/feature

#3155 [datadog_incident_type] Update incident type name in tests
  datadog/tests/cassettes/TestAccDatadogIncidentTypeDataSource_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogIncidentTypeDataSource_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogIncidentType_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogIncidentType_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogIncidentType_Import.freeze
  datadog/tests/cassettes/TestAccDatadogIncidentType_Import.yaml
  datadog/tests/cassettes/TestAccDatadogIncidentType_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogIncidentType_Updated.yaml
  datadog/tests/data_source_datadog_incident_type_test.go
  datadog/tests/resource_datadog_incident_type_test.go
Labels: changelog/no-changelog

#3125 [SEC_22455] Add support for decoder processor
  datadog/resource_datadog_logs_custom_pipeline.go
  datadog/tests/cassettes/TestAccDatadogLogsPipelineDefaultTags.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipelineDefaultTags.yaml
  datadog/tests/cassettes/TestAccDatadogLogsPipeline_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipeline_basic.yaml
  datadog/tests/cassettes/TestAccDatadogLogsPipeline_import.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipeline_import.yaml
  datadog/tests/resource_datadog_logs_custom_pipeline_test.go
  docs/resources/logs_custom_pipeline.md
  go.mod
  go.sum
Labels: changelog/improvement, resource/datadog_logs_custom_pipeline

#3160 [datadog_observability_pipeline] CrowdStrike Next-Gen SIEM Destination
  datadog/fwprovider/observability_pipeline/compression.go
  datadog/fwprovider/observability_pipeline/crowdstrike_next_gen_siem_destination.go
  datadog/fwprovider/resource_datadog_observability_pipeline.go
  datadog/tests/cassettes/TestAccDatadogObservabilityPipeline_crowdstrikeNextGenSiemDestination.freeze
  datadog/tests/cassettes/TestAccDatadogObservabilityPipeline_crowdstrikeNextGenSiemDestination.yaml
  datadog/tests/cassettes/TestAccDatadogObservabilityPipeline_crowdstrikeNextGenSiemDestination_basic.freeze
  datadog/tests/cassettes/TestAccDatadogObservabilityPipeline_crowdstrikeNextGenSiemDestination_basic.yaml
  datadog/tests/resource_datadog_observability_pipeline_test.go
Labels: changelog/feature

#3165 [datadog_observability_pipeline] make CustomProcessor `enabled` and `drop_on_error` fields required
  datadog/fwprovider/observability_pipeline/custom_processor.go
Labels: changelog/no-changelog

#3164 [datadog_agentless_scanning_aws_scan_options] Add Terraform provider for AWS scan options
  .github/CODEOWNERS
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_agentless_scanning_aws_scan_options.go
  datadog/internal/utils/api_instances_helper.go
  datadog/tests/cassettes/TestAccDatadogAgentlessScanningAwsScanOptions_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogAgentlessScanningAwsScanOptions_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogAgentlessScanningAwsScanOptions_Import.freeze
  datadog/tests/cassettes/TestAccDatadogAgentlessScanningAwsScanOptions_Import.yaml
  datadog/tests/cassettes/TestAccDatadogAgentlessScanningAwsScanOptions_Update.freeze
  datadog/tests/cassettes/TestAccDatadogAgentlessScanningAwsScanOptions_Update.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_agentless_scanning_aws_scan_options_test.go
  docs/resources/agentless_scanning_aws_scan_options.md
  examples/resources/datadog_agentless_scanning_aws_scan_options/import.sh
  examples/resources/datadog_agentless_scanning_aws_scan_options/resource.tf
Labels: changelog/feature, resource/datadog_agentless_scanning_aws_scan_optio

#3171 [workflow_automation] Clean up state if workflow not found
  datadog/fwprovider/data_source_datadog_workflow_automation.go
  datadog/fwprovider/resource_datadog_workflow_automation.go
Labels: changelog/bugfix

#3179 [DOCS] Add example for runApiTest browser_step type
  docs/resources/synthetics_test.md
  examples/resources/datadog_synthetics_test/resource.tf
Labels: resource/datadog_synthetics_test, changelog/documentation

#3173 [datadog_integration_aws_account] Add support for log_source_config
  datadog/fwprovider/resource_datadog_integration_aws_account.go
  datadog/tests/cassettes/TestAccIntegrationAwsAccountKeyBased.freeze
  datadog/tests/cassettes/TestAccIntegrationAwsAccountKeyBased.yaml
  datadog/tests/cassettes/TestAccIntegrationAwsAccount_InvalidEmptyTagFilters.freeze
  datadog/tests/cassettes/TestAccIntegrationAwsAccount_InvalidEmptyTagFilters.yaml
  datadog/tests/cassettes/TestAccIntegrationAwsAccount_OptionalLogSourceConfig.freeze
  datadog/tests/cassettes/TestAccIntegrationAwsAccount_OptionalLogSourceConfig.yaml
  datadog/tests/cassettes/TestAccIntegrationAwsAccount_RoleBased.freeze
  datadog/tests/cassettes/TestAccIntegrationAwsAccount_RoleBased.yaml
  datadog/tests/resource_datadog_integration_aws_account_test.go
  docs/resources/integration_aws_account.md
  examples/resources/datadog_integration_aws_account/resource.tf
Labels: changelog/feature

#3172 [datadog_service_account] Add pagination support for datadog_service_account data
  datadog/fwprovider/data_source_datadog_service_account.go
  datadog/tests/cassettes/TestAccDatadogServiceAccountDatasourceError.freeze
  datadog/tests/cassettes/TestAccDatadogServiceAccountDatasourceError.yaml
  datadog/tests/cassettes/TestAccDatadogServiceAccountDatasourceMatchFilter.freeze
  datadog/tests/cassettes/TestAccDatadogServiceAccountDatasourceMatchFilter.yaml
  datadog/tests/cassettes/TestAccDatadogServiceAccountDatasourcePagination.freeze
  datadog/tests/cassettes/TestAccDatadogServiceAccountDatasourcePagination.yaml
  datadog/tests/data_source_datadog_service_account_test.go
Labels: changelog/bugfix

#3184 [observability_pipelines] Add new options for overflow routing in quota processor in terraform
  datadog/fwprovider/resource_datadog_observability_pipeline.go
  datadog/tests/cassettes/TestAccDatadogObservabilityPipeline_quotaProcessor.freeze
  datadog/tests/cassettes/TestAccDatadogObservabilityPipeline_quotaProcessor.yaml
  datadog/tests/cassettes/TestAccDatadogObservabilityPipeline_quotaProcessor_overflowAction.freeze
  datadog/tests/cassettes/TestAccDatadogObservabilityPipeline_quotaProcessor_overflowAction.yaml
  datadog/tests/resource_datadog_observability_pipeline_test.go
  go.mod
  go.sum
Labels: changelog/feature

#3156 [datadog_integration_aws_account] Disable AWS/Usage metric collection by default
  datadog/fwprovider/resource_datadog_integration_aws_account.go
  datadog/tests/cassettes/TestAccIntegrationAwsAccountKeyBased.freeze
  datadog/tests/cassettes/TestAccIntegrationAwsAccountKeyBased.yaml
  datadog/tests/cassettes/TestAccIntegrationAwsAccount_OptionalLogSourceConfig.freeze
  datadog/tests/cassettes/TestAccIntegrationAwsAccount_OptionalLogSourceConfig.yaml
  datadog/tests/cassettes/TestAccIntegrationAwsAccount_RoleBased.freeze
  datadog/tests/cassettes/TestAccIntegrationAwsAccount_RoleBased.yaml
  datadog/tests/resource_datadog_integration_aws_account_test.go
  docs/resources/integration_aws_account.md
  examples/resources/datadog_integration_aws_account/resource.tf
Labels: changelog/feature

#3182 [datadog_on_call_team_routing_rules] Fix incorrect comment in import section of the documentation
  docs/resources/on_call_team_routing_rules.md
  examples/resources/datadog_on_call_team_routing_rules/import.sh
Labels: changelog/documentation, resource/datadog_on_call_team_routing_rules

#3189 [datadog_sensitive_data_scanner_group] Add support for SDS `should_save_match`
  .github/CODEOWNERS
  datadog/resource_datadog_sensitive_data_scanner_rule.go
  docs/resources/sensitive_data_scanner_rule.md
Labels: changelog/feature

#3190 [provider] Use latest stable terraform/opentofu in CI
  .github/ISSUE_TEMPLATE/01-bug-report.yml
  .github/workflows/test.yml
  .github/workflows/test_integration.yml
Labels: changelog/no-changelog
