Repository DataDog/terraform-provider-datadog, pull requests merged in 2025-06, with the labels that each got.

#3037 [Chore] Update the dependencies
  LICENSE-3rdparty.csv
  go.mod
  go.sum
Labels: changelog/note

#3042 [datadog_synthetics_test] Exclude TLS version types from being converted to number
  datadog/resource_datadog_synthetics_test_.go
Labels: changelog/bugfix, mergequeue-status: rejected

#3046 [on_call_escalation_policy] Add default for `resolve_page_on_policy_end`
  datadog/fwprovider/resource_datadog_on_call_escalation_policy.go
  datadog/tests/cassettes/TestAccOnCallEscalationPolicyCreateAndUpdate.freeze
  datadog/tests/cassettes/TestAccOnCallEscalationPolicyCreateAndUpdate.yaml
  datadog/tests/resource_datadog_on_call_escalation_policy_test.go
  datadog/tests/resource_datadog_on_call_escalation_policy_test.tf
  docs/resources/on_call_escalation_policy.md
Labels: changelog/no-changelog, mergequeue-status: in_progress

#3053 [synthetics_test] Add private location api key field
  datadog/fwprovider/resource_datadog_synthetics_private_location.go
  datadog/tests/resource_datadog_synthetics_private_location_test.go
  docs/resources/synthetics_private_location.md
Labels: changelog/feature

#3017 [datadog_monitor] add opt-in behavior on restricted_roles
  datadog/resource_datadog_monitor.go
  datadog/tests/cassettes/TestAccDatadogMonitor_WithRestrictionPolicy.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_WithRestrictionPolicy.yaml
  datadog/tests/data_source_datadog_monitor_test.go
  datadog/tests/resource_datadog_monitor_test.go
  docs/resources/monitor.md
Labels: changelog/improvement, resource/datadog_monitor, mergequeue-status: rejected

#3050 [APIR-1709][resource_datadog_integration_aws_account] Update docs for logs_config.lambda_forwarder.sources field
  datadog/fwprovider/resource_datadog_integration_aws_account.go
  docs/resources/integration_aws_account.md
Labels: changelog/documentation

#3048 [datadog_synthetics_test] Add `form` for `multipart/form-data` API tests
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsApiTest_FileUpload.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsApiTest_FileUpload.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_FileUpload.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_FileUpload.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
  go.mod
  go.sum
Labels: changelog/feature

#3062 [datadog_synthetics_test] Fix basic auth
  datadog/resource_datadog_synthetics_test_.go
  go.mod
  go.sum
Labels: changelog/bugfix, resource/datadog_synthetics_test

#3056 [datadog_csm_threats] adding hash action
  datadog/fwprovider/data_source_datadog_csm_threats_agent_rule.go
  datadog/fwprovider/resource_datadog_csm_threats_agent_rule.go
  datadog/tests/cassettes/TestAccCSMThreatsAgentRule_CreateAndUpdate.freeze
  datadog/tests/cassettes/TestAccCSMThreatsAgentRule_CreateAndUpdate.yaml
  datadog/tests/cassettes/TestAccCSMThreatsAgentRulesDataSource.freeze
  datadog/tests/cassettes/TestAccCSMThreatsAgentRulesDataSource.yaml
  datadog/tests/data_source_datadog_csm_threats_agent_rules_test.go
  datadog/tests/resource_datadog_csm_threats_agent_rule_test.go
  docs/data-sources/csm_threats_agent_rules.md
  docs/resources/csm_threats_agent_rule.md
Labels: changelog/no-changelog, mergequeue-status: in_progress

#3071 [datadog_synthetics_test] Fix browser step params element documentation
  datadog/resource_datadog_synthetics_test_.go
  docs/resources/synthetics_test.md
  examples/resources/datadog_synthetics_test/resource.tf
Labels: resource/datadog_synthetics_test, changelog/documentation

#3078 [datadog_on_call_escalation_policy] correctly set retries on update
  datadog/fwprovider/resource_datadog_on_call_escalation_policy.go
Labels: changelog/bugfix, mergequeue-status: in_progress

#3073 [datadog_synthetics_test] Fix link in assertion descriptions
  datadog/resource_datadog_synthetics_test_.go
  docs/resources/synthetics_test.md
Labels: mergequeue-status: in_progress, changelog/documentation

#3077 [on_call] update validation and documentation
  datadog/fwprovider/resource_datadog_on_call_escalation_policy.go
  datadog/fwprovider/resource_datadog_on_call_schedule.go
  datadog/fwprovider/resource_datadog_on_call_team_routing_rules.go
  docs/resources/on_call_schedule.md
  docs/resources/on_call_team_routing_rules.md
  scripts/generate-docs.sh
Labels: changelog/bugfix, mergequeue-status: in_progress, changelog/documentation

#3067 [synthetics_test] Fix provider crash due to absent 'relative_position' in config
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsMobileTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsMobileTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsMobileTest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsMobileTest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsMobileTest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsMobileTest_importBasic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/bugfix, resource/datadog_synthetics_test, mergequeue-status: in_progress
