Repository DataDog/terraform-provider-datadog, pull requests merged in 2025-03, with the labels that each got.

#2880 [datadog_integration_aws_external_id] Add new resource to generate an AWS Integration external ID
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_integration_aws_external_id.go
  datadog/tests/cassettes/TestAccIntegrationAwsExternalIDBasic.freeze
  datadog/tests/cassettes/TestAccIntegrationAwsExternalIDBasic.yaml
  datadog/tests/framework_provider_test.go
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_integration_aws_external_id_test.go
  docs/resources/integration_aws_external_id.md
  examples/resources/datadog_integration_aws_external_id/import.sh
  examples/resources/datadog_integration_aws_external_id/resource.tf
Labels: changelog/feature, mergequeue-status: in_progress

#2882 [datadog_dashboard] Remove duplicate accepted values in table cell display mode docs
  datadog/resource_datadog_dashboard.go
  docs/resources/dashboard.md
  docs/resources/powerpack.md
Labels: mergequeue-status: in_progress, changelog/documentation

#2874 [datadog_appsec] introduce the Application Security resources
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_appsec_waf_custom_rule.go
  datadog/fwprovider/resource_datadog_appsec_waf_exclusion_filter.go
  datadog/internal/utils/api_instances_helper.go
  datadog/tests/cassettes/TestAccAppsecWafCustomRuleBasic.freeze
  datadog/tests/cassettes/TestAccAppsecWafCustomRuleBasic.yaml
  datadog/tests/cassettes/TestAccAppsecWafExclusionFilterBasic.freeze
  datadog/tests/cassettes/TestAccAppsecWafExclusionFilterBasic.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_appsec_waf_custom_rule_test.go
  datadog/tests/resource_datadog_appsec_waf_exclusion_filter_test.go
  docs/resources/appsec_waf_custom_rule.md
  docs/resources/appsec_waf_exclusion_filter.md
  examples/resources/datadog_appsec_waf_custom_rule/import.sh
  examples/resources/datadog_appsec_waf_custom_rule/resource.tf
  examples/resources/datadog_appsec_waf_exclusion_filter/import.sh
  examples/resources/datadog_appsec_waf_exclusion_filter/resource.tf
  go.mod
  go.sum
Labels: new-resource, changelog/feature, mergequeue-status: in_progress

#2833 [datadog_workflow_automation] Add Workflows to Terraform
  .github/CODEOWNERS
  LICENSE-3rdparty.csv
  datadog/fwprovider/data_source_datadog_workflow_automation.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_workflow_automation.go
  datadog/internal/utils/api_instances_helper.go
  datadog/internal/utils/utils.go
  datadog/tests/cassettes/TestAccDatadogWorkflowAutomationDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogWorkflowAutomationDatasource.yaml
  datadog/tests/cassettes/TestAccDatadogWorkflowAutomationResource.freeze
  datadog/tests/cassettes/TestAccDatadogWorkflowAutomationResource.yaml
  datadog/tests/data_source_datadog_workflow_automation_test.go
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_workflow_automation_test.go
  docs/data-sources/workflow_automation.md
  docs/resources/workflow_automation.md
  examples/data-sources/datadog_workflow_automation/data-source.tf
  examples/resources/datadog_workflow_automation/import.sh
  examples/resources/datadog_workflow_automation/resource.tf
  go.mod
  go.sum
Labels: changelog/feature, mergequeue-status: in_progress

#2895 [datadog_security_monitoring_rule] Add group_signals_by and case actions
  datadog/resource_datadog_security_monitoring_rule.go
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_AppsecRule.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_AppsecRule.yaml
  datadog/tests/resource_datadog_security_monitoring_rule_test.go
  docs/data-sources/security_monitoring_rules.md
  docs/resources/security_monitoring_rule.md
Labels: changelog/feature, mergequeue-status: in_progress

#2890 [synthetics] Update doc with an example of file upload
  datadog/resource_datadog_synthetics_test_.go
  docs/resources/synthetics_test.md
  examples/resources/datadog_synthetics_test/resource.tf
Labels: mergequeue-status: in_progress, changelog/documentation

#2900 [resource_datadog_role] Update terraform docs to include default_permissions_opt_out attribute
  datadog/resource_datadog_role.go
  docs/resources/role.md
  scripts/generate-docs.sh
Labels: mergequeue-status: in_progress, changelog/documentation

#2894 [datadog_synthetics_test] Add `extractedValuesFromScript` to multistep API tests
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFromTest_LocalVariable.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFromTest_LocalVariable.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_FileUpload.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_FileUpload.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
Labels: changelog/feature, mergequeue-status: in_progress

#2892 [synthetics_private_location] Fix unremovable metadata bug
  datadog/fwprovider/resource_datadog_synthetics_private_location.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsPrivateLocation_importBasic.yaml
Labels: changelog/bugfix, resource/datadog_synthetics_private_location

#2884 [Generator] (feat) Added datasource generation
  .generator/README.md
  .generator/src/generator/cli.py
  .generator/src/generator/formatter.py
  .generator/src/generator/openapi.py
  .generator/src/generator/setup.py
  .generator/src/generator/templates/data_source/base.j2
  .generator/src/generator/templates/data_source/read.j2
  .generator/src/generator/templates/data_source/schema.j2
  .generator/src/generator/templates/data_source/state.j2
  .generator/src/generator/templates/data_source/types.j2
  .generator/src/generator/templates/read_method.j2
  .generator/src/generator/templates/update_state_method.j2
  .generator/src/generator/templates/utils/schema_helper.j2
  .generator/src/generator/templates/utils/state_helper.j2
  .generator/src/generator/type.py
  .generator/src/generator/utils.py
Labels: changelog/no-changelog

#2909 [Generator] (fix) Fixed the way the computed values are generated
  .generator/README.md
  .generator/src/generator/setup.py
  .generator/src/generator/templates/data_source/base.j2
  .generator/src/generator/templates/data_source/types.j2
  .generator/src/generator/type.py
  .generator/src/generator/utils.py
Labels: changelog/no-changelog

#2910 [Generator] (fix) Made resources and datasource optional
  .generator/src/generator/openapi.py
Labels: changelog/no-changelog

#2914 Assign correct ownership for collaboration-integrations
  .github/CODEOWNERS
Labels: changelog/no-changelog

#2886 [synthetics_global_variable] Migrate synthetics resource and data_source to framework
  datadog/data_source_datadog_synthetics_global_variable.go
  datadog/fwprovider/data_source_datadog_synthetics_global_variable.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_synthetics_global_variable.go
  datadog/provider.go
  datadog/resource_datadog_synthetics_global_variable.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFIDO_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFIDO_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFIDO_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFIDO_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFromTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFromTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFromTest_LocalVariable.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFromTest_LocalVariable.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableSecure_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableSecure_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableSecure_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableSecure_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableTOTP_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableTOTP_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableTOTP_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableTOTP_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariable_importBasic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.yaml
  datadog/tests/data_source_datadog_synthetics_global_variable_test.go
  datadog/tests/data_source_datadog_synthetics_test_test.go
  datadog/tests/resource_datadog_synthetics_global_variable_test.go
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_global_variable.md
  examples/resources/datadog_synthetics_global_variable/resource.tf
Labels: changelog/improvement, resource/datadog_synthetics_global_variable

#2911 [datadog_synthetics_test] Deprecate restricted_roles and bindings in synthetics test configuration doc
  datadog/tests/cassettes/TestAccDatadogSyntheticsMobileTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsMobileTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsMobileTest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsMobileTest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsMobileTest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsMobileTest_importBasic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
  examples/resources/datadog_synthetics_test/resource.tf
Labels: changelog/no-changelog, resource/datadog_synthetics_test

#2907 [datadog_webhook] Handle unknown encode_as on update
  datadog/fwprovider/resource_datadog_webhook.go
  datadog/tests/cassettes/TestAccDatadogWebhook_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogWebhook_Basic.yaml
  datadog/tests/resource_datadog_webhook_test.go
Labels: changelog/bugfix, resource/datadog_webhook

#2922 [datadog_metric_metadata] Fix drift on imported resources
  datadog/resource_datadog_metric_metadata.go
Labels: changelog/bugfix

#2906 [datadog_spans_metric] Suppress unknown include_percentiles state
  datadog/fwprovider/resource_datadog_spans_metric.go
  datadog/tests/resource_datadog_spans_metric_test.go
Labels: changelog/bugfix, resource/datadog_spans_metrics

#2924 [datadog_azure_integration] Fix import command
  datadog/fwprovider/resource_datadog_azure_integration.go
  datadog/tests/cassettes/TestAccDatadogIntegrationAzure_import.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAzure_import.yaml
  datadog/tests/resource_datadog_integration_azure_test.go
  docs/resources/integration_azure.md
  examples/resources/datadog_integration_azure/import.sh
Labels: changelog/bugfix

#2921 Bumps terraform libraries
  LICENSE-3rdparty.csv
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_synthetics_global_variable.go
  datadog/internal/fwutils/modify_plan.go
  datadog/tests/cassettes/TestAccDatadogActionConnectionDatasource_AWS_AssumeRole.freeze
  datadog/tests/cassettes/TestAccDatadogActionConnectionDatasource_AWS_AssumeRole.yaml
  datadog/tests/cassettes/TestAccDatadogApmRetentionFilterOrder.freeze
  datadog/tests/cassettes/TestAccDatadogApmRetentionFilterOrder.yaml
  datadog/tests/cassettes/TestAccDatadogWorkflowAutomationDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogWorkflowAutomationDatasource.yaml
  go.mod
  go.sum
Labels: changelog/no-changelog

#2570 Set more specific GitHub token permissions on workflows.
  .github/workflows/changelog.yaml
  .github/workflows/prepare_release.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/test_integration.yml
Labels: changelog/no-changelog

#2875 [datadog_logs_archive] Added storage class to s3 archive terraform provider
  datadog/resource_datadog_logs_archive.go
  datadog/tests/cassettes/TestAccDatadogLogsArchiveS3Update_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchiveS3Update_basic.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchiveS3_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchiveS3_basic.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchivesOrderDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchivesOrderDatasource.yaml
  datadog/tests/resource_datadog_logs_archive_test.go
  docs/resources/logs_archive.md
  go.mod
  go.sum
Labels: changelog/feature, resource/datadog_logs_archive, mergequeue-status: in_progress

#2723 [datadog_app_builder_app] Add App Builder Terraform Support
  .github/CODEOWNERS
  datadog/fwprovider/data_source_datadog_app_builder_app.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_app_builder_app.go
  datadog/internal/utils/api_instances_helper.go
  datadog/internal/utils/utils.go
  datadog/internal/utils/utils_test.go
  datadog/tests/cassettes/TestAccDatadogAppBuilderAppDataSource_Inline_WithOptionalFields.freeze
  datadog/tests/cassettes/TestAccDatadogAppBuilderAppDataSource_Inline_WithOptionalFields.yaml
  datadog/tests/cassettes/TestAccDatadogAppBuilderAppResource_Escaped_Interpolated.freeze
  datadog/tests/cassettes/TestAccDatadogAppBuilderAppResource_Escaped_Interpolated.yaml
  datadog/tests/cassettes/TestAccDatadogAppBuilderAppResource_Escaped_Interpolated_Import.freeze
  datadog/tests/cassettes/TestAccDatadogAppBuilderAppResource_Escaped_Interpolated_Import.yaml
  datadog/tests/cassettes/TestAccDatadogAppBuilderAppResource_FromFile.freeze
  datadog/tests/cassettes/TestAccDatadogAppBuilderAppResource_FromFile.yaml
  datadog/tests/cassettes/TestAccDatadogAppBuilderAppResource_FromFile_Import.freeze
  datadog/tests/cassettes/TestAccDatadogAppBuilderAppResource_FromFile_Import.yaml
  datadog/tests/cassettes/TestAccDatadogAppBuilderAppResource_Inline_WithOptionalFields.freeze
  datadog/tests/cassettes/TestAccDatadogAppBuilderAppResource_Inline_WithOptionalFields.yaml
  datadog/tests/cassettes/TestAccDatadogAppBuilderAppResource_Inline_WithOptionalFields_Import.freeze
  datadog/tests/cassettes/TestAccDatadogAppBuilderAppResource_Inline_WithOptionalFields_Import.yaml
  datadog/tests/data_source_datadog_app_builder_app_test.go
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_app_builder_app_test.go
  docs/data-sources/app_builder_app.md
  docs/resources/app_builder_app.md
  examples/data-sources/datadog_app_builder_app/data-source.tf
  examples/resources/datadog_app_builder_app/import.sh
  examples/resources/datadog_app_builder_app/resource.json
  examples/resources/datadog_app_builder_app/resource.tf
  go.mod
  go.sum
Labels: new-resource, new-data-source, changelog/feature, mergequeue-status: removed, resource/datadog_app_builder_app

#2935 Remove need for github-token when validating PR title
  .github/workflows/changelog.yaml
Labels: changelog/no-changelog

#2930 [Doc] (feat) added description enrichment for more validators
  datadog/fwprovider/resource_datadog_software_catalog.go
  datadog/internal/fwutils/fw_enrich_schema.go
  datadog/internal/fwutils/fw_enrich_schema_test.go
  datadog/internal/validators/entity_yaml_validator.go
  datadog/internal/validators/validators.go
  datadog/internal/validators/validators_test.go
  docs/resources/action_connection.md
  docs/resources/apm_retention_filter.md
  docs/resources/app_builder_app.md
  docs/resources/ip_allowlist.md
  docs/resources/software_catalog.md
  docs/resources/synthetics_concurrency_cap.md
  docs/resources/synthetics_global_variable.md
  docs/resources/workflow_automation.md
Labels: documentation, changelog/no-changelog

#2822 [data_source_datadog_software_catalog] Adding Software Catalog data source
  datadog/fwprovider/data_source_datadog_software_catalog.go
  datadog/fwprovider/framework_provider.go
  datadog/internal/utils/api_instances_helper.go
  datadog/tests/cassettes/TestAccDatadogSoftwareCatalogEntity_Datasource.freeze
  datadog/tests/cassettes/TestAccDatadogSoftwareCatalogEntity_Datasource.yaml
  datadog/tests/data_source_datadog_software_catalog_test.go
  datadog/tests/provider_test.go
  docs/data-sources/software_catalog.md
  examples/data-sources/datadog_software_catalog/data-source.tf
Labels: new-data-source, changelog/feature

#2934 [datadog_rum_metric] Set `tag_name` parameter as computed
  datadog/fwprovider/resource_datadog_rum_metric.go
  datadog/tests/cassettes/TestAccRumMetricAttributes.freeze
  datadog/tests/cassettes/TestAccRumMetricAttributes.yaml
  datadog/tests/resource_datadog_rum_metric_test.go
Labels: changelog/bugfix

#2937 Remove duplicate permissions
  .github/workflows/release.yml
Labels: changelog/no-changelog

#2936 [datadog_rum_metric] Fix issue with rum metric resource.
  datadog/fwprovider/resource_datadog_rum_metric.go
  datadog/tests/cassettes/TestAccRumMetricAttributes.freeze
  datadog/tests/cassettes/TestAccRumMetricAttributes.yaml
  datadog/tests/resource_datadog_rum_metric_test.go
Labels: changelog/bugfix, mergequeue-status: in_progress, resource/datadog_rum_metric
