Repository DataDog/terraform-provider-datadog, pull requests merged in 2025-10, with the labels that each got.

#3253 [datadog_synthetics_test] Forbid empty locations for browser and API synthetic tests
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_EmptyLocations.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_EmptyLocations.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_EmptyLocations.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_EmptyLocations.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
Labels: changelog/improvement

#3239 [datadog_security_monitoring_rule] Add sequence detection method to security monitoring rule resource
  datadog/resource_datadog_security_monitoring_rule.go
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_SequenceDetection.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityMonitoringRule_SequenceDetection.yaml
  datadog/tests/resource_datadog_security_monitoring_rule_test.go
  docs/data-sources/security_monitoring_rules.md
  docs/resources/security_monitoring_rule.md
  go.mod
  go.sum
Labels: changelog/feature

#3263 [datadog_azure_uc_config] Add support for Cloud Cost Azure Cloud Usage Cost Config resource and data source
  datadog/fwprovider/data_source_datadog_azure_uc_config.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_aws_cur_config.go
  datadog/fwprovider/resource_datadog_azure_uc_config.go
  datadog/fwprovider/resource_datadog_gcp_uc_config.go
  datadog/tests/cassettes/TestAccAzureUcConfigBasic.freeze
  datadog/tests/cassettes/TestAccAzureUcConfigBasic.yaml
  datadog/tests/cassettes/TestAccAzureUcConfigImport.freeze
  datadog/tests/cassettes/TestAccAzureUcConfigImport.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_azure_uc_config_test.go
  docs/data-sources/azure_uc_config.md
  docs/resources/azure_uc_config.md
  examples/resources/datadog_azure_uc_config/import.sh
  examples/resources/datadog_azure_uc_config/resource.tf
Labels: changelog/bugfix, changelog/feature

#3261 [datadog_integration_aws_iam_permissions_standard] Add new data source for AWS Integration standard IAM permissions
  datadog/fwprovider/data_source_datadog_integration_aws_iam_permissions_standard.go
  datadog/fwprovider/framework_provider.go
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSIAMPermissionsStandardDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAWSIAMPermissionsStandardDatasource.yaml
  datadog/tests/data_source_datadog_integration_aws_iam_permissions_standard_test.go
  datadog/tests/provider_test.go
  docs/data-sources/integration_aws_iam_permissions_standard.md
Labels: changelog/feature

#3236 [datadog_tag_pipeline_ruleset] terraform support for tag-pipeline
  datadog/fwprovider/data_source_datadog_tag_pipeline_ruleset.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_tag_pipeline_ruleset.go
  datadog/fwprovider/resource_datadog_tag_pipeline_rulesets.go
  datadog/tests/cassettes/TestAccDatadogTagPipelineRulesetDataSource_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogTagPipelineRulesetDataSource_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogTagPipelineRulesetDataSource_MappingRule.freeze
  datadog/tests/cassettes/TestAccDatadogTagPipelineRulesetDataSource_MappingRule.yaml
  datadog/tests/cassettes/TestAccDatadogTagPipelineRulesetDataSource_ReferenceTableRule.freeze
  datadog/tests/cassettes/TestAccDatadogTagPipelineRulesetDataSource_ReferenceTableRule.yaml
  datadog/tests/cassettes/TestAccDatadogTagPipelineRuleset_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogTagPipelineRuleset_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogTagPipelineRuleset_Import.freeze
  datadog/tests/cassettes/TestAccDatadogTagPipelineRuleset_Import.yaml
  datadog/tests/cassettes/TestAccDatadogTagPipelineRuleset_MappingRule.freeze
  datadog/tests/cassettes/TestAccDatadogTagPipelineRuleset_MappingRule.yaml
  datadog/tests/cassettes/TestAccDatadogTagPipelineRuleset_MultipleRules.freeze
  datadog/tests/cassettes/TestAccDatadogTagPipelineRuleset_MultipleRules.yaml
  datadog/tests/cassettes/TestAccDatadogTagPipelineRuleset_QueryRule.freeze
  datadog/tests/cassettes/TestAccDatadogTagPipelineRuleset_QueryRule.yaml
  datadog/tests/cassettes/TestAccDatadogTagPipelineRuleset_ReferenceTableRule.freeze
  datadog/tests/cassettes/TestAccDatadogTagPipelineRuleset_ReferenceTableRule.yaml
  datadog/tests/cassettes/TestAccDatadogTagPipelineRuleset_Update.freeze
  datadog/tests/cassettes/TestAccDatadogTagPipelineRuleset_Update.yaml
  datadog/tests/cassettes/TestAccDatadogTagPipelineRulesets_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogTagPipelineRulesets_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogTagPipelineRulesets_Import.freeze
  datadog/tests/cassettes/TestAccDatadogTagPipelineRulesets_Import.yaml
  datadog/tests/cassettes/TestAccDatadogTagPipelineRulesets_SingleRuleset.freeze
  datadog/tests/cassettes/TestAccDatadogTagPipelineRulesets_SingleRuleset.yaml
  datadog/tests/cassettes/TestAccDatadogTagPipelineRulesets_Update.freeze
  datadog/tests/cassettes/TestAccDatadogTagPipelineRulesets_Update.yaml
  datadog/tests/data_source_datadog_tag_pipeline_ruleset_test.go
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_tag_pipeline_ruleset_test.go
  datadog/tests/resource_datadog_tag_pipeline_rulesets_test.go
  docs/data-sources/tag_pipeline_ruleset.md
  docs/resources/tag_pipeline_ruleset.md
  docs/resources/tag_pipeline_rulesets.md
  examples/resources/datadog_tag_pipeline_ruleset/import.sh
  examples/resources/datadog_tag_pipeline_ruleset/resource.tf
  examples/resources/datadog_tag_pipeline_rulesets/import.sh
  examples/resources/datadog_tag_pipeline_rulesets/resource.tf
Labels: changelog/feature

#3269 [datadog_csm_threats] Fix csm threats agent rule expression whitespace inconsistency
  datadog/fwprovider/resource_datadog_csm_threats_agent_rule.go
Labels: changelog/bugfix
