Repository DataDog/terraform-provider-datadog, pull requests merged in 2025-02, with the labels that each got.

#2740 [datadog_logs_archives] Handle encryption field for S3 destinations for Logs Archives
  datadog/resource_datadog_logs_archive.go
  datadog/tests/cassettes/TestAccDatadogLogsArchiveOrder_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchiveOrder_basic.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchiveOrder_empty.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchiveOrder_empty.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchiveS3Update_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchiveS3Update_basic.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchiveS3_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchiveS3_basic.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchivesOrderDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchivesOrderDatasource.yaml
  datadog/tests/cassettes/TestAccDatadogLogsPipeline_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipeline_basic.yaml
  datadog/tests/cassettes/TestAccDatadogLogsPipeline_import.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipeline_import.yaml
  datadog/tests/resource_datadog_logs_archive_test.go
  docs/resources/logs_archive.md
  go.mod
  go.sum
Labels: changelog/improvement

#2707 [datadog_spans_metric] Mark `include_percentiles` property as computed
  datadog/fwprovider/resource_datadog_spans_metric.go
  datadog/tests/cassettes/TestAccSpansMetricBasic.freeze
  datadog/tests/cassettes/TestAccSpansMetricBasic.yaml
  datadog/tests/cassettes/TestAccSpansMetricGroupBys.freeze
  datadog/tests/cassettes/TestAccSpansMetricGroupBys.yaml
  datadog/tests/cassettes/TestAccSpansMetric_import.freeze
  datadog/tests/cassettes/TestAccSpansMetric_import.yaml
Labels: changelog/bugfix

#2050 Add framework resource generator helper
  .generator/README.md
  .generator/poetry.lock
  .generator/pyproject.toml
  .generator/src/generator/__init__.py
  .generator/src/generator/__main__.py
  .generator/src/generator/cli.py
  .generator/src/generator/formatter.py
  .generator/src/generator/openapi.py
  .generator/src/generator/templates/base_resource.j2
  .generator/src/generator/templates/create_method.j2
  .generator/src/generator/templates/delete_method.j2
  .generator/src/generator/templates/read_method.j2
  .generator/src/generator/templates/request_builder.j2
  .generator/src/generator/templates/resource_example.j2
  .generator/src/generator/templates/resource_import_example.j2
  .generator/src/generator/templates/resource_test.j2
  .generator/src/generator/templates/schema.j2
  .generator/src/generator/templates/types.j2
  .generator/src/generator/templates/update_method.j2
  .generator/src/generator/templates/update_state_method.j2
  .generator/src/generator/templates/utils/request_builder_helper.j2
  .generator/src/generator/templates/utils/resource_test_helper.j2
  .generator/src/generator/templates/utils/schema_helper.j2
  .generator/src/generator/templates/utils/state_helper.j2
  .generator/src/generator/templates/utils/types_helper.j2
  .generator/src/generator/utils.py
  .github/CODEOWNERS
  .gitignore
Labels: changelog/no-changelog, mergequeue-status: in_progress

#2761 [datadog_service_account] Fix : `roles` attribute is now always updated
  datadog/fwprovider/resource_datadog_service_account.go
Labels: changelog/bugfix

#2804 Update documentation guidelines
  DEVELOPMENT.md
Labels: changelog/no-changelog

#2802 [datadog_service_definition_yaml] Fix panic when contact attributes exists but are empty (nil)
  datadog/resource_datadog_service_definition_yaml.go
Labels: changelog/bugfix

#2768 [datadog_synthetics_global_variable] Remove drift on `option` argument
  datadog/resource_datadog_synthetics_global_variable.go
Labels: changelog/bugfix

#2812 check comparison instead of equality
  datadog/resource_datadog_service_definition_yaml.go
  go.mod
  go.sum
Labels: changelog/no-changelog

#2810 Bump datadog-api-client to v2.35.0
  go.mod
  go.sum
Labels: changelog/note

#2809 [TIDY] (generator) Refactor the generator
  .generator/src/generator/cli.py
  .generator/src/generator/setup.py
  .generator/src/generator/templates/delete_method.j2
  .generator/src/generator/utils.py
Labels: changelog/no-changelog, mergequeue-status: in_progress

#2819 [TIDY] (generator) Remove unused classes
  .generator/src/generator/openapi.py
Labels: changelog/no-changelog, mergequeue-status: in_progress

#2784 [datadog_user] Fix the `name` field as Optional + Computed
  datadog/resource_datadog_user.go
  docs/resources/user.md
Labels: changelog/bugfix

#2786 [datadog_users] Add attributes to `datadog_users` datasource
  .github/CODEOWNERS
  datadog/fwprovider/data_source_datadog_users.go
  datadog/tests/data_source_datadog_users_test.go
  datadog/tests/utils_test.go
  docs/data-sources/users.md
Labels: changelog/improvement

#2823 [TIDY] (generator) Moved type related functions to their own file
  .generator/src/generator/openapi.py
  .generator/src/generator/setup.py
  .generator/src/generator/type.py
Labels: changelog/no-changelog, mergequeue-status: in_progress

#2818 [datadog_synthetics_test] Add secure field for extractFromJavascript browser step variables
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTestBrowserNewBrowserStep_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTestBrowserNewBrowserStep_Basic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
Labels: changelog/feature, mergequeue-status: in_progress

#2789 [datadog_teams] Add new datasource
  datadog/fwprovider/data_source_datadog_teams.go
  datadog/fwprovider/framework_provider.go
  datadog/tests/cassettes/TestAccDatadogTeamsDatasourceFilterKeyword.freeze
  datadog/tests/cassettes/TestAccDatadogTeamsDatasourceFilterKeyword.yaml
  datadog/tests/data_source_datadog_teams_test.go
  datadog/tests/provider_test.go
  docs/data-sources/teams.md
  examples/data-sources/datadog_teams/data-source.tf
Labels: changelog/feature, mergequeue-status: in_progress

#2828 [Generator] (fix) Fixed schema generation
  .generator/src/generator/templates/utils/state_helper.j2
  .generator/src/generator/type.py
Labels: changelog/no-changelog

#2806 [resource_datadog_security_notification_rule] Add notification rule terraform provider
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_security_notification_rule.go
  datadog/tests/cassettes/TestAccDatadogSecurityNotificationRuleFull.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityNotificationRuleFull.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityNotificationRuleSignalRuleSimple.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityNotificationRuleSignalRuleSimple.yaml
  datadog/tests/cassettes/TestAccDatadogSecurityNotificationRuleVulnerabilityRuleSimple.freeze
  datadog/tests/cassettes/TestAccDatadogSecurityNotificationRuleVulnerabilityRuleSimple.yaml
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_security_notification_rule_test.go
  docs/resources/security_notification_rule.md
  examples/resources/datadog_security_notification_rule/import.sh
  examples/resources/datadog_security_notification_rule/resource.tf
Labels: changelog/feature, mergequeue-status: in_progress

#2835 [Generator] (fix) Removed `output` parameter
  .generator/src/generator/cli.py
Labels: changelog/no-changelog

#2831 [datadog_api_key] Support `remote_config_read_enabled` argument
  datadog/fwprovider/data_source_datadog_api_key.go
  datadog/fwprovider/data_source_datadog_teams.go
  datadog/fwprovider/resource_datadog_api_key.go
  datadog/tests/resource_datadog_api_key_test.go
  docs/data-sources/api_key.md
  docs/resources/api_key.md
Labels: changelog/feature

#2820 [datadog_synthetics_test] Add renotify occurrences option
  datadog/resource_datadog_synthetics_test_.go
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTestBrowserNewBrowserStep_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTestBrowserNewBrowserStep_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_Updated_RumSettings.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsBrowserTest_importBasic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFromTest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFromTest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFromTest_LocalVariable.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsGlobalVariableFromTest_LocalVariable.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserMML_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestBrowserMML_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.yaml
  datadog/tests/resource_datadog_synthetics_test_test.go
  docs/resources/synthetics_test.md
Labels: changelog/feature, mergequeue-status: in_progress

#2841 Fix generator to take in account `required` / `enum` / `read_only` / `nullable` cases
  .generator/src/generator/setup.py
  .generator/src/generator/templates/utils/request_builder_helper.j2
  .generator/src/generator/templates/utils/resource_test_helper.j2
  .generator/src/generator/templates/utils/schema_helper.j2
  .generator/src/generator/templates/utils/state_helper.j2
  .generator/src/generator/utils.py
Labels: changelog/no-changelog

#2839 [generator] fixes for generate_resource
  .generator/src/generator/cli.py
Labels: changelog/no-changelog

#2852 [datadog_synthetics_global_variable] Fix cassettes for tests
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_AdvancedScheduling.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_AdvancedScheduling.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Basic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Updated.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_Updated.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertionsOptions.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsAPITest_importBasic.yaml
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.freeze
  datadog/tests/cassettes/TestAccDatadogSyntheticsTestMultistepApi_Basic.yaml
Labels: changelog/no-changelog

#2787 [datadog_user] Add computed attributes to `datadog_user` datasource
  datadog/data_source_datadog_user.go
  docs/data-sources/user.md
Labels: changelog/improvement

#2845 [datadog_logs_custom_pipeline] Add support for default tags in log pipelines
  datadog/fwprovider/framework_provider.go
  datadog/provider.go
  datadog/resource_datadog_logs_custom_pipeline.go
  datadog/tests/cassettes/TestAccDatadogLogsPipelineDefaultTags.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipelineDefaultTags.yaml
  datadog/tests/cassettes/TestAccDatadogLogsPipeline_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipeline_basic.yaml
  datadog/tests/resource_datadog_logs_custom_pipeline_test.go
  docs/index.md
Labels: changelog/improvement

#2855 [global] Co-ownership of terraform provider
  .github/CODEOWNERS
Labels: changelog/no-changelog

#2853 [resource_datadog_security_notification_rule] Update security_notification_rule documentation
  datadog/fwprovider/resource_datadog_security_notification_rule.go
  docs/resources/security_notification_rule.md
  examples/resources/datadog_security_notification_rule/resource.tf
Labels: changelog/documentation

#2858 [datadog_dashboard] Add dashboard unit support
  datadog/resource_datadog_dashboard.go
  datadog/tests/cassettes/TestAccDatadogDashboardQueryTableFormula.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardQueryTableFormula.yaml
  datadog/tests/cassettes/TestAccDatadogDashboardQueryTableFormula_import.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardQueryTableFormula_import.yaml
  datadog/tests/resource_datadog_dashboard_query_table_test.go
  docs/resources/dashboard.md
  docs/resources/powerpack.md
  docs/resources/synthetics_test.md
  go.mod
  go.sum
Labels: changelog/improvement

#2857 [datadog_api_key] Fix bug introduced in 3.55.0 for organisation that doesn't have Remove config enabled
  datadog/fwprovider/resource_datadog_api_key.go
  datadog/tests/resource_datadog_api_key_test.go
  docs/resources/api_key.md
Labels: changelog/bugfix

#2856 [SEC-17676] Update TF documentation for evaluation_window and keep_alive for Security monitoring rule.
  docs/resources/dashboard.md
  docs/resources/powerpack.md
  docs/resources/security_monitoring_rule.md
  go.mod
  go.sum
Labels: changelog/no-changelog

#2863 [datadog_openapi_api] Deprecate openapi resource
  datadog/fwprovider/resource_datadog_openapi_api.go
  docs/resources/openapi_api.md
Labels: changelog/note

#2861 [datadog_logs_custom_pipeline] Manage `span-id-remapper` processor
  datadog/resource_datadog_logs_custom_pipeline.go
  datadog/tests/cassettes/TestAccDatadogLogsPipelineDefaultTags.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipelineDefaultTags.yaml
  datadog/tests/cassettes/TestAccDatadogLogsPipelineEmptyFilterQuery.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipelineEmptyFilterQuery.yaml
  datadog/tests/cassettes/TestAccDatadogLogsPipeline_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipeline_basic.yaml
  datadog/tests/cassettes/TestAccDatadogLogsPipeline_import.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipeline_import.yaml
  datadog/tests/cassettes/TestAccDatadogLogsPipelinesDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipelinesDatasource.yaml
  datadog/tests/cassettes/TestAccDatadogLogsPipelinesDatasourceReadonly.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipelinesDatasourceReadonly.yaml
  datadog/tests/cassettes/TestAccDatadogLogsPipelinesOrderDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipelinesOrderDatasource.yaml
  datadog/tests/resource_datadog_logs_custom_pipeline_test.go
  docs/resources/logs_custom_pipeline.md
Labels: changelog/improvement

#2862 [datadog_dashboard] Add `scaling` argument for style of `toplist_definition` widget
  datadog/resource_datadog_dashboard.go
  datadog/tests/cassettes/TestAccDatadogDashboardTopListWithStyle.freeze
  datadog/tests/cassettes/TestAccDatadogDashboardTopListWithStyle.yaml
  datadog/tests/resource_datadog_dashboard_top_list_test.go
  docs/resources/dashboard.md
  docs/resources/powerpack.md
Labels: changelog/improvement

#2866 [resource_datadog_integration_aws*] Update documentation to highlight deprecated resources
  datadog/resource_datadog_dashboard.go
  datadog/resource_datadog_integration_aws.go
  datadog/resource_datadog_integration_aws_lambda_arn.go
  datadog/resource_datadog_integration_aws_log_collection.go
  datadog/resource_datadog_integration_aws_tag_filter.go
  datadog/utils.go
  docs/resources/integration_aws.md
  docs/resources/integration_aws_lambda_arn.md
  docs/resources/integration_aws_log_collection.md
  docs/resources/integration_aws_tag_filter.md
Labels: changelog/no-changelog

#2821 [datadog_restriction_policy] Add doc for restriction policy
  datadog/fwprovider/resource_datadog_restriction_policy.go
  datadog/resource_datadog_synthetics_global_variable.go
  datadog/resource_datadog_synthetics_private_location.go
  datadog/resource_datadog_synthetics_test_.go
  docs/resources/restriction_policy.md
  docs/resources/synthetics_global_variable.md
  docs/resources/synthetics_private_location.md
  docs/resources/synthetics_test.md
Labels: changelog/documentation

#2867 [Generator] (fix) Support date-time format enrichment
  .generator/src/generator/formatter.py
  .generator/src/generator/setup.py
  .generator/src/generator/templates/utils/state_helper.j2
  .generator/src/generator/utils.py
Labels: changelog/no-changelog

#2811 Run entire test suite for all PR's
  .github/workflows/test.yml
Labels: changelog/no-changelog

#2871 [datadog_synthetics_test] Only set renotify_occurrences if renotify_interval is set
  datadog/resource_datadog_synthetics_test_.go
Labels: changelog/bugfix, mergequeue-status: in_progress

#2718 [datadog_action_connection] ACTP-104 Terraform provider for Connections API
  .github/CODEOWNERS
  datadog/fwprovider/data_source_datadog_action_connection.go
  datadog/fwprovider/framework_provider.go
  datadog/fwprovider/resource_datadog_action_connection.go
  datadog/internal/utils/api_instances_helper.go
  datadog/tests/cassettes/TestAccDatadogActionConnectionDatasource_AWS_AssumeRole.freeze
  datadog/tests/cassettes/TestAccDatadogActionConnectionDatasource_AWS_AssumeRole.yaml
  datadog/tests/cassettes/TestAccDatadogActionConnectionResource_AWS_AssumeRole.freeze
  datadog/tests/cassettes/TestAccDatadogActionConnectionResource_AWS_AssumeRole.yaml
  datadog/tests/cassettes/TestAccDatadogActionConnectionResource_HTTP_TokenAuth.freeze
  datadog/tests/cassettes/TestAccDatadogActionConnectionResource_HTTP_TokenAuth.yaml
  datadog/tests/data_source_datadog_action_connection_test.go
  datadog/tests/provider_test.go
  datadog/tests/resource_datadog_action_connection_test.go
  docs/data-sources/action_connection.md
  docs/resources/action_connection.md
  examples/data-sources/datadog_action_connection/data-source.tf
  examples/resources/datadog_action_connection/import.sh
  examples/resources/datadog_action_connection/resource.tf
Labels: changelog/feature
