Repository DataDog/terraform-provider-datadog, pull requests merged in 2025-01, with the labels that each got.

#2746 [datadog_integration_aws_account] Fix error message wording
  datadog/fwprovider/resource_datadog_integration_aws_account.go
Labels: changelog/no-changelog

#2732 [datadog_logs_pipelines_order] Add datasource for Logs Pipelines Order
  datadog/fwprovider/data_source_datadog_logs_pipelines_order.go
  datadog/fwprovider/framework_provider.go
  datadog/tests/cassettes/TestAccDatadogLogsPipelinesOrderDatasource.freeze
  datadog/tests/cassettes/TestAccDatadogLogsPipelinesOrderDatasource.yaml
  datadog/tests/data_source_datadog_logs_pipelines_order_test.go
  datadog/tests/provider_test.go
  docs/data-sources/logs_pipelines_order.md
  examples/data-sources/datadog_logs_pipelines_order/data-source.tf
Labels: changelog/feature, mergequeue-status: in_progress

#2749 [datadog_integration_aws_account] Fix panic when resources_config is omitted
  datadog/fwprovider/resource_datadog_integration_aws_account.go
Labels: changelog/bugfix, mergequeue-status: in_progress

#2738 [AZINTS-2487] Update Azure integration terraform to support metric filitering
  datadog/fwprovider/resource_datadog_azure_integration.go
  docs/resources/integration_azure.md
Labels: changelog/no-changelog, azure-integrations

#2752 Revert "[AZINTS-2487] Update Azure integration terraform to support metric filitering"
  datadog/fwprovider/resource_datadog_azure_integration.go
  docs/resources/integration_azure.md
Labels: changelog/no-changelog

#2710 [resource_datadog_role] ACCESS-2867 - Support `default_permissions_opt_out` attribute in Terraform
  datadog/resource_datadog_role.go
  datadog/tests/cassettes/TestAccDatadogRole_CreateUpdate.freeze
  datadog/tests/cassettes/TestAccDatadogRole_CreateUpdate.yaml
  datadog/tests/cassettes/TestAccDatadogRole_InvalidPerm.freeze
  datadog/tests/cassettes/TestAccDatadogRole_InvalidPerm.yaml
  datadog/tests/resource_datadog_role_test.go
  docs/resources/role.md
  scripts/generate-docs.sh
Labels: changelog/improvement, aaa-access, mergequeue-status: rejected

#2760 [datadog_application_key] Support scoped app key management
  datadog/fwprovider/data_source_datadog_application_key.go
  datadog/fwprovider/resource_datadog_application_key.go
  datadog/tests/resource_datadog_application_key_test.go
  docs/data-sources/application_key.md
  docs/resources/application_key.md
Labels: changelog/feature, mergequeue-status: rejected

#2763 [datadog_application_key] use plan modifiers for app keys
  datadog/fwprovider/resource_datadog_application_key.go
Labels: changelog/bugfix

#2765 [datadog_api_key] Use plan modifier for API keys.
  .github/CODEOWNERS
  datadog/fwprovider/resource_datadog_api_key.go
Labels: changelog/bugfix

#2764 [datadog_security_monitoring_suppression] Add Start to Suppressions
  datadog/fwprovider/data_source_security_monitoring_suppression.go
  datadog/fwprovider/resource_datadog_security_monitoring_suppression.go
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateAndUpdateDataExclusionQuery.freeze
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateAndUpdateDataExclusionQuery.yaml
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateAndUpdateWithoutDates.freeze
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateAndUpdateWithoutDates.yaml
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateAndUpdateWithoutStartAndExpirationDates.freeze
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateThenAddAndRemoveExpirationDate.freeze
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateThenAddAndRemoveExpirationDate.yaml
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateThenAddAndRemoveStartDate.freeze
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateThenAddAndRemoveStartDate.yaml
  datadog/tests/resource_datadog_security_monitoring_suppression_test.go
  docs/data-sources/security_monitoring_suppressions.md
  docs/resources/security_monitoring_suppression.md
  examples/resources/datadog_security_monitoring_suppression/resource.tf
  go.mod
  go.sum
Labels: changelog/feature

#2757 [datadog_azure_integration] Support metric filitering
  datadog/fwprovider/resource_datadog_azure_integration.go
  docs/resources/integration_azure.md
Labels: changelog/feature, azure-integrations

#2774 [data_datadog_application_key] remove scopes from schema
  datadog/fwprovider/data_source_datadog_application_key.go
  docs/data-sources/application_key.md
Labels: changelog/bugfix

#2778 Revert "[datadog_azure_integration] Support metric filitering"
  datadog/fwprovider/resource_datadog_azure_integration.go
  docs/resources/integration_azure.md
Labels: changelog/no-changelog

#2780 [datadog_security_monitoring_suppression] Add Start to Suppressions
  datadog/fwprovider/data_source_security_monitoring_suppression.go
  datadog/fwprovider/resource_datadog_security_monitoring_suppression.go
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateAndUpdateDataExclusionQuery.freeze
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateAndUpdateDataExclusionQuery.yaml
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateAndUpdateWithoutDates.freeze
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateAndUpdateWithoutDates.yaml
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateAndUpdateWithoutStartAndExpirationDates.freeze
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateThenAddAndRemoveExpirationDate.freeze
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateThenAddAndRemoveExpirationDate.yaml
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateThenAddAndRemoveStartDate.freeze
  datadog/tests/cassettes/TestAccSecurityMonitoringSuppression_CreateThenAddAndRemoveStartDate.yaml
  datadog/tests/resource_datadog_security_monitoring_suppression_test.go
  docs/data-sources/security_monitoring_suppressions.md
  docs/resources/security_monitoring_suppression.md
  examples/resources/datadog_security_monitoring_suppression/resource.tf
  go.mod
  go.sum
Labels: changelog/feature

#2781 [datadog_azure_integration] Support metric filtering
  datadog/fwprovider/resource_datadog_azure_integration.go
  docs/resources/integration_azure.md
Labels: changelog/feature

#2783 [datadog_azure_integration] change default value of `resource_provider_configs` and rerecord tests
  datadog/fwprovider/resource_datadog_azure_integration.go
  datadog/tests/cassettes/TestAccDatadogIntegrationAzure.freeze
  datadog/tests/cassettes/TestAccDatadogIntegrationAzure.yaml
  datadog/tests/cassettes/TestAccDatadogLogsArchiveAzure_basic.freeze
  datadog/tests/cassettes/TestAccDatadogLogsArchiveAzure_basic.yaml
  docs/resources/monitor.md
  go.mod
  go.sum
Labels: changelog/bugfix

#2791 Set the SHA hash for the GitHub actions.
  .github/workflows/changelog.yaml
  .github/workflows/prepare_release.yml
  .github/workflows/release.yml
  .github/workflows/sdkv2_deprecation.yaml
  .github/workflows/test.yml
  .github/workflows/test_integration.yml
Labels: changelog/no-changelog

#2803 [datadog_synthetics_test] duplication of default info
  datadog/resource_datadog_synthetics_test_.go
  docs/resources/synthetics_test.md
Labels: changelog/no-changelog

#2770 [datadog_application_key] Support scoped app key management for service accounts
  datadog/fwprovider/resource_datadog_service_account_application_key.go
  datadog/tests/resource_datadog_application_key_test.go
  datadog/tests/resource_datadog_service_account_application_key_test.go
  docs/resources/service_account_application_key.md
Labels: changelog/feature, aaa-access, mergequeue-status: rejected

#2807 Update API Clients team to include Web Frameworks team
  .github/CODEOWNERS
Labels: changelog/no-changelog

#2769 [datadog_monitor] Add cost alert monitors
  datadog/resource_datadog_monitor.go
  datadog/tests/cassettes/TestAccDatadogMonitor_FormulaFunction_Cost.freeze
  datadog/tests/cassettes/TestAccDatadogMonitor_FormulaFunction_Cost.yaml
  datadog/tests/resource_datadog_monitor_test.go
  docs/resources/monitor.md
  go.mod
  go.sum
Labels: changelog/feature, mergequeue-status: in_progress
